const quizList = [
    {
      no: 1,
      word: "吧",
      word_traditional: "吧",
      pinyin: "ba",
      zh: "我们去吃饭吧。",
      zh_traditional: "我們去吃飯吧。",
      zh_pinyin: "wǒmen qù chīfàn ba.",
      ko: "우리 밥 먹으러 가자.",
      meaning_ko: "추측, 제안의 어기조사",
      meanings_extra: ["~하자", "~일 거야"],
      part_of_speech: "조사"
    },
    {
      no: 2,
      word: "白",
      word_traditional: "白",
      pinyin: "bái",
      zh: "她的衣服是白色的。",
      zh_traditional: "她的衣服是白色的。",
      zh_pinyin: "tā de yīfu shì báisè de.",
      ko: "그녀의 옷은 하얗다.",
      meaning_ko: "하얗다, 밝다",
      meanings_extra: [],
      part_of_speech: "형용사"
    },
    {
      no: 3,
      word: "百",
      word_traditional: "百",
      pinyin: "bǎi",
      zh: "他有一百本书。",
      zh_traditional: "他有一百本書。",
      zh_pinyin: "tā yǒu yī bǎi běn shū.",
      ko: "그는 책 백 권이 있다.",
      meaning_ko: "100",
      meanings_extra: ["백"],
      part_of_speech: "수사"
    },
    {
      no: 4,
      word: "帮助",
      word_traditional: "幫助",
      pinyin: "bāngzhù",
      zh: "他帮助我学习中文。",
      zh_traditional: "他幫助我學習中文。",
      zh_pinyin: "tā bāngzhù wǒ xuéxí Zhōngwén.",
      ko: "그는 나의 중국어 공부를 도와준다.",
      meaning_ko: "돕다",
      meanings_extra: ["도움 주다"],
      part_of_speech: "동사"
    },
    {
      no: 5,
      word: "报纸",
      word_traditional: "報紙",
      pinyin: "bàozhǐ",
      zh: "我每天看报纸。",
      zh_traditional: "我每天看報紙。",
      zh_pinyin: "wǒ měitiān kàn bàozhǐ.",
      ko: "나는 매일 신문을 본다.",
      meaning_ko: "신문",
      meanings_extra: [],
      part_of_speech: "명사"
    },
    {
      no: 6,
      word: "比",
      word_traditional: "比",
      pinyin: "bǐ",
      zh: "我比你高。",
      zh_traditional: "我比你高。",
      zh_pinyin: "wǒ bǐ nǐ gāo.",
      ko: "나는 너보다 키가 크다.",
      meaning_ko: "~에 비해",
      meanings_extra: ["더"],
      part_of_speech: "전치사"
    },
    {
      no: 7,
      word: "别",
      word_traditional: "別",
      pinyin: "bié",
      zh: "别走！",
      zh_traditional: "別走！",
      zh_pinyin: "bié zǒu!",
      ko: "가지 마!",
      meaning_ko: "~하지 마라",
      meanings_extra: [],
      part_of_speech: "부사"
    },
    {
      no: 8,
      word: "宾馆",
      word_traditional: "賓館",
      pinyin: "bīnguǎn",
      zh: "我们住在宾馆。",
      zh_traditional: "我們住在賓館。",
      zh_pinyin: "wǒmen zhù zài bīnguǎn.",
      ko: "우리는 호텔에 묵는다.",
      meaning_ko: "호텔",
      meanings_extra: [],
      part_of_speech: "명사"
    },
    {
      no: 9,
      word: "长",
      word_traditional: "長",
      pinyin: "cháng",
      zh: "这条路很长。",
      zh_traditional: "這條路很長。",
      zh_pinyin: "zhè tiáo lù hěn cháng.",
      ko: "이 길은 매우 길다.",
      meaning_ko: "길다",
      meanings_extra: ["긴"],
      part_of_speech: "형용사"
    },
    {
      no: 10,
      word: "唱歌",
      word_traditional: "唱歌",
      pinyin: "chànggē",
      zh: "他们喜欢唱歌。",
      zh_traditional: "他們喜歡唱歌。",
      zh_pinyin: "tāmen xǐhuan chànggē.",
      ko: "그들은 노래 부르는 것을 좋아한다.",
      meaning_ko: "노래 부르다",
      meanings_extra: [],
      part_of_speech: "동사"
    },
    {
      no: 11,
      word: "出",
      word_traditional: "出",
      pinyin: "chū",
      zh: "他出去了。",
      zh_traditional: "他出去了。",
      zh_pinyin: "tā chūqù le.",
      ko: "그는 나갔다.",
      meaning_ko: "나가다, 나오다",
      meanings_extra: [],
      part_of_speech: "동사"
    },
    {
      no: 12,
      word: "穿",
      word_traditional: "穿",
      pinyin: "chuān",
      zh: "她穿了新衣服。",
      zh_traditional: "她穿了新衣服。",
      zh_pinyin: "tā chuān le xīn yīfu.",
      ko: "그녀는 새 옷을 입었다.",
      meaning_ko: "입다, 신다",
      meanings_extra: [],
      part_of_speech: "동사"
    },
    {
      no: 13,
      word: "次",
      word_traditional: "次",
      pinyin: "cì",
      zh: "我去过三次北京。",
      zh_traditional: "我去過三次北京。",
      zh_pinyin: "wǒ qù guo sān cì Běijīng.",
      ko: "나는 베이징에 세 번 가본 적 있다.",
      meaning_ko: "차례, 번, 회",
      meanings_extra: [],
      part_of_speech: "명사"
    },
    {
      no: 14,
      word: "从",
      word_traditional: "從",
      pinyin: "cóng",
      zh: "他从家里来。",
      zh_traditional: "他從家裡來。",
      zh_pinyin: "tā cóng jiā lǐ lái.",
      ko: "그는 집에서 왔다.",
      meaning_ko: "~부터",
      meanings_extra: ["~에서부터"],
      part_of_speech: "전치사"
    },
    {
      no: 15,
      word: "错",
      word_traditional: "錯",
      pinyin: "cuò",
      zh: "我写错了。",
      zh_traditional: "我寫錯了。",
      zh_pinyin: "wǒ xiě cuò le.",
      ko: "나는 잘못 썼다.",
      meaning_ko: "틀리다",
      meanings_extra: ["잘못되다"],
      part_of_speech: "형용사"
    },
    {
      no: 16,
      word: "打篮球",
      word_traditional: "打籃球",
      pinyin: "dǎ lánqiú",
      zh: "他喜欢打篮球。",
      zh_traditional: "他喜歡打籃球。",
      zh_pinyin: "tā xǐhuan dǎ lánqiú.",
      ko: "그는 농구하는 것을 좋아한다.",
      meaning_ko: "농구를 하다",
      meanings_extra: [],
      part_of_speech: "동사구"
    },
    {
      no: 17,
      word: "大家",
      word_traditional: "大家",
      pinyin: "dàjiā",
      zh: "大家好！",
      zh_traditional: "大家好！",
      zh_pinyin: "dàjiā hǎo!",
      ko: "여러분, 안녕하세요!",
      meaning_ko: "모두",
      meanings_extra: ["모두들"],
      part_of_speech: "대명사"
    },
    {
      no: 18,
      word: "到",
      word_traditional: "到",
      pinyin: "dào",
      zh: "我到了学校。",
      zh_traditional: "我到了學校。",
      zh_pinyin: "wǒ dào le xuéxiào.",
      ko: "나는 학교에 도착했다.",
      meaning_ko: "도착하다, 도달하다",
      meanings_extra: [],
      part_of_speech: "동사"
    },
    {
      no: 19,
      word: "得",
      word_traditional: "得",
      pinyin: "de",
      zh: "他跑得快。",
      zh_traditional: "他跑得快。",
      zh_pinyin: "tā pǎo de kuài.",
      ko: "그는 빨리 뛴다.",
      meaning_ko: "~게, ~도",
      meanings_extra: ["결과 보어 연결"],
      part_of_speech: "조사"
    },
    {
      no: 20,
      word: "等",
      word_traditional: "等",
      pinyin: "děng",
      zh: "我在等你。",
      zh_traditional: "我在等你。",
      zh_pinyin: "wǒ zài děng nǐ.",
      ko: "나는 너를 기다리고 있다.",
      meaning_ko: "기다리다",
      meanings_extra: [],
      part_of_speech: "동사"
    },
    {
        no: 21,
        word: "弟弟",
        word_traditional: "弟弟",
        pinyin: "dìdi",
        zh: "我有一个弟弟。",
        zh_traditional: "我有一個弟弟。",
        zh_pinyin: "wǒ yǒu yí gè dìdi.",
        ko: "나는 남동생이 한 명 있다.",
        meaning_ko: "남동생",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 22,
        word: "第一",
        word_traditional: "第一",
        pinyin: "dì yī",
        zh: "他是第一名。",
        zh_traditional: "他是第一名。",
        zh_pinyin: "tā shì dì yī míng.",
        ko: "그는 1등이다.",
        meaning_ko: "제1, 첫 번째",
        meanings_extra: [],
        part_of_speech: "수사"
      },
      {
        no: 23,
        word: "懂",
        word_traditional: "懂",
        pinyin: "dǒng",
        zh: "我懂你的意思。",
        zh_traditional: "我懂你的意思。",
        zh_pinyin: "wǒ dǒng nǐ de yìsi.",
        ko: "나는 네 뜻을 이해한다.",
        meaning_ko: "알다, 이해하다",
        meanings_extra: [],
        part_of_speech: "동사"
      },
      {
        no: 24,
        word: "对",
        word_traditional: "對",
        pinyin: "duì",
        zh: "你的答案对。",
        zh_traditional: "你的答案對。",
        zh_pinyin: "nǐ de dá'àn duì.",
        ko: "네 답이 맞다.",
        meaning_ko: "맞다, 옳다",
        meanings_extra: ["~에게", "~에 대하여"],
        part_of_speech: "형용사/전치사"
      },
      {
        no: 25,
        word: "房间",
        word_traditional: "房間",
        pinyin: "fángjiān",
        zh: "我的房间很大。",
        zh_traditional: "我的房間很大。",
        zh_pinyin: "wǒ de fángjiān hěn dà.",
        ko: "내 방은 크다.",
        meaning_ko: "방",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 26,
        word: "非常",
        word_traditional: "非常",
        pinyin: "fēicháng",
        zh: "今天天气非常好。",
        zh_traditional: "今天天氣非常好。",
        zh_pinyin: "jīntiān tiānqì fēicháng hǎo.",
        ko: "오늘 날씨가 매우 좋다.",
        meaning_ko: "매우, 대단히",
        meanings_extra: [],
        part_of_speech: "부사"
      },
      {
        no: 27,
        word: "服务员",
        word_traditional: "服務員",
        pinyin: "fúwùyuán",
        zh: "服务员，请帮我。",
        zh_traditional: "服務員，請幫我。",
        zh_pinyin: "fúwùyuán, qǐng bāng wǒ.",
        ko: "웨이터, 저 좀 도와주세요.",
        meaning_ko: "종업원",
        meanings_extra: ["서비스 직원"],
        part_of_speech: "명사"
      },
      {
        no: 28,
        word: "高",
        word_traditional: "高",
        pinyin: "gāo",
        zh: "他很高。",
        zh_traditional: "他很高。",
        zh_pinyin: "tā hěn gāo.",
        ko: "그는 키가 크다.",
        meaning_ko: "높다, 키가 크다",
        meanings_extra: [],
        part_of_speech: "형용사"
      },
      {
        no: 29,
        word: "告诉",
        word_traditional: "告訴",
        pinyin: "gàosu",
        zh: "请告诉我真相。",
        zh_traditional: "請告訴我真相。",
        zh_pinyin: "qǐng gàosu wǒ zhēnxiàng.",
        ko: "제발 진실을 말해 주세요.",
        meaning_ko: "말하다, 알리다",
        meanings_extra: [],
        part_of_speech: "동사"
      },
      {
        no: 30,
        word: "哥哥",
        word_traditional: "哥哥",
        pinyin: "gēge",
        zh: "我有一个哥哥。",
        zh_traditional: "我有一個哥哥。",
        zh_pinyin: "wǒ yǒu yí gè gēge.",
        ko: "나는 형이 한 명 있다.",
        meaning_ko: "형, 오빠",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 31,
        word: "给",
        word_traditional: "給",
        pinyin: "gěi",
        zh: "我给你一本书。",
        zh_traditional: "我給你一本書。",
        zh_pinyin: "wǒ gěi nǐ yì běn shū.",
        ko: "나는 너에게 책 한 권을 준다.",
        meaning_ko: "~에게 ~을 주다",
        meanings_extra: [],
        part_of_speech: "동사"
      },
      {
        no: 32,
        word: "公共汽车",
        word_traditional: "公共汽車",
        pinyin: "gōnggòng qìchē",
        zh: "我坐公共汽车去学校。",
        zh_traditional: "我坐公共汽車去學校。",
        zh_pinyin: "wǒ zuò gōnggòng qìchē qù xuéxiào.",
        ko: "나는 버스를 타고 학교에 간다.",
        meaning_ko: "버스",
        meanings_extra: ["공공버스"],
        part_of_speech: "명사"
      },
      {
        no: 33,
        word: "公司",
        word_traditional: "公司",
        pinyin: "gōngsī",
        zh: "他在公司工作。",
        zh_traditional: "他在公司工作。",
        zh_pinyin: "tā zài gōngsī gōngzuò.",
        ko: "그는 회사에서 일한다.",
        meaning_ko: "회사",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 34,
        word: "贵",
        word_traditional: "貴",
        pinyin: "guì",
        zh: "这件衣服很贵。",
        zh_traditional: "這件衣服很貴。",
        zh_pinyin: "zhè jiàn yīfu hěn guì.",
        ko: "이 옷은 매우 비싸다.",
        meaning_ko: "비싸다",
        meanings_extra: [],
        part_of_speech: "형용사"
      },
      {
        no: 35,
        word: "过",
        word_traditional: "過",
        pinyin: "guò",
        zh: "我去过北京。",
        zh_traditional: "我去過北京。",
        zh_pinyin: "wǒ qù guò Běijīng.",
        ko: "나는 베이징에 가본 적이 있다.",
        meaning_ko: "경험을 나타내는 동사 뒤 보어",
        meanings_extra: ["지나가다"],
        part_of_speech: "조사/동사"
      },
      {
        no: 36,
        word: "还",
        word_traditional: "還",
        pinyin: "hái",
        zh: "他还在学校。",
        zh_traditional: "他還在學校。",
        zh_pinyin: "tā hái zài xuéxiào.",
        ko: "그는 아직 학교에 있다.",
        meaning_ko: "아직도, 여전히",
        meanings_extra: [],
        part_of_speech: "부사"
      },
      {
        no: 37,
        word: "孩子",
        word_traditional: "孩子",
        pinyin: "háizi",
        zh: "他有两个孩子。",
        zh_traditional: "他有兩個孩子。",
        zh_pinyin: "tā yǒu liǎng gè háizi.",
        ko: "그는 아이가 두 명 있다.",
        meaning_ko: "아이, 자녀",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 38,
        word: "好吃",
        word_traditional: "好吃",
        pinyin: "hǎochī",
        zh: "这个菜很好吃。",
        zh_traditional: "這個菜很好吃。",
        zh_pinyin: "zhège cài hěn hǎochī.",
        ko: "이 음식은 맛있다.",
        meaning_ko: "맛있다",
        meanings_extra: [],
        part_of_speech: "형용사"
      },
      {
        no: 39,
        word: "黑",
        word_traditional: "黑",
        pinyin: "hēi",
        zh: "这只猫是黑色的。",
        zh_traditional: "這隻貓是黑色的。",
        zh_pinyin: "zhè zhī māo shì hēisè de.",
        ko: "이 고양이는 검은색이다.",
        meaning_ko: "어둡다, 까맣다",
        meanings_extra: [],
        part_of_speech: "형용사"
      },
      {
        no: 40,
        word: "红",
        word_traditional: "紅",
        pinyin: "hóng",
        zh: "苹果是红色的。",
        zh_traditional: "蘋果是紅色的。",
        zh_pinyin: "píngguǒ shì hóngsè de.",
        ko: "사과는 빨간색이다.",
        meaning_ko: "붉다, 빨갛다",
        meanings_extra: [],
        part_of_speech: "형용사"
      },
      {
        no: 21,
        word: "弟弟",
        word_traditional: "弟弟",
        pinyin: "dìdi",
        zh: "我有一个弟弟。",
        zh_traditional: "我有一個弟弟。",
        zh_pinyin: "wǒ yǒu yí gè dìdi.",
        ko: "나는 남동생이 한 명 있다.",
        meaning_ko: "남동생",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 22,
        word: "第一",
        word_traditional: "第一",
        pinyin: "dì yī",
        zh: "他是第一名。",
        zh_traditional: "他是第一名。",
        zh_pinyin: "tā shì dì yī míng.",
        ko: "그는 1등이다.",
        meaning_ko: "제1, 첫 번째",
        meanings_extra: [],
        part_of_speech: "수사"
      },
      {
        no: 23,
        word: "懂",
        word_traditional: "懂",
        pinyin: "dǒng",
        zh: "我懂你的意思。",
        zh_traditional: "我懂你的意思。",
        zh_pinyin: "wǒ dǒng nǐ de yìsi.",
        ko: "나는 네 뜻을 이해한다.",
        meaning_ko: "알다, 이해하다",
        meanings_extra: [],
        part_of_speech: "동사"
      },
      {
        no: 24,
        word: "对",
        word_traditional: "對",
        pinyin: "duì",
        zh: "你的答案对。",
        zh_traditional: "你的答案對。",
        zh_pinyin: "nǐ de dá'àn duì.",
        ko: "네 답이 맞다.",
        meaning_ko: "맞다, 옳다",
        meanings_extra: ["~에게", "~에 대하여"],
        part_of_speech: "형용사/전치사"
      },
      {
        no: 25,
        word: "房间",
        word_traditional: "房間",
        pinyin: "fángjiān",
        zh: "我的房间很大。",
        zh_traditional: "我的房間很大。",
        zh_pinyin: "wǒ de fángjiān hěn dà.",
        ko: "내 방은 크다.",
        meaning_ko: "방",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 26,
        word: "非常",
        word_traditional: "非常",
        pinyin: "fēicháng",
        zh: "今天天气非常好。",
        zh_traditional: "今天天氣非常好。",
        zh_pinyin: "jīntiān tiānqì fēicháng hǎo.",
        ko: "오늘 날씨가 매우 좋다.",
        meaning_ko: "매우, 대단히",
        meanings_extra: [],
        part_of_speech: "부사"
      },
      {
        no: 27,
        word: "服务员",
        word_traditional: "服務員",
        pinyin: "fúwùyuán",
        zh: "服务员，请帮我。",
        zh_traditional: "服務員，請幫我。",
        zh_pinyin: "fúwùyuán, qǐng bāng wǒ.",
        ko: "웨이터, 저 좀 도와주세요.",
        meaning_ko: "종업원",
        meanings_extra: ["서비스 직원"],
        part_of_speech: "명사"
      },
      {
        no: 28,
        word: "高",
        word_traditional: "高",
        pinyin: "gāo",
        zh: "他很高。",
        zh_traditional: "他很高。",
        zh_pinyin: "tā hěn gāo.",
        ko: "그는 키가 크다.",
        meaning_ko: "높다, 키가 크다",
        meanings_extra: [],
        part_of_speech: "형용사"
      },
      {
        no: 29,
        word: "告诉",
        word_traditional: "告訴",
        pinyin: "gàosu",
        zh: "请告诉我真相。",
        zh_traditional: "請告訴我真相。",
        zh_pinyin: "qǐng gàosu wǒ zhēnxiàng.",
        ko: "제발 진실을 말해 주세요.",
        meaning_ko: "말하다, 알리다",
        meanings_extra: [],
        part_of_speech: "동사"
      },
      {
        no: 30,
        word: "哥哥",
        word_traditional: "哥哥",
        pinyin: "gēge",
        zh: "我有一个哥哥。",
        zh_traditional: "我有一個哥哥。",
        zh_pinyin: "wǒ yǒu yí gè gēge.",
        ko: "나는 형이 한 명 있다.",
        meaning_ko: "형, 오빠",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 31,
        word: "给",
        word_traditional: "給",
        pinyin: "gěi",
        zh: "我给你一本书。",
        zh_traditional: "我給你一本書。",
        zh_pinyin: "wǒ gěi nǐ yì běn shū.",
        ko: "나는 너에게 책 한 권을 준다.",
        meaning_ko: "~에게 ~을 주다",
        meanings_extra: [],
        part_of_speech: "동사"
      },
      {
        no: 32,
        word: "公共汽车",
        word_traditional: "公共汽車",
        pinyin: "gōnggòng qìchē",
        zh: "我坐公共汽车去学校。",
        zh_traditional: "我坐公共汽車去學校。",
        zh_pinyin: "wǒ zuò gōnggòng qìchē qù xuéxiào.",
        ko: "나는 버스를 타고 학교에 간다.",
        meaning_ko: "버스",
        meanings_extra: ["공공버스"],
        part_of_speech: "명사"
      },
      {
        no: 33,
        word: "公司",
        word_traditional: "公司",
        pinyin: "gōngsī",
        zh: "他在公司工作。",
        zh_traditional: "他在公司工作。",
        zh_pinyin: "tā zài gōngsī gōngzuò.",
        ko: "그는 회사에서 일한다.",
        meaning_ko: "회사",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 34,
        word: "贵",
        word_traditional: "貴",
        pinyin: "guì",
        zh: "这件衣服很贵。",
        zh_traditional: "這件衣服很貴。",
        zh_pinyin: "zhè jiàn yīfu hěn guì.",
        ko: "이 옷은 매우 비싸다.",
        meaning_ko: "비싸다",
        meanings_extra: [],
        part_of_speech: "형용사"
      },
      {
        no: 35,
        word: "过",
        word_traditional: "過",
        pinyin: "guò",
        zh: "我去过北京。",
        zh_traditional: "我去過北京。",
        zh_pinyin: "wǒ qù guò Běijīng.",
        ko: "나는 베이징에 가본 적이 있다.",
        meaning_ko: "경험을 나타내는 동사 뒤 보어",
        meanings_extra: ["지나가다"],
        part_of_speech: "조사/동사"
      },
      {
        no: 36,
        word: "还",
        word_traditional: "還",
        pinyin: "hái",
        zh: "他还在学校。",
        zh_traditional: "他還在學校。",
        zh_pinyin: "tā hái zài xuéxiào.",
        ko: "그는 아직 학교에 있다.",
        meaning_ko: "아직도, 여전히",
        meanings_extra: [],
        part_of_speech: "부사"
      },
      {
        no: 37,
        word: "孩子",
        word_traditional: "孩子",
        pinyin: "háizi",
        zh: "他有两个孩子。",
        zh_traditional: "他有兩個孩子。",
        zh_pinyin: "tā yǒu liǎng gè háizi.",
        ko: "그는 아이가 두 명 있다.",
        meaning_ko: "아이, 자녀",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 38,
        word: "好吃",
        word_traditional: "好吃",
        pinyin: "hǎochī",
        zh: "这个菜很好吃。",
        zh_traditional: "這個菜很好吃。",
        zh_pinyin: "zhège cài hěn hǎochī.",
        ko: "이 음식은 맛있다.",
        meaning_ko: "맛있다",
        meanings_extra: [],
        part_of_speech: "형용사"
      },
      {
        no: 39,
        word: "黑",
        word_traditional: "黑",
        pinyin: "hēi",
        zh: "这只猫是黑色的。",
        zh_traditional: "這隻貓是黑色的。",
        zh_pinyin: "zhè zhī māo shì hēisè de.",
        ko: "이 고양이는 검은색이다.",
        meaning_ko: "어둡다, 까맣다",
        meanings_extra: [],
        part_of_speech: "형용사"
      },
      {
        no: 40,
        word: "红",
        word_traditional: "紅",
        pinyin: "hóng",
        zh: "苹果是红色的。",
        zh_traditional: "蘋果是紅色的。",
        zh_pinyin: "píngguǒ shì hóngsè de.",
        ko: "사과는 빨간색이다.",
        meaning_ko: "붉다, 빨갛다",
        meanings_extra: [],
        part_of_speech: "형용사"
      },
      {
        no: 61,
        word: "离",
        word_traditional: "離",
        pinyin: "lí",
        zh: "学校离家很近。",
        zh_traditional: "學校離家很近。",
        zh_pinyin: "xuéxiào lí jiā hěn jìn.",
        ko: "학교가 집에서 매우 가깝다.",
        meaning_ko: "~에서 떨어지다",
        meanings_extra: ["떨어져 있다"],
        part_of_speech: "전치사"
      },
      {
        no: 62,
        word: "两",
        word_traditional: "兩",
        pinyin: "liǎng",
        zh: "我有两本书。",
        zh_traditional: "我有兩本書。",
        zh_pinyin: "wǒ yǒu liǎng běn shū.",
        ko: "나는 책 두 권이 있다.",
        meaning_ko: "둘, 2",
        meanings_extra: ["두 개"],
        part_of_speech: "수사"
      },
      {
        no: 63,
        word: "零",
        word_traditional: "零",
        pinyin: "líng",
        zh: "今天是零度。",
        zh_traditional: "今天是零度。",
        zh_pinyin: "jīntiān shì líng dù.",
        ko: "오늘은 영도이다.",
        meaning_ko: "영, 0",
        meanings_extra: ["제로"],
        part_of_speech: "수사"
      },
      {
        no: 64,
        word: "路",
        word_traditional: "路",
        pinyin: "lù",
        zh: "这条路很宽。",
        zh_traditional: "這條路很寬。",
        zh_pinyin: "zhè tiáo lù hěn kuān.",
        ko: "이 길은 매우 넓다.",
        meaning_ko: "길, 도로",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 65,
        word: "旅游",
        word_traditional: "旅遊",
        pinyin: "lǚyóu",
        zh: "我喜欢旅游。",
        zh_traditional: "我喜歡旅遊。",
        zh_pinyin: "wǒ xǐhuan lǚyóu.",
        ko: "나는 여행하는 것을 좋아한다.",
        meaning_ko: "여행하다",
        meanings_extra: [],
        part_of_speech: "동사"
      },
      {
        no: 66,
        word: "卖",
        word_traditional: "賣",
        pinyin: "mài",
        zh: "他卖水果。",
        zh_traditional: "他賣水果。",
        zh_pinyin: "tā mài shuǐguǒ.",
        ko: "그는 과일을 판다.",
        meaning_ko: "팔다",
        meanings_extra: [],
        part_of_speech: "동사"
      },
      {
        no: 67,
        word: "慢",
        word_traditional: "慢",
        pinyin: "màn",
        zh: "他走得很慢。",
        zh_traditional: "他走得很慢。",
        zh_pinyin: "tā zǒu de hěn màn.",
        ko: "그는 매우 천천히 걷는다.",
        meaning_ko: "느리다",
        meanings_extra: [],
        part_of_speech: "형용사"
      },
      {
        no: 68,
        word: "忙",
        word_traditional: "忙",
        pinyin: "máng",
        zh: "我很忙。",
        zh_traditional: "我很忙。",
        zh_pinyin: "wǒ hěn máng.",
        ko: "나는 매우 바쁘다.",
        meaning_ko: "바쁘다",
        meanings_extra: [],
        part_of_speech: "형용사"
      },
      {
        no: 69,
        word: "每",
        word_traditional: "每",
        pinyin: "měi",
        zh: "我每天喝水。",
        zh_traditional: "我每天喝水。",
        zh_pinyin: "wǒ měitiān hē shuǐ.",
        ko: "나는 매일 물을 마신다.",
        meaning_ko: "매, 각",
        meanings_extra: ["~마다"],
        part_of_speech: "부사"
      },
      {
        no: 70,
        word: "妹妹",
        word_traditional: "妹妹",
        pinyin: "mèimei",
        zh: "我有一个妹妹。",
        zh_traditional: "我有一個妹妹。",
        zh_pinyin: "wǒ yǒu yí gè mèimei.",
        ko: "나는 여동생이 한 명 있다.",
        meaning_ko: "여동생",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 71,
        word: "门",
        word_traditional: "門",
        pinyin: "mén",
        zh: "门开着。",
        zh_traditional: "門開著。",
        zh_pinyin: "mén kāi zhe.",
        ko: "문이 열려 있다.",
        meaning_ko: "문",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 72,
        word: "面条儿",
        word_traditional: "麵條兒",
        pinyin: "miàntiáor",
        zh: "我喜欢吃面条儿。",
        zh_traditional: "我喜歡吃麵條兒。",
        zh_pinyin: "wǒ xǐhuan chī miàntiáor.",
        ko: "나는 국수를 먹는 것을 좋아한다.",
        meaning_ko: "국수",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 73,
        word: "男",
        word_traditional: "男",
        pinyin: "nán",
        zh: "他是男学生。",
        zh_traditional: "他是男學生。",
        zh_pinyin: "tā shì nán xuésheng.",
        ko: "그는 남자 학생이다.",
        meaning_ko: "남자",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 74,
        word: "您",
        word_traditional: "您",
        pinyin: "nín",
        zh: "您好！",
        zh_traditional: "您好！",
        zh_pinyin: "nín hǎo!",
        ko: "안녕하세요! (존댓말)",
        meaning_ko: "당신 (존칭)",
        meanings_extra: [],
        part_of_speech: "대명사"
      },
      {
        no: 75,
        word: "牛奶",
        word_traditional: "牛奶",
        pinyin: "niúnǎi",
        zh: "我喜欢喝牛奶。",
        zh_traditional: "我喜歡喝牛奶。",
        zh_pinyin: "wǒ xǐhuan hē niúnǎi.",
        ko: "나는 우유 마시는 것을 좋아한다.",
        meaning_ko: "우유",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 76,
        word: "女",
        word_traditional: "女",
        pinyin: "nǚ",
        zh: "她是女学生。",
        zh_traditional: "她是女學生。",
        zh_pinyin: "tā shì nǚ xuésheng.",
        ko: "그녀는 여자 학생이다.",
        meaning_ko: "여자",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 77,
        word: "旁边",
        word_traditional: "旁邊",
        pinyin: "pángbiān",
        zh: "学校旁边有公园。",
        zh_traditional: "學校旁邊有公園。",
        zh_pinyin: "xuéxiào pángbiān yǒu gōngyuán.",
        ko: "학교 옆에 공원이 있다.",
        meaning_ko: "옆, 근처",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 78,
        word: "跑步",
        word_traditional: "跑步",
        pinyin: "pǎobù",
        zh: "我每天跑步。",
        zh_traditional: "我每天跑步。",
        zh_pinyin: "wǒ měitiān pǎobù.",
        ko: "나는 매일 달린다.",
        meaning_ko: "달리다",
        meanings_extra: [],
        part_of_speech: "동사"
      },
      {
        no: 79,
        word: "便宜",
        word_traditional: "便宜",
        pinyin: "piányi",
        zh: "这个很便宜。",
        zh_traditional: "這個很便宜。",
        zh_pinyin: "zhège hěn piányi.",
        ko: "이것은 매우 싸다.",
        meaning_ko: "싸다",
        meanings_extra: [],
        part_of_speech: "형용사"
      },
      {
        no: 80,
        word: "票",
        word_traditional: "票",
        pinyin: "piào",
        zh: "我买了两张票。",
        zh_traditional: "我買了兩張票。",
        zh_pinyin: "wǒ mǎile liǎng zhāng piào.",
        ko: "나는 표 두 장을 샀다.",
        meaning_ko: "표",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 81,
        word: "妻子",
        word_traditional: "妻子",
        pinyin: "qīzi",
        zh: "他爱他的妻子。",
        zh_traditional: "他愛他的妻子。",
        zh_pinyin: "tā ài tā de qīzi.",
        ko: "그는 그의 아내를 사랑한다.",
        meaning_ko: "아내",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 82,
        word: "起床",
        word_traditional: "起床",
        pinyin: "qǐchuáng",
        zh: "我每天七点起床。",
        zh_traditional: "我每天七點起床。",
        zh_pinyin: "wǒ měitiān qī diǎn qǐchuáng.",
        ko: "나는 매일 7시에 일어난다.",
        meaning_ko: "일어나다 (잠자리에서)",
        meanings_extra: [],
        part_of_speech: "동사"
      },
      {
        no: 83,
        word: "千",
        word_traditional: "千",
        pinyin: "qiān",
        zh: "一千个人来了。",
        zh_traditional: "一千個人來了。",
        zh_pinyin: "yī qiān gè rén lái le.",
        ko: "천 명이 왔다.",
        meaning_ko: "천, 1000",
        meanings_extra: [],
        part_of_speech: "수사"
      },
      {
        no: 84,
        word: "铅笔",
        word_traditional: "鉛筆",
        pinyin: "qiānbǐ",
        zh: "我有一支铅笔。",
        zh_traditional: "我有一支鉛筆。",
        zh_pinyin: "wǒ yǒu yì zhī qiānbǐ.",
        ko: "나는 연필 한 자루가 있다.",
        meaning_ko: "연필",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 85,
        word: "晴",
        word_traditional: "晴",
        pinyin: "qíng",
        zh: "今天天气晴。",
        zh_traditional: "今天天氣晴。",
        zh_pinyin: "jīntiān tiānqì qíng.",
        ko: "오늘 날씨가 맑다.",
        meaning_ko: "맑다 (날씨)",
        meanings_extra: [],
        part_of_speech: "형용사"
      },
      {
        no: 86,
        word: "去年",
        word_traditional: "去年",
        pinyin: "qùnián",
        zh: "我去年去了北京。",
        zh_traditional: "我去年去了北京。",
        zh_pinyin: "wǒ qùnián qù le Běijīng.",
        ko: "나는 작년에 베이징에 갔다.",
        meaning_ko: "작년",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 87,
        word: "让",
        word_traditional: "讓",
        pinyin: "ràng",
        zh: "请让他进来。",
        zh_traditional: "請讓他進來。",
        zh_pinyin: "qǐng ràng tā jìnlái.",
        ko: "그를 들어오게 해 주세요.",
        meaning_ko: "~하게 하다, 양보하다",
        meanings_extra: [],
        part_of_speech: "동사"
      },
      {
        no: 88,
        word: "日",
        word_traditional: "日",
        pinyin: "rì",
        zh: "今天是几月几日？",
        zh_traditional: "今天是幾月幾日？",
        zh_pinyin: "jīntiān shì jǐ yuè jǐ rì?",
        ko: "오늘은 몇 월 며칠입니까?",
        meaning_ko: "일 (날짜 단위)",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 89,
        word: "上班",
        word_traditional: "上班",
        pinyin: "shàngbān",
        zh: "我早上八点上班。",
        zh_traditional: "我早上八點上班。",
        zh_pinyin: "wǒ zǎoshang bā diǎn shàngbān.",
        ko: "나는 아침 8시에 출근한다.",
        meaning_ko: "출근하다",
        meanings_extra: [],
        part_of_speech: "동사"
      },
      {
        no: 90,
        word: "身体",
        word_traditional: "身體",
        pinyin: "shēntǐ",
        zh: "他的身体很好。",
        zh_traditional: "他的身體很好。",
        zh_pinyin: "tā de shēntǐ hěn hǎo.",
        ko: "그의 몸이 매우 건강하다.",
        meaning_ko: "몸, 신체",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 91,
        word: "生病",
        word_traditional: "生病",
        pinyin: "shēngbìng",
        zh: "我生病了。",
        zh_traditional: "我生病了。",
        zh_pinyin: "wǒ shēngbìng le.",
        ko: "나는 아팠다.",
        meaning_ko: "병이 나다",
        meanings_extra: [],
        part_of_speech: "동사"
      },
      {
        no: 92,
        word: "生日",
        word_traditional: "生日",
        pinyin: "shēngrì",
        zh: "今天是我的生日。",
        zh_traditional: "今天是我的生日。",
        zh_pinyin: "jīntiān shì wǒ de shēngrì.",
        ko: "오늘은 내 생일이다.",
        meaning_ko: "생일",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 93,
        word: "时间",
        word_traditional: "時間",
        pinyin: "shíjiān",
        zh: "你有时间吗？",
        zh_traditional: "你有時間嗎？",
        zh_pinyin: "nǐ yǒu shíjiān ma?",
        ko: "너는 시간이 있니?",
        meaning_ko: "시간",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 94,
        word: "事情",
        word_traditional: "事情",
        pinyin: "shìqing",
        zh: "这件事情很重要。",
        zh_traditional: "這件事情很重要。",
        zh_pinyin: "zhè jiàn shìqing hěn zhòngyào.",
        ko: "이 일은 매우 중요하다.",
        meaning_ko: "일, 사건",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 95,
        word: "手表",
        word_traditional: "手表",
        pinyin: "shǒubiǎo",
        zh: "我的手表很贵。",
        zh_traditional: "我的手表很貴。",
        zh_pinyin: "wǒ de shǒubiǎo hěn guì.",
        ko: "내 시계는 매우 비싸다.",
        meaning_ko: "손목시계",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 96,
        word: "手机",
        word_traditional: "手機",
        pinyin: "shǒujī",
        zh: "我用手机打电话。",
        zh_traditional: "我用手機打電話。",
        zh_pinyin: "wǒ yòng shǒujī dǎ diànhuà.",
        ko: "나는 휴대폰으로 전화한다.",
        meaning_ko: "휴대전화",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 97,
        word: "说话",
        word_traditional: "說話",
        pinyin: "shuōhuà",
        zh: "他们在说话。",
        zh_traditional: "他們在說話。",
        zh_pinyin: "tāmen zài shuōhuà.",
        ko: "그들은 말하고 있다.",
        meaning_ko: "말하다",
        meanings_extra: [],
        part_of_speech: "동사"
      },
      {
        no: 98,
        word: "送",
        word_traditional: "送",
        pinyin: "sòng",
        zh: "我送你去机场。",
        zh_traditional: "我送你去機場。",
        zh_pinyin: "wǒ sòng nǐ qù jīchǎng.",
        ko: "내가 너를 공항까지 데려다 줄게.",
        meaning_ko: "보내다, 배웅하다",
        meanings_extra: [],
        part_of_speech: "동사"
      },
      {
        no: 99,
        word: "虽然...但是...",
        word_traditional: "雖然...但是...",
        pinyin: "suīrán...dànshì...",
        zh: "虽然下雨，但是我们去公园了。",
        zh_traditional: "雖然下雨，但是我們去公園了。",
        zh_pinyin: "suīrán xiàyǔ, dànshì wǒmen qù gōngyuán le.",
        ko: "비가 왔지만 우리는 공원에 갔다.",
        meaning_ko: "비록 ~하지만 ~하다",
        meanings_extra: [],
        part_of_speech: "접속사"
      },
      {
        no: 100,
        word: "它",
        word_traditional: "它",
        pinyin: "tā",
        zh: "这只猫很可爱，它很小。",
        zh_traditional: "這隻貓很可愛，它很小。",
        zh_pinyin: "zhè zhī māo hěn kě'ài, tā hěn xiǎo.",
        ko: "이 고양이는 귀엽고, 아주 작다.",
        meaning_ko: "그것",
        meanings_extra: [],
        part_of_speech: "대명사"
      },
      {
        no: 101,
        word: "踢足球",
        word_traditional: "踢足球",
        pinyin: "tī zúqiú",
        zh: "他们喜欢踢足球。",
        zh_traditional: "他們喜歡踢足球。",
        zh_pinyin: "tāmen xǐhuan tī zúqiú.",
        ko: "그들은 축구하는 것을 좋아한다.",
        meaning_ko: "축구를 하다",
        meanings_extra: [],
        part_of_speech: "동사"
      },
      {
        no: 102,
        word: "题",
        word_traditional: "題",
        pinyin: "tí",
        zh: "这道题很难。",
        zh_traditional: "這道題很難。",
        zh_pinyin: "zhè dào tí hěn nán.",
        ko: "이 문제는 매우 어렵다.",
        meaning_ko: "문제",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 103,
        word: "跳舞",
        word_traditional: "跳舞",
        pinyin: "tiàowǔ",
        zh: "她喜欢跳舞。",
        zh_traditional: "她喜歡跳舞。",
        zh_pinyin: "tā xǐhuan tiàowǔ.",
        ko: "그녀는 춤추는 것을 좋아한다.",
        meaning_ko: "춤을 추다",
        meanings_extra: [],
        part_of_speech: "동사"
      },
      {
        no: 104,
        word: "外",
        word_traditional: "外",
        pinyin: "wài",
        zh: "他在外面。",
        zh_traditional: "他在外面。",
        zh_pinyin: "tā zài wàimiàn.",
        ko: "그는 밖에 있다.",
        meaning_ko: "겉, 바깥",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 105,
        word: "完",
        word_traditional: "完",
        pinyin: "wán",
        zh: "我做完作业了。",
        zh_traditional: "我做完作業了。",
        zh_pinyin: "wǒ zuò wán zuòyè le.",
        ko: "나는 숙제를 다 했다.",
        meaning_ko: "마치다",
        meanings_extra: ["끝내다"],
        part_of_speech: "동사"
      },
      {
        no: 106,
        word: "玩",
        word_traditional: "玩",
        pinyin: "wán",
        zh: "孩子们在玩。",
        zh_traditional: "孩子們在玩。",
        zh_pinyin: "háizi men zài wán.",
        ko: "아이들이 놀고 있다.",
        meaning_ko: "놀다",
        meanings_extra: [],
        part_of_speech: "동사"
      },
      {
        no: 107,
        word: "晚上",
        word_traditional: "晚上",
        pinyin: "wǎnshang",
        zh: "晚上我去看电影。",
        zh_traditional: "晚上我去看電影。",
        zh_pinyin: "wǎnshang wǒ qù kàn diànyǐng.",
        ko: "저녁에 나는 영화를 보러 간다.",
        meaning_ko: "저녁",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 108,
        word: "往",
        word_traditional: "往",
        pinyin: "wǎng",
        zh: "他往学校走。",
        zh_traditional: "他往學校走。",
        zh_pinyin: "tā wǎng xuéxiào zǒu.",
        ko: "그는 학교 쪽으로 걷는다.",
        meaning_ko: "~쪽으로",
        meanings_extra: ["향하여"],
        part_of_speech: "전치사"
      },
      {
        no: 109,
        word: "为什么",
        word_traditional: "為什麼",
        pinyin: "wèishénme",
        zh: "你为什么迟到？",
        zh_traditional: "你為什麼遲到？",
        zh_pinyin: "nǐ wèishénme chídào?",
        ko: "너 왜 늦었니?",
        meaning_ko: "왜, 어째서",
        meanings_extra: [],
        part_of_speech: "의문사"
      },
      {
        no: 110,
        word: "问",
        word_traditional: "問",
        pinyin: "wèn",
        zh: "我问老师问题。",
        zh_traditional: "我問老師問題。",
        zh_pinyin: "wǒ wèn lǎoshī wèntí.",
        ko: "나는 선생님께 질문을 한다.",
        meaning_ko: "묻다, 질문하다",
        meanings_extra: [],
        part_of_speech: "동사"
      },
      {
        no: 111,
        word: "问题",
        word_traditional: "問題",
        pinyin: "wèntí",
        zh: "这个问题很重要。",
        zh_traditional: "這個問題很重要。",
        zh_pinyin: "zhège wèntí hěn zhòngyào.",
        ko: "이 문제는 매우 중요하다.",
        meaning_ko: "문제",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 112,
        word: "西瓜",
        word_traditional: "西瓜",
        pinyin: "xīguā",
        zh: "我喜欢吃西瓜。",
        zh_traditional: "我喜歡吃西瓜。",
        zh_pinyin: "wǒ xǐhuan chī xīguā.",
        ko: "나는 수박 먹는 것을 좋아한다.",
        meaning_ko: "수박",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 113,
        word: "希望",
        word_traditional: "希望",
        pinyin: "xīwàng",
        zh: "我希望明天晴天。",
        zh_traditional: "我希望明天晴天。",
        zh_pinyin: "wǒ xīwàng míngtiān qíngtiān.",
        ko: "나는 내일 맑은 날씨를 바란다.",
        meaning_ko: "희망하다, 바라다",
        meanings_extra: [],
        part_of_speech: "동사"
      },
      {
        no: 114,
        word: "洗",
        word_traditional: "洗",
        pinyin: "xǐ",
        zh: "我洗了衣服。",
        zh_traditional: "我洗了衣服。",
        zh_pinyin: "wǒ xǐ le yīfu.",
        ko: "나는 옷을 빨았다.",
        meaning_ko: "씻다, 빨다",
        meanings_extra: [],
        part_of_speech: "동사"
      },
      {
        no: 115,
        word: "小时",
        word_traditional: "小時",
        pinyin: "xiǎoshí",
        zh: "我学习了两个小时。",
        zh_traditional: "我學習了兩個小時。",
        zh_pinyin: "wǒ xuéxí le liǎng gè xiǎoshí.",
        ko: "나는 두 시간 공부했다.",
        meaning_ko: "시간 (단위)",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 116,
        word: "笑",
        word_traditional: "笑",
        pinyin: "xiào",
        zh: "她笑了。",
        zh_traditional: "她笑了。",
        zh_pinyin: "tā xiào le.",
        ko: "그녀가 웃었다.",
        meaning_ko: "웃다",
        meanings_extra: [],
        part_of_speech: "동사"
      },
      {
        no: 117,
        word: "新",
        word_traditional: "新",
        pinyin: "xīn",
        zh: "我买了新手机。",
        zh_traditional: "我買了新手機。",
        zh_pinyin: "wǒ mǎi le xīn shǒujī.",
        ko: "나는 새 휴대폰을 샀다.",
        meaning_ko: "새롭다",
        meanings_extra: [],
        part_of_speech: "형용사"
      },
      {
        no: 118,
        word: "姓",
        word_traditional: "姓",
        pinyin: "xìng",
        zh: "我姓李。",
        zh_traditional: "我姓李。",
        zh_pinyin: "wǒ xìng Lǐ.",
        ko: "내 성은 리다.",
        meaning_ko: "성씨가 ~이다",
        meanings_extra: [],
        part_of_speech: "동사"
      },
      {
        no: 119,
        word: "休息",
        word_traditional: "休息",
        pinyin: "xiūxi",
        zh: "我们休息一下。",
        zh_traditional: "我們休息一下。",
        zh_pinyin: "wǒmen xiūxi yíxià.",
        ko: "우리 잠시 쉬자.",
        meaning_ko: "휴식하다, 쉬다",
        meanings_extra: [],
        part_of_speech: "동사"
      },
      {
        no: 120,
        word: "雪",
        word_traditional: "雪",
        pinyin: "xuě",
        zh: "下雪了。",
        zh_traditional: "下雪了。",
        zh_pinyin: "xià xuě le.",
        ko: "눈이 내렸다.",
        meaning_ko: "눈 (snow)",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 121,
        word: "颜色",
        word_traditional: "顏色",
        pinyin: "yánsè",
        zh: "这是什么颜色？",
        zh_traditional: "這是什麼顏色？",
        zh_pinyin: "zhè shì shénme yánsè?",
        ko: "이것은 무슨 색이에요?",
        meaning_ko: "색, 색깔",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 122,
        word: "眼睛",
        word_traditional: "眼睛",
        pinyin: "yǎnjing",
        zh: "他的眼睛很大。",
        zh_traditional: "他的眼睛很大。",
        zh_pinyin: "tā de yǎnjing hěn dà.",
        ko: "그의 눈이 크다.",
        meaning_ko: "눈",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 123,
        word: "羊肉",
        word_traditional: "羊肉",
        pinyin: "yángròu",
        zh: "我喜欢吃羊肉。",
        zh_traditional: "我喜歡吃羊肉。",
        zh_pinyin: "wǒ xǐhuan chī yángròu.",
        ko: "나는 양고기 먹는 것을 좋아한다.",
        meaning_ko: "양고기",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 124,
        word: "药",
        word_traditional: "藥",
        pinyin: "yào",
        zh: "我去买药。",
        zh_traditional: "我去買藥。",
        zh_pinyin: "wǒ qù mǎi yào.",
        ko: "나는 약을 사러 간다.",
        meaning_ko: "약",
        meanings_extra: ["약물"],
        part_of_speech: "명사"
      },
      {
        no: 125,
        word: "要",
        word_traditional: "要",
        pinyin: "yào",
        zh: "我要喝水。",
        zh_traditional: "我要喝水。",
        zh_pinyin: "wǒ yào hē shuǐ.",
        ko: "나는 물을 마시고 싶다.",
        meaning_ko: "~할 것이다, 원하다",
        meanings_extra: [],
        part_of_speech: "동사"
      },
      {
        no: 126,
        word: "也",
        word_traditional: "也",
        pinyin: "yě",
        zh: "我也是学生。",
        zh_traditional: "我也是學生。",
        zh_pinyin: "wǒ yě shì xuésheng.",
        ko: "나도 학생이다.",
        meaning_ko: "~도, 역시",
        meanings_extra: [],
        part_of_speech: "부사"
      },
      {
        no: 127,
        word: "一起",
        word_traditional: "一起",
        pinyin: "yìqǐ",
        zh: "我们一起去学校。",
        zh_traditional: "我們一起去學校。",
        zh_pinyin: "wǒmen yìqǐ qù xuéxiào.",
        ko: "우리는 함께 학교에 간다.",
        meaning_ko: "같이",
        meanings_extra: [],
        part_of_speech: "부사"
      },
      {
        no: 128,
        word: "一下",
        word_traditional: "一下",
        pinyin: "yíxià",
        zh: "请等一下。",
        zh_traditional: "請等一下。",
        zh_pinyin: "qǐng děng yíxià.",
        ko: "잠깐 기다려 주세요.",
        meaning_ko: "한 번 ~해보다",
        meanings_extra: [],
        part_of_speech: "부사"
      },
      {
        no: 129,
        word: "已经",
        word_traditional: "已經",
        pinyin: "yǐjīng",
        zh: "我已经吃了。",
        zh_traditional: "我已經吃了。",
        zh_pinyin: "wǒ yǐjīng chī le.",
        ko: "나는 이미 먹었다.",
        meaning_ko: "이미, 벌써",
        meanings_extra: [],
        part_of_speech: "부사"
      },
      {
        no: 130,
        word: "意思",
        word_traditional: "意思",
        pinyin: "yìsi",
        zh: "这句话什么意思？",
        zh_traditional: "這句話什麼意思？",
        zh_pinyin: "zhè jù huà shénme yìsi?",
        ko: "이 문장의 뜻이 무엇인가요?",
        meaning_ko: "의미, 뜻",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 131,
        word: "因为...所以...",
        word_traditional: "因為...所以...",
        pinyin: "yīnwèi...suǒyǐ...",
        zh: "因为下雨，所以我们没去。",
        zh_traditional: "因為下雨，所以我們沒去。",
        zh_pinyin: "yīnwèi xiàyǔ, suǒyǐ wǒmen méi qù.",
        ko: "비가 와서 우리는 가지 않았다.",
        meaning_ko: "~하기 때문에 ~하다",
        meanings_extra: [],
        part_of_speech: "접속사"
      },
      {
        no: 132,
        word: "阴",
        word_traditional: "陰",
        pinyin: "yīn",
        zh: "今天阴天。",
        zh_traditional: "今天陰天。",
        zh_pinyin: "jīntiān yīn tiān.",
        ko: "오늘은 흐린 날이다.",
        meaning_ko: "흐리다",
        meanings_extra: [],
        part_of_speech: "형용사"
      },
      {
        no: 133,
        word: "游泳",
        word_traditional: "游泳",
        pinyin: "yóuyǒng",
        zh: "我喜欢游泳。",
        zh_traditional: "我喜歡游泳。",
        zh_pinyin: "wǒ xǐhuan yóuyǒng.",
        ko: "나는 수영하는 것을 좋아한다.",
        meaning_ko: "수영하다",
        meanings_extra: [],
        part_of_speech: "동사"
      },
      {
        no: 134,
        word: "右边",
        word_traditional: "右邊",
        pinyin: "yòubiān",
        zh: "厕所右边是教室。",
        zh_traditional: "廁所右邊是教室。",
        zh_pinyin: "cèsuǒ yòubiān shì jiàoshì.",
        ko: "화장실 오른쪽에 교실이 있다.",
        meaning_ko: "오른쪽",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 135,
        word: "鱼",
        word_traditional: "魚",
        pinyin: "yú",
        zh: "我喜欢吃鱼。",
        zh_traditional: "我喜歡吃魚。",
        zh_pinyin: "wǒ xǐhuan chī yú.",
        ko: "나는 생선을 먹는 것을 좋아한다.",
        meaning_ko: "물고기",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 136,
        word: "远",
        word_traditional: "遠",
        pinyin: "yuǎn",
        zh: "学校很远。",
        zh_traditional: "學校很遠。",
        zh_pinyin: "xuéxiào hěn yuǎn.",
        ko: "학교가 매우 멀다.",
        meaning_ko: "멀다",
        meanings_extra: [],
        part_of_speech: "형용사"
      },
      {
        no: 137,
        word: "运动",
        word_traditional: "運動",
        pinyin: "yùndòng",
        zh: "他喜欢运动。",
        zh_traditional: "他喜歡運動。",
        zh_pinyin: "tā xǐhuan yùndòng.",
        ko: "그는 운동하는 것을 좋아한다.",
        meaning_ko: "운동하다",
        meanings_extra: [],
        part_of_speech: "동사"
      },
      {
        no: 138,
        word: "再",
        word_traditional: "再",
        pinyin: "zài",
        zh: "请再说一遍。",
        zh_traditional: "請再說一遍。",
        zh_pinyin: "qǐng zài shuō yí biàn.",
        ko: "다시 한 번 말해 주세요.",
        meaning_ko: "다시",
        meanings_extra: [],
        part_of_speech: "부사"
      },
      {
        no: 139,
        word: "早上",
        word_traditional: "早上",
        pinyin: "zǎoshang",
        zh: "我早上七点起床。",
        zh_traditional: "我早上七點起床。",
        zh_pinyin: "wǒ zǎoshang qī diǎn qǐchuáng.",
        ko: "나는 아침 7시에 일어난다.",
        meaning_ko: "아침",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 140,
        word: "丈夫",
        word_traditional: "丈夫",
        pinyin: "zhàngfu",
        zh: "他是我的丈夫。",
        zh_traditional: "他是我的丈夫。",
        zh_pinyin: "tā shì wǒ de zhàngfu.",
        ko: "그는 나의 남편이다.",
        meaning_ko: "남편",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 141,
        word: "找",
        word_traditional: "找",
        pinyin: "zhǎo",
        zh: "我在找我的手机。",
        zh_traditional: "我在找我的手機。",
        zh_pinyin: "wǒ zài zhǎo wǒ de shǒujī.",
        ko: "나는 내 휴대폰을 찾고 있다.",
        meaning_ko: "찾다, 구하다",
        meanings_extra: [],
        part_of_speech: "동사"
      },
      {
        no: 142,
        word: "着",
        word_traditional: "著",
        pinyin: "zhe",
        zh: "他穿着红衣服。",
        zh_traditional: "他穿著紅衣服。",
        zh_pinyin: "tā chuān zhe hóng yīfu.",
        ko: "그는 빨간 옷을 입고 있다.",
        meaning_ko: "동작의 진행을 나타냄",
        meanings_extra: ["~하고 있다"],
        part_of_speech: "조사"
      },
      {
        no: 143,
        word: "真",
        word_traditional: "真",
        pinyin: "zhēn",
        zh: "这本书真好。",
        zh_traditional: "這本書真好。",
        zh_pinyin: "zhè běn shū zhēn hǎo.",
        ko: "이 책은 정말 좋다.",
        meaning_ko: "진실로, 참으로",
        meanings_extra: ["정말"],
        part_of_speech: "부사"
      },
      {
        no: 144,
        word: "正在",
        word_traditional: "正在",
        pinyin: "zhèngzài",
        zh: "我正在学习中文。",
        zh_traditional: "我正在學習中文。",
        zh_pinyin: "wǒ zhèngzài xuéxí Zhōngwén.",
        ko: "나는 중국어를 공부하고 있다.",
        meaning_ko: "지금 ~하고 있는 중이다",
        meanings_extra: [],
        part_of_speech: "부사"
      },
      {
        no: 145,
        word: "只",
        word_traditional: "只",
        pinyin: "zhī",
        zh: "我有一只狗。",
        zh_traditional: "我有一隻狗。",
        zh_pinyin: "wǒ yǒu yī zhī gǒu.",
        ko: "나는 개 한 마리가 있다.",
        meaning_ko: "마리, 쪽, 짝 (동물이나 쌍을 세는 단위)",
        meanings_extra: [],
        part_of_speech: "양사"
      },
      {
        no: 146,
        word: "知道",
        word_traditional: "知道",
        pinyin: "zhīdào",
        zh: "我知道答案。",
        zh_traditional: "我知道答案。",
        zh_pinyin: "wǒ zhīdào dá'àn.",
        ko: "나는 답을 알고 있다.",
        meaning_ko: "알다, 이해하다",
        meanings_extra: [],
        part_of_speech: "동사"
      },
      {
        no: 147,
        word: "准备",
        word_traditional: "準備",
        pinyin: "zhǔnbèi",
        zh: "我准备好了。",
        zh_traditional: "我準備好了。",
        zh_pinyin: "wǒ zhǔnbèi hǎo le.",
        ko: "나는 준비가 됐다.",
        meaning_ko: "준비하다",
        meanings_extra: [],
        part_of_speech: "동사"
      },
      {
        no: 148,
        word: "走",
        word_traditional: "走",
        pinyin: "zǒu",
        zh: "我们走吧！",
        zh_traditional: "我們走吧！",
        zh_pinyin: "wǒmen zǒu ba!",
        ko: "우리 가자!",
        meaning_ko: "걷다, 가다",
        meanings_extra: ["떠나다"],
        part_of_speech: "동사"
      },
      {
        no: 149,
        word: "最",
        word_traditional: "最",
        pinyin: "zuì",
        zh: "他是最好的学生。",
        zh_traditional: "他是最好的學生。",
        zh_pinyin: "tā shì zuì hǎo de xuésheng.",
        ko: "그는 최고의 학생이다.",
        meaning_ko: "가장, 제일",
        meanings_extra: [],
        part_of_speech: "부사"
      },
      {
        no: 150,
        word: "左边",
        word_traditional: "左邊",
        pinyin: "zuǒbiān",
        zh: "银行在左边。",
        zh_traditional: "銀行在左邊。",
        zh_pinyin: "yínháng zài zuǒbiān.",
        ko: "은행은 왼쪽에 있다.",
        meaning_ko: "왼쪽",
        meanings_extra: [],
        part_of_speech: "명사"
      }
  ]
  