const quizList = [
  {
    no: 1,
    word: "我",
    word_traditional: "我",
    pinyin: "wǒ",
    zh: "我是学生。",
    zh_traditional: "我是學生。",
    zh_pinyin: "wǒ shì xuésheng.",
    ko: "나는 학생이다.",
    meaning_ko: "나, 저",
    meanings_extra: ["자신"],
    part_of_speech: "대명사"
  },
  {
    no: 2,
    word: "我们",
    word_traditional: "我們",
    pinyin: "wǒmen",
    zh: "我们去学校。",
    zh_traditional: "我們去學校。",
    zh_pinyin: "wǒmen qù xuéxiào.",
    ko: "우리 학교에 간다.",
    meaning_ko: "우리",
    meanings_extra: [],
    part_of_speech: "대명사"
  },
  {
    no: 3,
    word: "你",
    word_traditional: "你",
    pinyin: "nǐ",
    zh: "你好吗？",
    zh_traditional: "你好嗎？",
    zh_pinyin: "nǐ hǎo ma?",
    ko: "너는 잘 지내니?",
    meaning_ko: "너, 당신",
    meanings_extra: [],
    part_of_speech: "대명사"
  },
  {
    no: 4,
    word: "他",
    word_traditional: "他",
    pinyin: "tā",
    zh: "他是老师。",
    zh_traditional: "他是老師。",
    zh_pinyin: "tā shì lǎoshī.",
    ko: "그는 선생님이다.",
    meaning_ko: "그 (남자)",
    meanings_extra: [],
    part_of_speech: "대명사"
  },
  {
    no: 5,
    word: "她",
    word_traditional: "她",
    pinyin: "tā",
    zh: "她是学生。",
    zh_traditional: "她是學生。",
    zh_pinyin: "tā shì xuésheng.",
    ko: "그녀는 학생이다.",
    meaning_ko: "그녀",
    meanings_extra: [],
    part_of_speech: "대명사"
  },
  {
    no: 6,
    word: "这(这儿)",
    word_traditional: "這",
    pinyin: "zhè(r)",
    zh: "这是我的书。",
    zh_traditional: "這是我的書。",
    zh_pinyin: "zhè shì wǒ de shū.",
    ko: "이것은 내 책이다.",
    meaning_ko: "이것",
    meanings_extra: [],
    part_of_speech: "지시대명사"
  },
  {
    no: 7,
    word: "那(那儿)",
    word_traditional: "那",
    pinyin: "nà(r)",
    zh: "那是你的家。",
    zh_traditional: "那是你的家。",
    zh_pinyin: "nà shì nǐ de jiā.",
    ko: "저것은 너희 집이다.",
    meaning_ko: "저것",
    meanings_extra: [],
    part_of_speech: "지시대명사"
  },
  {
    no: 8,
    word: "哪",
    word_traditional: "哪",
    pinyin: "nǎ",
    zh: "你喜欢哪个颜色？",
    zh_traditional: "你喜歡哪個顏色？",
    zh_pinyin: "nǐ xǐhuan nǎ ge yánsè?",
    ko: "너는 어떤 색깔을 좋아하니?",
    meaning_ko: "어느, 어디",
    meanings_extra: [],
    part_of_speech: "의문대명사"
  },
  {
    no: 9,
    word: "哪儿",
    word_traditional: "哪兒",
    pinyin: "nǎr",
    zh: "你去哪儿？",
    zh_traditional: "你去哪兒？",
    zh_pinyin: "nǐ qù nǎr?",
    ko: "너 어디 가니?",
    meaning_ko: "어디",
    meanings_extra: ["어느 곳"],
    part_of_speech: "의문대명사"
  },
  {
    no: 10,
    word: "谁",
    word_traditional: "誰",
    pinyin: "shéi",
    zh: "他是谁？",
    zh_traditional: "他是誰？",
    zh_pinyin: "tā shì shéi?",
    ko: "그는 누구니?",
    meaning_ko: "누구",
    meanings_extra: [],
    part_of_speech: "의문대명사"
  },
  {
    no: 11,
    word: "什么",
    word_traditional: "什麼",
    pinyin: "shénme",
    zh: "这是什么？",
    zh_traditional: "這是什麼？",
    zh_pinyin: "zhè shì shénme?",
    ko: "이것은 무엇인가?",
    meaning_ko: "무엇",
    meanings_extra: ["어떤"],
    part_of_speech: "의문대명사"
  },
  {
    no: 12,
    word: "多少",
    word_traditional: "多少",
    pinyin: "duōshao",
    zh: "多少钱？",
    zh_traditional: "多少錢？",
    zh_pinyin: "duōshao qián?",
    ko: "얼마입니까?",
    meaning_ko: "얼마, 몇",
    meanings_extra: [],
    part_of_speech: "의문대명사"
  },
  {
    no: 13,
    word: "几",
    word_traditional: "幾",
    pinyin: "jǐ",
    zh: "你有几个苹果？",
    zh_traditional: "你有幾個蘋果？",
    zh_pinyin: "nǐ yǒu jǐ gè píngguǒ?",
    ko: "너는 사과 몇 개 있니?",
    meaning_ko: "몇",
    meanings_extra: ["얼마"],
    part_of_speech: "의문대명사"
  },
  {
    no: 14,
    word: "怎么",
    word_traditional: "怎麼",
    pinyin: "zěnme",
    zh: "你怎么去学校？",
    zh_traditional: "你怎麼去學校？",
    zh_pinyin: "nǐ zěnme qù xuéxiào?",
    ko: "너는 어떻게 학교에 가니?",
    meaning_ko: "어떻게",
    meanings_extra: [],
    part_of_speech: "의문대명사"
  },
  {
    no: 15,
    word: "怎么样",
    word_traditional: "怎麼樣",
    pinyin: "zěnmeyàng",
    zh: "天气怎么样？",
    zh_traditional: "天氣怎麼樣？",
    zh_pinyin: "tiānqì zěnmeyàng?",
    ko: "날씨는 어떠니?",
    meaning_ko: "어떠하다",
    meanings_extra: [],
    part_of_speech: "의문대명사"
  },
  {
    no: 16,
    word: "一",
    word_traditional: "一",
    pinyin: "yī",
    zh: "我有一个朋友。",
    zh_traditional: "我有一個朋友。",
    zh_pinyin: "wǒ yǒu yī gè péngyou.",
    ko: "나는 친구 한 명이 있다.",
    meaning_ko: "하나",
    meanings_extra: ["일"],
    part_of_speech: "수사"
  },
  {
    no: 17,
    word: "二",
    word_traditional: "二",
    pinyin: "èr",
    zh: "今天是二月。",
    zh_traditional: "今天是二月。",
    zh_pinyin: "jīntiān shì èr yuè.",
    ko: "오늘은 2월이다.",
    meaning_ko: "둘",
    meanings_extra: ["이"],
    part_of_speech: "수사"
  },
  {
    no: 18,
    word: "三",
    word_traditional: "三",
    pinyin: "sān",
    zh: "我有三支笔。",
    zh_traditional: "我有三支筆。",
    zh_pinyin: "wǒ yǒu sān zhī bǐ.",
    ko: "나는 펜 세 자루가 있다.",
    meaning_ko: "셋",
    meanings_extra: [],
    part_of_speech: "수사"
  },
  {
    no: 19,
    word: "四",
    word_traditional: "四",
    pinyin: "sì",
    zh: "今天是四月。",
    zh_traditional: "今天是四月。",
    zh_pinyin: "jīntiān shì sì yuè.",
    ko: "오늘은 4월이다.",
    meaning_ko: "넷",
    meanings_extra: [],
    part_of_speech: "수사"
  },
  {
    no: 20,
    word: "五",
    word_traditional: "五",
    pinyin: "wǔ",
    zh: "我有五个苹果。",
    zh_traditional: "我有五個蘋果。",
    zh_pinyin: "wǒ yǒu wǔ gè píngguǒ.",
    ko: "나는 사과 다섯 개가 있다.",
    meaning_ko: "다섯",
    meanings_extra: [],
    part_of_speech: "수사"
  },
  {
    no: 21,
    word: "六",
    word_traditional: "六",
    pinyin: "liù",
    zh: "我六点起床。",
    zh_traditional: "我六點起床。",
    zh_pinyin: "wǒ liù diǎn qǐchuáng.",
    ko: "나는 6시에 일어난다.",
    meaning_ko: "여섯",
    meanings_extra: [],
    part_of_speech: "수사"
  },
  {
    no: 22,
    word: "七",
    word_traditional: "七",
    pinyin: "qī",
    zh: "今天是七号。",
    zh_traditional: "今天是七號。",
    zh_pinyin: "jīntiān shì qī hào.",
    ko: "오늘은 7일이다.",
    meaning_ko: "일곱",
    meanings_extra: [],
    part_of_speech: "수사"
  },
  {
    no: 23,
    word: "八",
    word_traditional: "八",
    pinyin: "bā",
    zh: "他有八本书。",
    zh_traditional: "他有八本書。",
    zh_pinyin: "tā yǒu bā běn shū.",
    ko: "그는 책 여덟 권이 있다.",
    meaning_ko: "여덟",
    meanings_extra: [],
    part_of_speech: "수사"
  },
  {
    no: 24,
    word: "九",
    word_traditional: "九",
    pinyin: "jiǔ",
    zh: "我们九点见面。",
    zh_traditional: "我們九點見面。",
    zh_pinyin: "wǒmen jiǔ diǎn jiànmiàn.",
    ko: "우리는 9시에 만난다.",
    meaning_ko: "아홉",
    meanings_extra: [],
    part_of_speech: "수사"
  },
  {
    no: 25,
    word: "十",
    word_traditional: "十",
    pinyin: "shí",
    zh: "他有十支笔。",
    zh_traditional: "他有十支筆。",
    zh_pinyin: "tā yǒu shí zhī bǐ.",
    ko: "그는 펜 열 자루가 있다.",
    meaning_ko: "열",
    meanings_extra: [],
    part_of_speech: "수사"
  },
  {
    no: 26,
    word: "个",
    word_traditional: "個",
    pinyin: "gè",
    zh: "我有一个苹果。",
    zh_traditional: "我有一個蘋果。",
    zh_pinyin: "wǒ yǒu yí gè píngguǒ.",
    ko: "나는 사과 하나가 있다.",
    meaning_ko: "개, 명 (사람이나 사물의 양사)",
    meanings_extra: ["사람", "것"],
    part_of_speech: "양사"
  },
  {
    no: 27,
    word: "岁",
    word_traditional: "歲",
    pinyin: "suì",
    zh: "他今年二十岁。",
    zh_traditional: "他今年二十歲。",
    zh_pinyin: "tā jīnnián èrshí suì.",
    ko: "그는 올해 20살이다.",
    meaning_ko: "살 (나이 단위)",
    meanings_extra: [],
    part_of_speech: "양사"
  },
  {
    no: 28,
    word: "本",
    word_traditional: "本",
    pinyin: "běn",
    zh: "我有三本书。",
    zh_traditional: "我有三本書。",
    zh_pinyin: "wǒ yǒu sān běn shū.",
    ko: "나는 책 세 권이 있다.",
    meaning_ko: "권 (책 단위)",
    meanings_extra: [],
    part_of_speech: "양사"
  },
  {
    no: 29,
    word: "些",
    word_traditional: "些",
    pinyin: "xiē",
    zh: "我买了一些水果。",
    zh_traditional: "我買了一些水果。",
    zh_pinyin: "wǒ mǎi le yìxiē shuǐguǒ.",
    ko: "나는 과일을 조금 샀다.",
    meaning_ko: "몇, 약간",
    meanings_extra: ["조금"],
    part_of_speech: "양사"
  },
  {
    no: 30,
    word: "块",
    word_traditional: "塊",
    pinyin: "kuài",
    zh: "我吃了一块蛋糕。",
    zh_traditional: "我吃了一塊蛋糕。",
    zh_pinyin: "wǒ chī le yí kuài dàngāo.",
    ko: "나는 케이크 한 조각을 먹었다.",
    meaning_ko: "덩어리, 조각",
    meanings_extra: ["조각"],
    part_of_speech: "양사"
  },
  {
    no: 31,
    word: "不",
    word_traditional: "不",
    pinyin: "bù",
    zh: "我不喜欢喝茶。",
    zh_traditional: "我不喜歡喝茶。",
    zh_pinyin: "wǒ bù xǐhuan hē chá.",
    ko: "나는 차 마시는 것을 좋아하지 않는다.",
    meaning_ko: "아니다, ~하지 않다",
    meanings_extra: ["부정"],
    part_of_speech: "부사"
  },
  {
    no: 32,
    word: "没",
    word_traditional: "沒",
    pinyin: "méi",
    zh: "我没吃饭。",
    zh_traditional: "我沒吃飯。",
    zh_pinyin: "wǒ méi chī fàn.",
    ko: "나는 밥을 먹지 않았다.",
    meaning_ko: "~하지 않았다",
    meanings_extra: ["부정"],
    part_of_speech: "부사"
  },
  {
    no: 33,
    word: "很",
    word_traditional: "很",
    pinyin: "hěn",
    zh: "她很漂亮。",
    zh_traditional: "她很漂亮。",
    zh_pinyin: "tā hěn piàoliang.",
    ko: "그녀는 매우 예쁘다.",
    meaning_ko: "매우, 아주",
    meanings_extra: ["꽤"],
    part_of_speech: "부사"
  },
  {
    no: 34,
    word: "太",
    word_traditional: "太",
    pinyin: "tài",
    zh: "天气太热了。",
    zh_traditional: "天氣太熱了。",
    zh_pinyin: "tiānqì tài rè le.",
    ko: "날씨가 너무 덥다.",
    meaning_ko: "너무",
    meanings_extra: ["지나치게"],
    part_of_speech: "부사"
  },
  {
    no: 35,
    word: "都",
    word_traditional: "都",
    pinyin: "dōu",
    zh: "我们都去学校。",
    zh_traditional: "我們都去學校。",
    zh_pinyin: "wǒmen dōu qù xuéxiào.",
    ko: "우리 모두 학교에 간다.",
    meaning_ko: "모두",
    meanings_extra: ["전부"],
    part_of_speech: "부사"
  },
  {
    no: 36,
    word: "一点儿",
    word_traditional: "一點兒",
    pinyin: "yìdiǎnr",
    zh: "我想喝一点儿水。",
    zh_traditional: "我想喝一點兒水。",
    zh_pinyin: "wǒ xiǎng hē yìdiǎnr shuǐ.",
    ko: "나는 물을 조금 마시고 싶다.",
    meaning_ko: "조금",
    meanings_extra: ["약간"],
    part_of_speech: "부사"
  },
  {
    no: 37,
    word: "和",
    word_traditional: "和",
    pinyin: "hé",
    zh: "我和你一起去。",
    zh_traditional: "我和你一起去。",
    zh_pinyin: "wǒ hé nǐ yìqǐ qù.",
    ko: "나와 너는 함께 간다.",
    meaning_ko: "그리고, ~와/과",
    meanings_extra: ["함께"],
    part_of_speech: "접속사"
  },
  {
    no: 38,
    word: "在",
    word_traditional: "在",
    pinyin: "zài",
    zh: "我在家。",
    zh_traditional: "我在家。",
    zh_pinyin: "wǒ zài jiā.",
    ko: "나는 집에 있다.",
    meaning_ko: "~에 있다, ~에서",
    meanings_extra: ["장소 전치사"],
    part_of_speech: "전치사"
  },
  {
    no: 39,
    word: "的",
    word_traditional: "的",
    pinyin: "de",
    zh: "我的书。",
    zh_traditional: "我的書。",
    zh_pinyin: "wǒ de shū.",
    ko: "나의 책.",
    meaning_ko: "~의 (소유격)",
    meanings_extra: ["관계대명사"],
    part_of_speech: "조사"
  },
  {
    no: 40,
    word: "了",
    word_traditional: "了",
    pinyin: "le",
    zh: "我吃了饭。",
    zh_traditional: "我吃了飯。",
    zh_pinyin: "wǒ chī le fàn.",
    ko: "나는 밥을 먹었다.",
    meaning_ko: "완료를 나타내는 조동사",
    meanings_extra: ["변화 표현"],
    part_of_speech: "조사"
  },
  {
    no: 41,
    word: "吗",
    word_traditional: "嗎",
    pinyin: "ma",
    zh: "你好吗？",
    zh_traditional: "你好嗎？",
    zh_pinyin: "nǐ hǎo ma?",
    ko: "너는 잘 지내니?",
    meaning_ko: "의문문을 만드는 조동사",
    meanings_extra: [],
    part_of_speech: "조사"
  },
  {
    no: 42,
    word: "呢",
    word_traditional: "呢",
    pinyin: "ne",
    zh: "你呢？",
    zh_traditional: "你呢？",
    zh_pinyin: "nǐ ne?",
    ko: "너는?",
    meaning_ko: "의문을 부드럽게 만드는 조동사",
    meanings_extra: [],
    part_of_speech: "조사"
  },
  {
    no: 43,
    word: "喂",
    word_traditional: "喂",
    pinyin: "wèi",
    zh: "喂，你好！",
    zh_traditional: "喂，你好！",
    zh_pinyin: "wèi, nǐ hǎo!",
    ko: "여보세요, 안녕하세요!",
    meaning_ko: "여보세요 (전화할 때)",
    meanings_extra: [],
    part_of_speech: "감탄사"
  },
  {
    no: 44,
    word: "家",
    word_traditional: "家",
    pinyin: "jiā",
    zh: "我回家了。",
    zh_traditional: "我回家了。",
    zh_pinyin: "wǒ huí jiā le.",
    ko: "나는 집에 돌아왔다.",
    meaning_ko: "집",
    meanings_extra: ["가족"],
    part_of_speech: "명사"
  },
  {
    no: 45,
    word: "学校",
    word_traditional: "學校",
    pinyin: "xuéxiào",
    zh: "学校很大。",
    zh_traditional: "學校很大。",
    zh_pinyin: "xuéxiào hěn dà.",
    ko: "학교가 매우 크다.",
    meaning_ko: "학교",
    meanings_extra: [],
    part_of_speech: "명사"
  },
  {
    no: 46,
    word: "饭店",
    word_traditional: "飯店",
    pinyin: "fàndiàn",
    zh: "我们去饭店吃饭。",
    zh_traditional: "我們去飯店吃飯。",
    zh_pinyin: "wǒmen qù fàndiàn chīfàn.",
    ko: "우리는 식당에 밥 먹으러 간다.",
    meaning_ko: "식당, 호텔",
    meanings_extra: [],
    part_of_speech: "명사"
  },
  {
    no: 47,
    word: "商店",
    word_traditional: "商店",
    pinyin: "shāngdiàn",
    zh: "我去商店买东西。",
    zh_traditional: "我去商店買東西。",
    zh_pinyin: "wǒ qù shāngdiàn mǎi dōngxī.",
    ko: "나는 가게에 물건을 사러 간다.",
    meaning_ko: "가게",
    meanings_extra: ["상점"],
    part_of_speech: "명사"
  },
  {
    no: 48,
    word: "医院",
    word_traditional: "醫院",
    pinyin: "yīyuàn",
    zh: "他去医院看病。",
    zh_traditional: "他去醫院看病。",
    zh_pinyin: "tā qù yīyuàn kànbìng.",
    ko: "그는 병원에 진료 받으러 간다.",
    meaning_ko: "병원",
    meanings_extra: [],
    part_of_speech: "명사"
  },
  {
    no: 49,
    word: "中国",
    word_traditional: "中國",
    pinyin: "Zhōngguó",
    zh: "中国是一个大国。",
    zh_traditional: "中國是一個大國。",
    zh_pinyin: "Zhōngguó shì yí gè dà guó.",
    ko: "중국은 큰 나라이다.",
    meaning_ko: "중국",
    meanings_extra: [],
    part_of_speech: "명사"
  },
  {
    no: 50,
    word: "北京",
    word_traditional: "北京",
    pinyin: "Běijīng",
    zh: "北京是中国的首都。",
    zh_traditional: "北京是中國的首都。",
    zh_pinyin: "Běijīng shì Zhōngguó de shǒudū.",
    ko: "베이징은 중국의 수도이다.",
    meaning_ko: "베이징",
    meanings_extra: [],
    part_of_speech: "명사"
  },
  {
    no: 51,
    word: "上",
    word_traditional: "上",
    pinyin: "shàng",
    zh: "我上楼去了。",
    zh_traditional: "我上樓去了。",
    zh_pinyin: "wǒ shàng lóu qù le.",
    ko: "나는 위층으로 올라갔다.",
    meaning_ko: "위, 올라가다",
    meanings_extra: ["올라가다", "출석하다"],
    part_of_speech: "동사/방향사"
  },
  {
    no: 52,
    word: "下",
    word_traditional: "下",
    pinyin: "xià",
    zh: "他下楼了。",
    zh_traditional: "他下樓了。",
    zh_pinyin: "tā xià lóu le.",
    ko: "그는 아래층으로 내려갔다.",
    meaning_ko: "아래, 내려가다",
    meanings_extra: ["떨어지다"],
    part_of_speech: "동사/방향사"
  },
  {
    no: 53,
    word: "前面",
    word_traditional: "前面",
    pinyin: "qiánmiàn",
    zh: "商店在前面。",
    zh_traditional: "商店在前面。",
    zh_pinyin: "shāngdiàn zài qiánmiàn.",
    ko: "가게는 앞에 있다.",
    meaning_ko: "앞, 앞쪽",
    meanings_extra: ["전에"],
    part_of_speech: "명사/방향사"
  },
  {
    no: 54,
    word: "后面",
    word_traditional: "後面",
    pinyin: "hòumiàn",
    zh: "学校在我家后面。",
    zh_traditional: "學校在我家後面。",
    zh_pinyin: "xuéxiào zài wǒ jiā hòumiàn.",
    ko: "학교는 우리 집 뒤에 있다.",
    meaning_ko: "뒤, 뒤쪽",
    meanings_extra: ["뒤편"],
    part_of_speech: "명사"
  },
  {
    no: 55,
    word: "里",
    word_traditional: "裡",
    pinyin: "lǐmiàn",
    zh: "书包里有书。",
    zh_traditional: "書包裡有書。",
    zh_pinyin: "shūbāo lǐmiàn yǒu shū.",
    ko: "책가방 안에 책이 있다.",
    meaning_ko: "안, 속",
    meanings_extra: ["내부"],
    part_of_speech: "명사"
  },
  {
    no: 56,
    word: "今天",
    word_traditional: "今天",
    pinyin: "jīntiān",
    zh: "今天天气很好。",
    zh_traditional: "今天天氣很好。",
    zh_pinyin: "jīntiān tiānqì hěn hǎo.",
    ko: "오늘 날씨가 매우 좋다.",
    meaning_ko: "오늘",
    meanings_extra: [],
    part_of_speech: "명사"
  },
  {
    no: 57,
    word: "明天",
    word_traditional: "明天",
    pinyin: "míngtiān",
    zh: "明天我去学校。",
    zh_traditional: "明天我去學校。",
    zh_pinyin: "míngtiān wǒ qù xuéxiào.",
    ko: "나는 내일 학교에 간다.",
    meaning_ko: "내일",
    meanings_extra: [],
    part_of_speech: "명사"
  },
  {
    no: 58,
    word: "昨天",
    word_traditional: "昨天",
    pinyin: "zuótiān",
    zh: "昨天我很忙。",
    zh_traditional: "昨天我很忙。",
    zh_pinyin: "zuótiān wǒ hěn máng.",
    ko: "나는 어제 매우 바빴다.",
    meaning_ko: "어제",
    meanings_extra: [],
    part_of_speech: "명사"
  },
  {
    no: 59,
    word: "上午",
    word_traditional: "上午",
    pinyin: "shàngwǔ",
    zh: "我上午去图书馆。",
    zh_traditional: "我上午去圖書館。",
    zh_pinyin: "wǒ shàngwǔ qù túshūguǎn.",
    ko: "나는 오전에 도서관에 간다.",
    meaning_ko: "오전",
    meanings_extra: [],
    part_of_speech: "명사"
  },
  {
    no: 60,
    word: "中午",
    word_traditional: "中午",
    pinyin: "zhōngwǔ",
    zh: "中午我们吃饭。",
    zh_traditional: "中午我們吃飯。",
    zh_pinyin: "zhōngwǔ wǒmen chī fàn.",
    ko: "우리는 정오에 밥을 먹는다.",
    meaning_ko: "정오, 점심",
    meanings_extra: [],
    part_of_speech: "명사"
  },
  {
    no: 61,
    word: "下午",
    word_traditional: "下午",
    pinyin: "xiàwǔ",
    zh: "下午我去运动。",
    zh_traditional: "下午我去運動。",
    zh_pinyin: "xiàwǔ wǒ qù yùndòng.",
    ko: "나는 오후에 운동하러 간다.",
    meaning_ko: "오후",
    meanings_extra: [],
    part_of_speech: "명사"
  },
  {
    no: 62,
    word: "年",
    word_traditional: "年",
    pinyin: "nián",
    zh: "今年是2025年。",
    zh_traditional: "今年是2025年。",
    zh_pinyin: "jīnnián shì 2025 nián.",
    ko: "올해는 2025년이다.",
    meaning_ko: "년, 해",
    meanings_extra: [],
    part_of_speech: "명사"
  },
  {
    no: 63,
    word: "月",
    word_traditional: "月",
    pinyin: "yuè",
    zh: "十二月是冬天。",
    zh_traditional: "十二月是冬天。",
    zh_pinyin: "shí'èr yuè shì dōngtiān.",
    ko: "12월은 겨울이다.",
    meaning_ko: "달, 월",
    meanings_extra: [],
    part_of_speech: "명사"
  },
  {
    no: 64,
    word: "号",
    word_traditional: "號",
    pinyin: "hào",
    zh: "今天是二十号。",
    zh_traditional: "今天是二十號。",
    zh_pinyin: "jīntiān shì èrshí hào.",
    ko: "오늘은 20일이다.",
    meaning_ko: "번호, 날짜",
    meanings_extra: [],
    part_of_speech: "명사"
  },
  {
    no: 65,
    word: "星期",
    word_traditional: "星期",
    pinyin: "xīngqī",
    zh: "星期一我有课。",
    zh_traditional: "星期一我有課。",
    zh_pinyin: "xīngqī yī wǒ yǒu kè.",
    ko: "나는 월요일에 수업이 있다.",
    meaning_ko: "주, 요일",
    meanings_extra: [],
    part_of_speech: "명사"
  },
  {
    no: 66,
    word: "点",
    word_traditional: "點",
    pinyin: "diǎn",
    zh: "现在三点了。",
    zh_traditional: "現在三點了。",
    zh_pinyin: "xiànzài sān diǎn le.",
    ko: "지금은 3시이다.",
    meaning_ko: "시 (시간 단위)",
    meanings_extra: [],
    part_of_speech: "명사"
  },
  {
    no: 67,
    word: "分钟",
    word_traditional: "分鐘",
    pinyin: "fēnzhōng",
    zh: "我等了十分钟。",
    zh_traditional: "我等了十分鐘。",
    zh_pinyin: "wǒ děng le shí fēnzhōng.",
    ko: "나는 10분 동안 기다렸다.",
    meaning_ko: "분 (시간 단위)",
    meanings_extra: [],
    part_of_speech: "명사"
  },
  {
    no: 68,
    word: "现在",
    word_traditional: "現在",
    pinyin: "xiànzài",
    zh: "我现在学习中文。",
    zh_traditional: "我現在學習中文。",
    zh_pinyin: "wǒ xiànzài xuéxí Zhōngwén.",
    ko: "나는 지금 중국어를 공부한다.",
    meaning_ko: "지금",
    meanings_extra: ["현재"],
    part_of_speech: "부사"
  },
  {
    no: 69,
    word: "时候",
    word_traditional: "時候",
    pinyin: "shíhou",
    zh: "我什么时候去？",
    zh_traditional: "我什麼時候去？",
    zh_pinyin: "wǒ shénme shíhou qù?",
    ko: "나는 언제 가니?",
    meaning_ko: "때, 시간",
    meanings_extra: [],
    part_of_speech: "명사"
  },
  {
    no: 70,
    word: "爸爸",
    word_traditional: "爸爸",
    pinyin: "bàba",
    zh: "爸爸在工作。",
    zh_traditional: "爸爸在工作。",
    zh_pinyin: "bàba zài gōngzuò.",
    ko: "아빠가 일하고 있다.",
    meaning_ko: "아빠",
    meanings_extra: [],
    part_of_speech: "명사"
  },
  {
    no: 71,
    word: "妈妈",
    word_traditional: "媽媽",
    pinyin: "māma",
    zh: "妈妈做饭。",
    zh_traditional: "媽媽做飯。",
    zh_pinyin: "māma zuò fàn.",
    ko: "엄마가 밥을 한다.",
    meaning_ko: "엄마",
    meanings_extra: [],
    part_of_speech: "명사"
  },
  {
    no: 72,
    word: "儿子",
    word_traditional: "兒子",
    pinyin: "érzi",
    zh: "儿子上学去了。",
    zh_traditional: "兒子上學去了。",
    zh_pinyin: "érzi shàngxué qù le.",
    ko: "아들이 학교에 갔다.",
    meaning_ko: "아들",
    meanings_extra: [],
    part_of_speech: "명사"
  },
  {
    no: 73,
    word: "女儿",
    word_traditional: "女兒",
    pinyin: "nǚ'ér",
    zh: "女儿很可爱。",
    zh_traditional: "女兒很可愛。",
    zh_pinyin: "nǚ'ér hěn kě'ài.",
    ko: "딸은 매우 귀엽다.",
    meaning_ko: "딸",
    meanings_extra: [],
    part_of_speech: "명사"
  },
  {
    no: 74,
    word: "老师",
    word_traditional: "老師",
    pinyin: "lǎoshī",
    zh: "老师教我们。",
    zh_traditional: "老師教我們。",
    zh_pinyin: "lǎoshī jiāo wǒmen.",
    ko: "선생님이 우리를 가르친다.",
    meaning_ko: "선생님",
    meanings_extra: [],
    part_of_speech: "명사"
  },
  {
    no: 75,
    word: "学生",
    word_traditional: "學生",
    pinyin: "xuéshēng",
    zh: "学生们在教室里。",
    zh_traditional: "學生們在教室裡。",
    zh_pinyin: "xuéshēng men zài jiàoshì lǐ.",
    ko: "학생들이 교실 안에 있다.",
    meaning_ko: "학생",
    meanings_extra: [],
    part_of_speech: "명사"
  },
  {
    no: 76,
    word: "同学",
    word_traditional: "同學",
    pinyin: "tóngxué",
    zh: "他是我的同学。",
    zh_traditional: "他是我的同學。",
    zh_pinyin: "tā shì wǒ de tóngxué.",
    ko: "그는 내 급우이다.",
    meaning_ko: "급우, 학우",
    meanings_extra: ["같은 학교 학생"],
    part_of_speech: "명사"
  },
  {
    no: 77,
    word: "朋友",
    word_traditional: "朋友",
    pinyin: "péngyou",
    zh: "她是我的朋友。",
    zh_traditional: "她是我的朋友。",
    zh_pinyin: "tā shì wǒ de péngyou.",
    ko: "그녀는 내 친구이다.",
    meaning_ko: "친구",
    meanings_extra: [],
    part_of_speech: "명사"
  },
  {
    no: 78,
    word: "医生",
    word_traditional: "醫生",
    pinyin: "yīshēng",
    zh: "他是一名医生。",
    zh_traditional: "他是一名醫生。",
    zh_pinyin: "tā shì yī míng yīshēng.",
    ko: "그는 한 명의 의사이다.",
    meaning_ko: "의사",
    meanings_extra: [],
    part_of_speech: "명사"
  },
  {
    no: 79,
    word: "先生",
    word_traditional: "先生",
    pinyin: "xiānsheng",
    zh: "李先生很忙。",
    zh_traditional: "李先生很忙。",
    zh_pinyin: "Lǐ xiānsheng hěn máng.",
    ko: "리 선생님은 매우 바쁘다.",
    meaning_ko: "씨, 선생님 (남자)",
    meanings_extra: ["남자 존칭"],
    part_of_speech: "명사"
  },
  {
    no: 80,
    word: "小姐",
    word_traditional: "小姐",
    pinyin: "xiǎojiě",
    zh: "王小姐是我的朋友。",
    zh_traditional: "王小姐是我的朋友。",
    zh_pinyin: "Wáng xiǎojiě shì wǒ de péngyou.",
    ko: "왕 아가씨는 내 친구이다.",
    meaning_ko: "아가씨, 미스",
    meanings_extra: ["젊은 여성 존칭"],
    part_of_speech: "명사"
  },
  {
    no: 81,
    word: "衣服",
    word_traditional: "衣服",
    pinyin: "yīfu",
    zh: "我买了新衣服。",
    zh_traditional: "我買了新衣服。",
    zh_pinyin: "wǒ mǎi le xīn yīfu.",
    ko: "나는 새 옷을 샀다.",
    meaning_ko: "옷",
    meanings_extra: ["의복"],
    part_of_speech: "명사"
  },
  {
    no: 82,
    word: "水",
    word_traditional: "水",
    pinyin: "shuǐ",
    zh: "请给我一杯水。",
    zh_traditional: "請給我一杯水。",
    zh_pinyin: "qǐng gěi wǒ yì bēi shuǐ.",
    ko: "물 한 잔 주세요.",
    meaning_ko: "물",
    meanings_extra: [],
    part_of_speech: "명사"
  },
  {
    no: 83,
    word: "菜",
    word_traditional: "菜",
    pinyin: "cài",
    zh: "我喜欢吃中国菜。",
    zh_traditional: "我喜歡吃中國菜。",
    zh_pinyin: "wǒ xǐhuan chī Zhōngguó cài.",
    ko: "나는 중국 음식을 좋아한다.",
    meaning_ko: "요리, 음식",
    meanings_extra: ["채소"],
    part_of_speech: "명사"
  },
  {
    no: 84,
    word: "米饭",
    word_traditional: "米飯",
    pinyin: "mǐfàn",
    zh: "我每天吃米饭。",
    zh_traditional: "我每天吃米飯。",
    zh_pinyin: "wǒ měitiān chī mǐfàn.",
    ko: "나는 매일 밥을 먹는다.",
    meaning_ko: "밥",
    meanings_extra: [],
    part_of_speech: "명사"
  },
  {
    no: 85,
    word: "水果",
    word_traditional: "水果",
    pinyin: "shuǐguǒ",
    zh: "水果很甜。",
    zh_traditional: "水果很甜。",
    zh_pinyin: "shuǐguǒ hěn tián.",
    ko: "과일은 매우 달다.",
    meaning_ko: "과일",
    meanings_extra: [],
    part_of_speech: "명사"
  },
  {
    no: 86,
    word: "苹果",
    word_traditional: "蘋果",
    pinyin: "píngguǒ",
    zh: "我喜欢吃苹果。",
    zh_traditional: "我喜歡吃蘋果。",
    zh_pinyin: "wǒ xǐhuan chī píngguǒ.",
    ko: "나는 사과 먹는 것을 좋아한다.",
    meaning_ko: "사과",
    meanings_extra: [],
    part_of_speech: "명사"
  },
  {
    no: 87,
    word: "茶",
    word_traditional: "茶",
    pinyin: "chá",
    zh: "请给我一杯茶。",
    zh_traditional: "請給我一杯茶。",
    zh_pinyin: "qǐng gěi wǒ yì bēi chá.",
    ko: "차 한 잔 주세요.",
    meaning_ko: "차",
    meanings_extra: [],
    part_of_speech: "명사"
  },
  {
    no: 88,
    word: "杯子",
    word_traditional: "杯子",
    pinyin: "bēizi",
    zh: "这个杯子很漂亮。",
    zh_traditional: "這個杯子很漂亮。",
    zh_pinyin: "zhège bēizi hěn piàoliang.",
    ko: "이 컵은 매우 예쁘다.",
    meaning_ko: "컵",
    meanings_extra: ["잔"],
    part_of_speech: "명사"
  },
  {
    no: 89,
    word: "钱",
    word_traditional: "錢",
    pinyin: "qián",
    zh: "我有很多钱。",
    zh_traditional: "我有很多錢。",
    zh_pinyin: "wǒ yǒu hěn duō qián.",
    ko: "나는 돈이 많다.",
    meaning_ko: "돈",
    meanings_extra: ["화폐"],
    part_of_speech: "명사"
  },
  {
    no: 90,
    word: "飞机",
    word_traditional: "飛機",
    pinyin: "fēijī",
    zh: "飞机快要起飞了。",
    zh_traditional: "飛機快要起飛了。",
    zh_pinyin: "fēijī kuài yào qǐfēi le.",
    ko: "비행기가 곧 이륙한다.",
    meaning_ko: "비행기",
    meanings_extra: [],
    part_of_speech: "명사"
  },
  {
    no: 91,
    word: "出租车",
    word_traditional: "出租車",
    pinyin: "chūzūchē",
    zh: "我坐出租车去学校。",
    zh_traditional: "我坐出租車去學校。",
    zh_pinyin: "wǒ zuò chūzūchē qù xuéxiào.",
    ko: "나는 택시를 타고 학교에 간다.",
    meaning_ko: "택시",
    meanings_extra: [],
    part_of_speech: "명사"
  },
  {
    no: 92,
    word: "电视",
    word_traditional: "電視",
    pinyin: "diànshì",
    zh: "我喜欢看电视。",
    zh_traditional: "我喜歡看電視。",
    zh_pinyin: "wǒ xǐhuan kàn diànshì.",
    ko: "나는 텔레비전을 좋아한다.",
    meaning_ko: "텔레비전",
    meanings_extra: [],
    part_of_speech: "명사"
  },
  {
    no: 93,
    word: "电脑",
    word_traditional: "電腦",
    pinyin: "diànnǎo",
    zh: "我用电脑工作。",
    zh_traditional: "我用電腦工作。",
    zh_pinyin: "wǒ yòng diànnǎo gōngzuò.",
    ko: "나는 컴퓨터로 일한다.",
    meaning_ko: "컴퓨터",
    meanings_extra: [],
    part_of_speech: "명사"
  },
  {
    no: 94,
    word: "电影",
    word_traditional: "電影",
    pinyin: "diànyǐng",
    zh: "我们去看电影。",
    zh_traditional: "我們去看電影。",
    zh_pinyin: "wǒmen qù kàn diànyǐng.",
    ko: "우리는 영화 보러 간다.",
    meaning_ko: "영화",
    meanings_extra: [],
    part_of_speech: "명사"
  },
  {
    no: 95,
    word: "天气",
    word_traditional: "天氣",
    pinyin: "tiānqì",
    zh: "今天天气很好。",
    zh_traditional: "今天天氣很好。",
    zh_pinyin: "jīntiān tiānqì hěn hǎo.",
    ko: "오늘 날씨가 매우 좋다.",
    meaning_ko: "날씨",
    meanings_extra: [],
    part_of_speech: "명사"
  },
  {
    no: 96,
    word: "猫",
    word_traditional: "貓",
    pinyin: "māo",
    zh: "猫很可爱。",
    zh_traditional: "貓很可愛。",
    zh_pinyin: "māo hěn kě'ài.",
    ko: "고양이는 매우 귀엽다.",
    meaning_ko: "고양이",
    meanings_extra: [],
    part_of_speech: "명사"
  },
  {
    no: 97,
    word: "狗",
    word_traditional: "狗",
    pinyin: "gǒu",
    zh: "狗在跑。",
    zh_traditional: "狗在跑。",
    zh_pinyin: "gǒu zài pǎo.",
    ko: "개가 뛰고 있다.",
    meaning_ko: "개",
    meanings_extra: [],
    part_of_speech: "명사"
  },
  {
    no: 98,
    word: "东西",
    word_traditional: "東西",
    pinyin: "dōngxi",
    zh: "我买了一些东西。",
    zh_traditional: "我買了一些東西。",
    zh_pinyin: "wǒ mǎi le yìxiē dōngxi.",
    ko: "나는 물건을 좀 샀다.",
    meaning_ko: "물건",
    meanings_extra: ["것"],
    part_of_speech: "명사"
  },
  {
    no: 99,
    word: "人",
    word_traditional: "人",
    pinyin: "rén",
    zh: "这里有很多人。",
    zh_traditional: "這裡有很多人。",
    zh_pinyin: "zhèlǐ yǒu hěn duō rén.",
    ko: "여기에 사람이 많다.",
    meaning_ko: "사람",
    meanings_extra: [],
    part_of_speech: "명사"
  },
  {
    no: 100,
    word: "名字",
    word_traditional: "名字",
    pinyin: "míngzi",
    zh: "你的名字是什么？",
    zh_traditional: "你的名字是什麼？",
    zh_pinyin: "nǐ de míngzi shì shénme?",
    ko: "너의 이름이 뭐니?",
    meaning_ko: "이름",
    meanings_extra: [],
    part_of_speech: "명사"
  },
  {
    no: 101,
    word: "书",
    word_traditional: "書",
    pinyin: "shū",
    zh: "我喜欢看书。",
    zh_traditional: "我喜歡看書。",
    zh_pinyin: "wǒ xǐhuan kàn shū.",
    ko: "나는 책 읽는 것을 좋아한다.",
    meaning_ko: "책",
    meanings_extra: [],
    part_of_speech: "명사"
  },
  {
    no: 102,
    word: "汉语",
    word_traditional: "漢語",
    pinyin: "hànyǔ",
    zh: "我学习汉语。",
    zh_traditional: "我學習漢語。",
    zh_pinyin: "wǒ xuéxí hànyǔ.",
    ko: "나는 중국어를 공부한다.",
    meaning_ko: "중국어",
    meanings_extra: ["한어"],
    part_of_speech: "명사"
  },
  {
    no: 103,
    word: "字",
    word_traditional: "字",
    pinyin: "zì",
    zh: "我会写汉字。",
    zh_traditional: "我會寫漢字。",
    zh_pinyin: "wǒ huì xiě hànzì.",
    ko: "나는 한자를 쓸 수 있다.",
    meaning_ko: "글자, 문자",
    meanings_extra: [],
    part_of_speech: "명사"
  },
  {
    no: 104,
    word: "桌子",
    word_traditional: "桌子",
    pinyin: "zhuōzi",
    zh: "桌子上有书。",
    zh_traditional: "桌子上有書。",
    zh_pinyin: "zhuōzi shàng yǒu shū.",
    ko: "책상 위에 책이 있다.",
    meaning_ko: "책상",
    meanings_extra: [],
    part_of_speech: "명사"
  },
  {
    no: 105,
    word: "椅子",
    word_traditional: "椅子",
    pinyin: "yǐzi",
    zh: "椅子很舒服。",
    zh_traditional: "椅子很舒服。",
    zh_pinyin: "yǐzi hěn shūfu.",
    ko: "의자가 매우 편하다.",
    meaning_ko: "의자",
    meanings_extra: [],
    part_of_speech: "명사"
  },
  {
    no: 106,
    word: "谢谢",
    word_traditional: "謝謝",
    pinyin: "xièxie",
    zh: "谢谢你！",
    zh_traditional: "謝謝你！",
    zh_pinyin: "xièxie nǐ!",
    ko: "고마워!",
    meaning_ko: "감사하다",
    meanings_extra: ["고맙다"],
    part_of_speech: "동사"
  },
  {
    no: 107,
    word: "不客气",
    word_traditional: "不客氣",
    pinyin: "búkèqi",
    zh: "不客气！",
    zh_traditional: "不客氣！",
    zh_pinyin: "búkèqi!",
    ko: "천만에요!",
    meaning_ko: "천만에요, 별말씀을요",
    meanings_extra: ["별 말씀을요"],
    part_of_speech: "동사"
  },
  {
    no: 108,
    word: "再见",
    word_traditional: "再見",
    pinyin: "zàijiàn",
    zh: "再见！",
    zh_traditional: "再見！",
    zh_pinyin: "zàijiàn!",
    ko: "안녕히 가세요!",
    meaning_ko: "안녕, 작별 인사",
    meanings_extra: ["잘 가"],
    part_of_speech: "동사"
  },
  {
    no: 109,
    word: "请",
    word_traditional: "請",
    pinyin: "qǐng",
    zh: "请坐！",
    zh_traditional: "請坐！",
    zh_pinyin: "qǐng zuò!",
    ko: "앉으세요!",
    meaning_ko: "청하다, 부탁하다",
    meanings_extra: ["초대하다"],
    part_of_speech: "동사"
  },
  {
    no: 110,
    word: "对不起",
    word_traditional: "對不起",
    pinyin: "duìbuqǐ",
    zh: "对不起，我迟到了。",
    zh_traditional: "對不起，我遲到了。",
    zh_pinyin: "duìbuqǐ, wǒ chídào le.",
    ko: "죄송합니다, 제가 늦었습니다.",
    meaning_ko: "미안하다, 죄송하다",
    meanings_extra: ["사과하다"],
    part_of_speech: "동사"
  },
  {
    no: 111,
    word: "没关系",
    word_traditional: "沒關係",
    pinyin: "méiguānxi",
    zh: "没关系。",
    zh_traditional: "沒關係。",
    zh_pinyin: "méiguānxi.",
    ko: "괜찮아요.",
    meaning_ko: "괜찮다, 상관없다",
    meanings_extra: ["문제없다"],
    part_of_speech: "동사"
  },
  {
    no: 112,
    word: "是",
    word_traditional: "是",
    pinyin: "shì",
    zh: "我是学生。",
    zh_traditional: "我是學生。",
    zh_pinyin: "wǒ shì xuésheng.",
    ko: "나는 학생이다.",
    meaning_ko: "이다",
    meanings_extra: ["맞다"],
    part_of_speech: "동사"
  },
  {
    no: 113,
    word: "有",
    word_traditional: "有",
    pinyin: "yǒu",
    zh: "我有一本书。",
    zh_traditional: "我有一本書。",
    zh_pinyin: "wǒ yǒu yì běn shū.",
    ko: "나는 책 한 권이 있다.",
    meaning_ko: "가지다, 있다",
    meanings_extra: ["소유하다"],
    part_of_speech: "동사"
  },
  {
    no: 114,
    word: "看",
    word_traditional: "看",
    pinyin: "kàn",
    zh: "我看电视。",
    zh_traditional: "我看電視。",
    zh_pinyin: "wǒ kàn diànshì.",
    ko: "나는 텔레비전을 본다.",
    meaning_ko: "보다",
    meanings_extra: ["관찰하다"],
    part_of_speech: "동사"
  },
  {
    no: 115,
    word: "听",
    word_traditional: "聽",
    pinyin: "tīng",
    zh: "我听音乐。",
    zh_traditional: "我聽音樂。",
    zh_pinyin: "wǒ tīng yīnyuè.",
    ko: "나는 음악을 듣는다.",
    meaning_ko: "듣다",
    meanings_extra: ["경청하다"],
    part_of_speech: "동사"
  },
  {
    no: 116,
    word: "说",
    word_traditional: "說",
    pinyin: "shuō",
    zh: "他说汉语。",
    zh_traditional: "他說漢語。",
    zh_pinyin: "tā shuō hànyǔ.",
    ko: "그는 중국어를 말한다.",
    meaning_ko: "말하다",
    meanings_extra: ["이야기하다"],
    part_of_speech: "동사"
  },
  {
    no: 117,
    word: "读",
    word_traditional: "讀",
    pinyin: "dú",
    zh: "我读书。",
    zh_traditional: "我讀書。",
    zh_pinyin: "wǒ dú shū.",
    ko: "나는 책을 읽는다.",
    meaning_ko: "읽다",
    meanings_extra: ["공부하다"],
    part_of_speech: "동사"
  },
  {
    no: 118,
    word: "写",
    word_traditional: "寫",
    pinyin: "xiě",
    zh: "我写字。",
    zh_traditional: "我寫字。",
    zh_pinyin: "wǒ xiě zì.",
    ko: "나는 글을 쓴다.",
    meaning_ko: "쓰다",
    meanings_extra: [],
    part_of_speech: "동사"
  },
  {
    no: 119,
    word: "看见",
    word_traditional: "看見",
    pinyin: "kànjiàn",
    zh: "我看见了一只猫。",
    zh_traditional: "我看見了一隻貓。",
    zh_pinyin: "wǒ kànjiàn le yì zhī māo.",
    ko: "나는 고양이 한 마리를 봤다.",
    meaning_ko: "보다, 목격하다",
    meanings_extra: ["보이다"],
    part_of_speech: "동사"
  },
  {
    no: 120,
    word: "叫",
    word_traditional: "叫",
    pinyin: "jiào",
    zh: "我叫王明。",
    zh_traditional: "我叫王明。",
    zh_pinyin: "wǒ jiào Wáng Míng.",
    ko: "내 이름은 왕밍이다.",
    meaning_ko: "부르다, 이름이 ~이다",
    meanings_extra: ["소리치다"],
    part_of_speech: "동사"
  },
  {
    no: 121,
    word: "来",
    word_traditional: "來",
    pinyin: "lái",
    zh: "他来了。",
    zh_traditional: "他來了。",
    zh_pinyin: "tā lái le.",
    ko: "그가 왔다.",
    meaning_ko: "오다",
    meanings_extra: [],
    part_of_speech: "동사"
  },
  {
    no: 122,
    word: "回",
    word_traditional: "回",
    pinyin: "huí",
    zh: "我回家了。",
    zh_traditional: "我回家了。",
    zh_pinyin: "wǒ huí jiā le.",
    ko: "나는 집에 돌아왔다.",
    meaning_ko: "돌아가다, 돌아오다",
    meanings_extra: [],
    part_of_speech: "동사"
  },
  {
    no: 123,
    word: "去",
    word_traditional: "去",
    pinyin: "qù",
    zh: "我去学校。",
    zh_traditional: "我去學校。",
    zh_pinyin: "wǒ qù xuéxiào.",
    ko: "나는 학교에 간다.",
    meaning_ko: "가다",
    meanings_extra: [],
    part_of_speech: "동사"
  },
  {
    no: 124,
    word: "吃",
    word_traditional: "吃",
    pinyin: "chī",
    zh: "我吃饭。",
    zh_traditional: "我吃飯。",
    zh_pinyin: "wǒ chī fàn.",
    ko: "나는 밥을 먹는다.",
    meaning_ko: "먹다",
    meanings_extra: [],
    part_of_speech: "동사"
  },
  {
    no: 125,
    word: "喝",
    word_traditional: "喝",
    pinyin: "hē",
    zh: "我喝水。",
    zh_traditional: "我喝水。",
    zh_pinyin: "wǒ hē shuǐ.",
    ko: "나는 물을 마신다.",
    meaning_ko: "마시다",
    meanings_extra: [],
    part_of_speech: "동사"
  },
  {
    no: 126,
    word: "睡觉",
    word_traditional: "睡覺",
    pinyin: "shuìjiào",
    zh: "我晚上十点睡觉。",
    zh_traditional: "我晚上十點睡覺。",
    zh_pinyin: "wǒ wǎnshang shí diǎn shuìjiào.",
    ko: "나는 저녁 10시에 잠잔다.",
    meaning_ko: "잠자다",
    meanings_extra: ["잠들다"],
    part_of_speech: "동사"
  },
  {
    no: 127,
    word: "打电话",
    word_traditional: "打電話",
    pinyin: "dǎ diànhuà",
    zh: "我给妈妈打电话。",
    zh_traditional: "我給媽媽打電話。",
    zh_pinyin: "wǒ gěi māma dǎ diànhuà.",
    ko: "나는 엄마에게 전화한다.",
    meaning_ko: "전화하다",
    meanings_extra: [],
    part_of_speech: "동사"
  },
  {
    no: 128,
    word: "做",
    word_traditional: "做",
    pinyin: "zuò",
    zh: "我做作业。",
    zh_traditional: "我做作業。",
    zh_pinyin: "wǒ zuò zuòyè.",
    ko: "나는 숙제를 한다.",
    meaning_ko: "하다, 만들다",
    meanings_extra: [],
    part_of_speech: "동사"
  },
  {
    no: 129,
    word: "买",
    word_traditional: "買",
    pinyin: "mǎi",
    zh: "我买了水果。",
    zh_traditional: "我買了水果。",
    zh_pinyin: "wǒ mǎi le shuǐguǒ.",
    ko: "나는 과일을 샀다.",
    meaning_ko: "사다",
    meanings_extra: [],
    part_of_speech: "동사"
  },
  {
    no: 130,
    word: "开",
    word_traditional: "開",
    pinyin: "kāi",
    zh: "请开门。",
    zh_traditional: "請開門。",
    zh_pinyin: "qǐng kāi mén.",
    ko: "문을 열어 주세요.",
    meaning_ko: "열다, 운전하다",
    meanings_extra: [],
    part_of_speech: "동사"
  },
  {
    no: 131,
    word: "坐",
    word_traditional: "坐",
    pinyin: "zuò",
    zh: "我坐公交车去学校。",
    zh_traditional: "我坐公交車去學校。",
    zh_pinyin: "wǒ zuò gōngjiāochē qù xuéxiào.",
    ko: "나는 버스를 타고 학교에 간다.",
    meaning_ko: "앉다, 타다",
    meanings_extra: [],
    part_of_speech: "동사"
  },
  {
    no: 132,
    word: "住",
    word_traditional: "住",
    pinyin: "zhù",
    zh: "我住在北京。",
    zh_traditional: "我住在北京。",
    zh_pinyin: "wǒ zhù zài Běijīng.",
    ko: "나는 베이징에 산다.",
    meaning_ko: "살다, 머무르다",
    meanings_extra: [],
    part_of_speech: "동사"
  },
  {
    no: 133,
    word: "学习",
    word_traditional: "學習",
    pinyin: "xuéxí",
    zh: "我学习汉语。",
    zh_traditional: "我學習漢語。",
    zh_pinyin: "wǒ xuéxí hànyǔ.",
    ko: "나는 중국어를 공부한다.",
    meaning_ko: "공부하다",
    meanings_extra: [],
    part_of_speech: "동사"
  },
  {
    no: 134,
    word: "工作",
    word_traditional: "工作",
    pinyin: "gōngzuò",
    zh: "他在工作。",
    zh_traditional: "他在工作。",
    zh_pinyin: "tā zài gōngzuò.",
    ko: "그는 일하고 있다.",
    meaning_ko: "일하다",
    meanings_extra: ["직업"],
    part_of_speech: "동사/명사"
  },
  {
    no: 135,
    word: "下雨",
    word_traditional: "下雨",
    pinyin: "xiàyǔ",
    zh: "今天下雨了。",
    zh_traditional: "今天下雨了。",
    zh_pinyin: "jīntiān xiàyǔ le.",
    ko: "오늘 비가 왔다.",
    meaning_ko: "비가 내리다",
    meanings_extra: [],
    part_of_speech: "동사"
  },
  {
    no: 136,
    word: "爱",
    word_traditional: "愛",
    pinyin: "ài",
    zh: "我爱你。",
    zh_traditional: "我愛你。",
    zh_pinyin: "wǒ ài nǐ.",
    ko: "나는 너를 사랑한다.",
    meaning_ko: "사랑하다",
    meanings_extra: [],
    part_of_speech: "동사"
  },
  {
    no: 137,
    word: "喜欢",
    word_traditional: "喜歡",
    pinyin: "xǐhuān",
    zh: "我喜欢吃苹果。",
    zh_traditional: "我喜歡吃蘋果。",
    zh_pinyin: "wǒ xǐhuān chī píngguǒ.",
    ko: "나는 사과 먹는 것을 좋아한다.",
    meaning_ko: "좋아하다",
    meanings_extra: ["사랑하다"],
    part_of_speech: "동사"
  },
  {
    no: 138,
    word: "想",
    word_traditional: "想",
    pinyin: "xiǎng",
    zh: "我想去中国。",
    zh_traditional: "我想去中國。",
    zh_pinyin: "wǒ xiǎng qù Zhōngguó.",
    ko: "나는 중국에 가고 싶다.",
    meaning_ko: "원하다, 생각하다",
    meanings_extra: ["생각하다"],
    part_of_speech: "동사"
  },
  {
    no: 139,
    word: "认识",
    word_traditional: "認識",
    pinyin: "rènshi",
    zh: "我认识他。",
    zh_traditional: "我認識他。",
    zh_pinyin: "wǒ rènshi tā.",
    ko: "나는 그를 안다.",
    meaning_ko: "알다, 인식하다",
    meanings_extra: ["만나다"],
    part_of_speech: "동사"
  },
  {
    no: 140,
    word: "会",
    word_traditional: "會",
    pinyin: "huì",
    zh: "我会说汉语。",
    zh_traditional: "我會說漢語。",
    zh_pinyin: "wǒ huì shuō hànyǔ.",
    ko: "나는 중국어를 말할 수 있다.",
    meaning_ko: "할 수 있다, ~할 줄 알다",
    meanings_extra: ["회의"],
    part_of_speech: "조동사"
  },
  {
    no: 141,
    word: "能",
    word_traditional: "能",
    pinyin: "néng",
    zh: "我能说中文。",
    zh_traditional: "我能說中文。",
    zh_pinyin: "wǒ néng shuō Zhōngwén.",
    ko: "나는 중국어를 할 수 있다.",
    meaning_ko: "할 수 있다, 능력 있다",
    meanings_extra: ["~할 줄 알다"],
    part_of_speech: "조동사"
  },
  {
    no: 142,
    word: "好",
    word_traditional: "好",
    pinyin: "hǎo",
    zh: "这个菜很好吃。",
    zh_traditional: "這個菜很好吃。",
    zh_pinyin: "zhège cài hěn hǎochī.",
    ko: "이 음식은 매우 맛있다.",
    meaning_ko: "좋다",
    meanings_extra: ["맛있다"],
    part_of_speech: "형용사"
  },
  {
    no: 143,
    word: "大",
    word_traditional: "大",
    pinyin: "dà",
    zh: "这栋房子很大。",
    zh_traditional: "這棟房子很大。",
    zh_pinyin: "zhè dòng fángzi hěn dà.",
    ko: "이 집은 매우 크다.",
    meaning_ko: "크다",
    meanings_extra: ["넓다"],
    part_of_speech: "형용사"
  },
  {
    no: 144,
    word: "小",
    word_traditional: "小",
    pinyin: "xiǎo",
    zh: "我的手机很小。",
    zh_traditional: "我的手機很小。",
    zh_pinyin: "wǒ de shǒujī hěn xiǎo.",
    ko: "내 휴대폰은 매우 작다.",
    meaning_ko: "작다",
    meanings_extra: ["어리다"],
    part_of_speech: "형용사"
  },
  {
    no: 145,
    word: "多",
    word_traditional: "多",
    pinyin: "duō",
    zh: "他有很多书。",
    zh_traditional: "他有很多書。",
    zh_pinyin: "tā yǒu hěn duō shū.",
    ko: "그는 책이 많다.",
    meaning_ko: "많다",
    meanings_extra: ["여러"],
    part_of_speech: "형용사/부사"
  },
  {
    no: 146,
    word: "少",
    word_traditional: "少",
    pinyin: "shǎo",
    zh: "这里人很少。",
    zh_traditional: "這裡人很少。",
    zh_pinyin: "zhèlǐ rén hěn shǎo.",
    ko: "여기는 사람이 적다.",
    meaning_ko: "적다",
    meanings_extra: ["모자라다"],
    part_of_speech: "형용사"
  },
  {
    no: 147,
    word: "冷",
    word_traditional: "冷",
    pinyin: "lěng",
    zh: "冬天很冷。",
    zh_traditional: "冬天很冷。",
    zh_pinyin: "dōngtiān hěn lěng.",
    ko: "겨울은 매우 춥다.",
    meaning_ko: "춥다",
    meanings_extra: [],
    part_of_speech: "형용사"
  },
  {
    no: 148,
    word: "热",
    word_traditional: "熱",
    pinyin: "rè",
    zh: "天气很热。",
    zh_traditional: "天氣很熱。",
    zh_pinyin: "tiānqì hěn rè.",
    ko: "날씨가 매우 덥다.",
    meaning_ko: "덥다",
    meanings_extra: [],
    part_of_speech: "형용사"
  },
  {
    no: 149,
    word: "高兴",
    word_traditional: "高興",
    pinyin: "gāoxìng",
    zh: "我很高兴见到你。",
    zh_traditional: "我很高興見到你。",
    zh_pinyin: "wǒ hěn gāoxìng jiàn dào nǐ.",
    ko: "나는 너를 만나서 매우 기쁘다.",
    meaning_ko: "기쁘다",
    meanings_extra: ["즐겁다"],
    part_of_speech: "형용사"
  },
  {
    no: 150,
    word: "漂亮",
    word_traditional: "漂亮",
    pinyin: "piàoliang",
    zh: "她很漂亮。",
    zh_traditional: "她很漂亮。",
    zh_pinyin: "tā hěn piàoliang.",
    ko: "그녀는 매우 예쁘다.",
    meaning_ko: "예쁘다",
    meanings_extra: ["아름답다"],
    part_of_speech: "형용사"
  }
]
