const quizList = [
    {
      no: 1,
      word: "一",
      word_traditional: "一",
      pinyin: "yī",
      zh: "我有一只狗。",
      zh_traditional: "我有一隻狗。",
      zh_pinyin: "wǒ yǒu yī zhī gǒu.",
      ko: "나는 개 한 마리가 있다.",
      meaning_ko: "일, 하나",
      meanings_extra: ["한 개", "첫 번째"],
      part_of_speech: "수사"
    },
    {
      no: 2,
      word: "二",
      word_traditional: "二",
      pinyin: "èr",
      zh: "我有两个苹果。",
      zh_traditional: "我有兩個蘋果。",
      zh_pinyin: "wǒ yǒu liǎng gè píngguǒ.",
      ko: "나는 사과 두 개가 있다.",
      meaning_ko: "이, 둘",
      meanings_extra: ["두 개", "두 번째"],
      part_of_speech: "수사"
    },
    {
      no: 3,
      word: "三",
      word_traditional: "三",
      pinyin: "sān",
      zh: "他有三个朋友。",
      zh_traditional: "他有三個朋友。",
      zh_pinyin: "tā yǒu sān gè péngyou.",
      ko: "그는 친구 세 명이 있다.",
      meaning_ko: "삼, 셋",
      meanings_extra: ["세 개", "세 번째"],
      part_of_speech: "수사"
    },
    {
      no: 4,
      word: "四",
      word_traditional: "四",
      pinyin: "sì",
      zh: "我家有四个人。",
      zh_traditional: "我家有四個人。",
      zh_pinyin: "wǒ jiā yǒu sì gè rén.",
      ko: "우리 집에는 네 명이 있다.",
      meaning_ko: "사, 넷",
      meanings_extra: ["네 개", "네 번째"],
      part_of_speech: "수사"
    },
    {
      no: 5,
      word: "五",
      word_traditional: "五",
      pinyin: "wǔ",
      zh: "今天是五月五号。",
      zh_traditional: "今天是五月五號。",
      zh_pinyin: "jīntiān shì wǔ yuè wǔ hào.",
      ko: "오늘은 5월 5일이다.",
      meaning_ko: "오, 다섯",
      meanings_extra: ["다섯 개", "다섯 번째"],
      part_of_speech: "수사"
    },
    {
      no: 6,
      word: "六",
      word_traditional: "六",
      pinyin: "liù",
      zh: "他六岁了。",
      zh_traditional: "他六歲了。",
      zh_pinyin: "tā liù suì le.",
      ko: "그는 여섯 살이다.",
      meaning_ko: "육, 여섯",
      meanings_extra: ["여섯 개", "여섯 번째"],
      part_of_speech: "수사"
    },
    {
      no: 7,
      word: "七",
      word_traditional: "七",
      pinyin: "qī",
      zh: "我有七本书。",
      zh_traditional: "我有七本書。",
      zh_pinyin: "wǒ yǒu qī běn shū.",
      ko: "나는 책 일곱 권이 있다.",
      meaning_ko: "칠, 일곱",
      meanings_extra: ["일곱 개", "일곱 번째"],
      part_of_speech: "수사"
    },
    {
      no: 8,
      word: "八",
      word_traditional: "八",
      pinyin: "bā",
      zh: "他买了八个苹果。",
      zh_traditional: "他買了八個蘋果。",
      zh_pinyin: "tā mǎile bā gè píngguǒ.",
      ko: "그는 사과 여덟 개를 샀다.",
      meaning_ko: "팔, 여덟",
      meanings_extra: ["여덟 개", "여덟 번째"],
      part_of_speech: "수사"
    },
    {
      no: 9,
      word: "九",
      word_traditional: "九",
      pinyin: "jiǔ",
      zh: "这里有九把椅子。",
      zh_traditional: "這裡有九把椅子。",
      zh_pinyin: "zhèlǐ yǒu jiǔ bǎ yǐzi.",
      ko: "여기에 의자 아홉 개가 있다.",
      meaning_ko: "구, 아홉",
      meanings_extra: ["아홉 개", "아홉 번째"],
      part_of_speech: "수사"
    },
    {
      no: 10,
      word: "十",
      word_traditional: "十",
      pinyin: "shí",
      zh: "我有十个朋友。",
      zh_traditional: "我有十個朋友。",
      zh_pinyin: "wǒ yǒu shí gè péngyou.",
      ko: "나는 친구 열 명이 있다.",
      meaning_ko: "십, 열",
      meanings_extra: ["열 개", "열 번째"],
      part_of_speech: "수사"
    },
    {
      no: 11,
      word: "零",
      word_traditional: "零",
      pinyin: "líng",
      zh: "零度很冷。",
      zh_traditional: "零度很冷。",
      zh_pinyin: "líng dù hěn lěng.",
      ko: "영도는 매우 춥다.",
      meaning_ko: "영, 0",
      meanings_extra: ["제로", "영점"],
      part_of_speech: "수사"
    },
    {
      no: 12,
      word: "几",
      word_traditional: "幾",
      pinyin: "jǐ",
      zh: "你有几个苹果？",
      zh_traditional: "你有幾個蘋果？",
      zh_pinyin: "nǐ yǒu jǐ gè píngguǒ?",
      ko: "너는 사과 몇 개 있어?",
      meaning_ko: "몇",
      meanings_extra: ["얼마나", "몇 개"],
      part_of_speech: "의문대명사"
    },
    {
      no: 13,
      word: "号",
      word_traditional: "號",
      pinyin: "hào",
      zh: "今天是几号？",
      zh_traditional: "今天是幾號？",
      zh_pinyin: "jīntiān shì jǐ hào?",
      ko: "오늘 며칠이에요?",
      meaning_ko: "번호, 날짜",
      meanings_extra: ["순번", "날짜"],
      part_of_speech: "명사"
    },
    {
      no: 14,
      word: "岁",
      word_traditional: "歲",
      pinyin: "suì",
      zh: "我十岁。",
      zh_traditional: "我十歲。",
      zh_pinyin: "wǒ shí suì.",
      ko: "나는 열 살이다.",
      meaning_ko: "살, 세",
      meanings_extra: ["나이", "연령"],
      part_of_speech: "양사"
    },
    {
      no: 15,
      word: "个",
      word_traditional: "個",
      pinyin: "gè",
      zh: "我有一个苹果。",
      zh_traditional: "我有一個蘋果。",
      zh_pinyin: "wǒ yǒu yī gè píngguǒ.",
      ko: "나는 사과 하나가 있다.",
      meaning_ko: "개 (양사)",
      meanings_extra: ["명 (사람 셀 때)", "단위"],
      part_of_speech: "양사"
    },
    {
      no: 16,
      word: "本",
      word_traditional: "本",
      pinyin: "běn",
      zh: "这本书很好。",
      zh_traditional: "這本書很好。",
      zh_pinyin: "zhè běn shū hěn hǎo.",
      ko: "이 책은 좋다.",
      meaning_ko: "권 (책 셀 때)",
      meanings_extra: ["책", "권"],
      part_of_speech: "양사"
    },
    {
      no: 17,
      word: "些",
      word_traditional: "些",
      pinyin: "xiē",
      zh: "我买了一些水果。",
      zh_traditional: "我買了一些水果。",
      zh_pinyin: "wǒ mǎile yīxiē shuǐguǒ.",
      ko: "나는 과일을 조금 샀다.",
      meaning_ko: "조금, 약간",
      meanings_extra: ["몇몇", "약간"],
      part_of_speech: "양사"
    },
    {
      no: 18,
      word: "块",
      word_traditional: "塊",
      pinyin: "kuài",
      zh: "我吃了一块蛋糕。",
      zh_traditional: "我吃了一塊蛋糕。",
      zh_pinyin: "wǒ chīle yī kuài dàngāo.",
      ko: "나는 케이크 한 조각을 먹었다.",
      meaning_ko: "덩어리, 조각",
      meanings_extra: ["조각", "덩어리 모양 물건 셀 때"],
      part_of_speech: "양사/명사"
    },
    {
      no: 19,
      word: "一点儿",
      word_traditional: "一點兒",
      pinyin: "yìdiǎnr",
      zh: "我喝了一点儿水。",
      zh_traditional: "我喝了一點兒水。",
      zh_pinyin: "wǒ hēle yìdiǎnr shuǐ.",
      ko: "나는 물을 조금 마셨다.",
      meaning_ko: "조금",
      meanings_extra: ["약간", "조금씩"],
      part_of_speech: "양사"
    },
    {
      no: 20,
      word: "家",
      word_traditional: "家",
      pinyin: "jiā",
      zh: "我家有三口人。",
      zh_traditional: "我家有三口人。",
      zh_pinyin: "wǒ jiā yǒu sān kǒu rén.",
      ko: "우리 집에는 세 식구가 있다.",
      meaning_ko: "집, 가족",
      meanings_extra: ["가게", "회사"],
      part_of_speech: "명사"
    },
    {
        no: 21,
        word: "我",
        word_traditional: "我",
        pinyin: "wǒ",
        zh: "我喜欢吃水果。",
        zh_traditional: "我喜歡吃水果。",
        zh_pinyin: "wǒ xǐhuan chī shuǐguǒ.",
        ko: "나는 과일 먹는 것을 좋아한다.",
        meaning_ko: "나",
        meanings_extra: ["저", "본인"],
        part_of_speech: "대명사"
      },
      {
        no: 22,
        word: "我们",
        word_traditional: "我們",
        pinyin: "wǒmen",
        zh: "我们去学校。",
        zh_traditional: "我們去學校。",
        zh_pinyin: "wǒmen qù xuéxiào.",
        ko: "우리는 학교에 간다.",
        meaning_ko: "우리",
        meanings_extra: ["저희", "우리들"],
        part_of_speech: "대명사"
      },
      {
        no: 23,
        word: "你",
        word_traditional: "你",
        pinyin: "nǐ",
        zh: "你好吗？",
        zh_traditional: "你好嗎？",
        zh_pinyin: "nǐ hǎo ma?",
        ko: "잘 지내니?",
        meaning_ko: "너",
        meanings_extra: ["당신"],
        part_of_speech: "대명사"
      },
      {
        no: 24,
        word: "他",
        word_traditional: "他",
        pinyin: "tā",
        zh: "他是我的朋友。",
        zh_traditional: "他是我的朋友。",
        zh_pinyin: "tā shì wǒ de péngyou.",
        ko: "그는 내 친구이다.",
        meaning_ko: "그",
        meanings_extra: [],
        part_of_speech: "대명사"
      },
      {
        no: 25,
        word: "她",
        word_traditional: "她",
        pinyin: "tā",
        zh: "她喜欢喝茶。",
        zh_traditional: "她喜歡喝茶。",
        zh_pinyin: "tā xǐhuan hē chá.",
        ko: "그녀는 차 마시는 것을 좋아한다.",
        meaning_ko: "그녀",
        meanings_extra: [],
        part_of_speech: "대명사"
      },
      {
        no: 26,
        word: "妈妈",
        word_traditional: "媽媽",
        pinyin: "māma",
        zh: "妈妈在家。",
        zh_traditional: "媽媽在家。",
        zh_pinyin: "māma zài jiā.",
        ko: "엄마가 집에 있다.",
        meaning_ko: "엄마",
        meanings_extra: ["어머니"],
        part_of_speech: "명사"
      },
      {
        no: 27,
        word: "爸爸",
        word_traditional: "爸爸",
        pinyin: "bàba",
        zh: "爸爸工作忙。",
        zh_traditional: "爸爸工作忙。",
        zh_pinyin: "bàba gōngzuò máng.",
        ko: "아빠는 일이 바쁘다.",
        meaning_ko: "아빠",
        meanings_extra: ["아버지"],
        part_of_speech: "명사"
      },
      {
        no: 28,
        word: "女儿",
        word_traditional: "女兒",
        pinyin: "nǚ'ér",
        zh: "她有一个女儿。",
        zh_traditional: "她有一個女兒。",
        zh_pinyin: "tā yǒu yí gè nǚ'ér.",
        ko: "그녀는 딸이 한 명 있다.",
        meaning_ko: "딸",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 29,
        word: "儿子",
        word_traditional: "兒子",
        pinyin: "érzi",
        zh: "他有两个儿子。",
        zh_traditional: "他有兩個兒子。",
        zh_pinyin: "tā yǒu liǎng gè érzi.",
        ko: "그는 아들이 두 명 있다.",
        meaning_ko: "아들",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 30,
        word: "人",
        word_traditional: "人",
        pinyin: "rén",
        zh: "这里有很多人。",
        zh_traditional: "這裡有很多人。",
        zh_pinyin: "zhèlǐ yǒu hěn duō rén.",
        ko: "여기에 사람이 많다.",
        meaning_ko: "사람",
        meanings_extra: ["인간"],
        part_of_speech: "명사"
      },
      {
        no: 31,
        word: "老师",
        word_traditional: "老師",
        pinyin: "lǎoshī",
        zh: "老师很高兴。",
        zh_traditional: "老師很高興。",
        zh_pinyin: "lǎoshī hěn gāoxìng.",
        ko: "선생님은 매우 기쁘다.",
        meaning_ko: "선생님",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 32,
        word: "学校",
        word_traditional: "學校",
        pinyin: "xuéxiào",
        zh: "我去学校。",
        zh_traditional: "我去學校。",
        zh_pinyin: "wǒ qù xuéxiào.",
        ko: "나는 학교에 간다.",
        meaning_ko: "학교",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 33,
        word: "学生",
        word_traditional: "學生",
        pinyin: "xuésheng",
        zh: "他是学生。",
        zh_traditional: "他是學生。",
        zh_pinyin: "tā shì xuésheng.",
        ko: "그는 학생이다.",
        meaning_ko: "학생",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 34,
        word: "同学",
        word_traditional: "同學",
        pinyin: "tóngxué",
        zh: "她是我的同学。",
        zh_traditional: "她是我的同學。",
        zh_pinyin: "tā shì wǒ de tóngxué.",
        ko: "그녀는 내 급우이다.",
        meaning_ko: "학교 친구",
        meanings_extra: ["동창", "급우"],
        part_of_speech: "명사"
      },
      {
        no: 35,
        word: "朋友",
        word_traditional: "朋友",
        pinyin: "péngyou",
        zh: "我有很多朋友。",
        zh_traditional: "我有很多朋友。",
        zh_pinyin: "wǒ yǒu hěn duō péngyou.",
        ko: "나는 친구가 많다.",
        meaning_ko: "친구",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 36,
        word: "名字",
        word_traditional: "名字",
        pinyin: "míngzi",
        zh: "你叫什么名字？",
        zh_traditional: "你叫什麼名字？",
        zh_pinyin: "nǐ jiào shénme míngzi?",
        ko: "너 이름이 뭐니?",
        meaning_ko: "이름",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 37,
        word: "先生",
        word_traditional: "先生",
        pinyin: "xiānsheng",
        zh: "这是王先生。",
        zh_traditional: "這是王先生。",
        zh_pinyin: "zhè shì Wáng xiānsheng.",
        ko: "이분은 왕 선생님(왕씨)이다.",
        meaning_ko: "선생님, ~씨",
        meanings_extra: ["남자 존칭"],
        part_of_speech: "명사"
      },
      {
        no: 38,
        word: "小姐",
        word_traditional: "小姐",
        pinyin: "xiǎojiě",
        zh: "李小姐很好。",
        zh_traditional: "李小姐很好。",
        zh_pinyin: "Lǐ xiǎojiě hěn hǎo.",
        ko: "이 아가씨는 매우 좋다.",
        meaning_ko: "아가씨",
        meanings_extra: ["미혼 여성 존칭"],
        part_of_speech: "명사"
      },
      {
        no: 39,
        word: "医生",
        word_traditional: "醫生",
        pinyin: "yīshēng",
        zh: "医生在医院工作。",
        zh_traditional: "醫生在醫院工作。",
        zh_pinyin: "yīshēng zài yīyuàn gōngzuò.",
        ko: "의사가 병원에서 일한다.",
        meaning_ko: "의사",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 40,
        word: "医院",
        word_traditional: "醫院",
        pinyin: "yīyuàn",
        zh: "医院很大。",
        zh_traditional: "醫院很大。",
        zh_pinyin: "yīyuàn hěn dà.",
        ko: "병원이 크다.",
        meaning_ko: "병원",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 41,
        word: "商店",
        word_traditional: "商店",
        pinyin: "shāngdiàn",
        zh: "商店里有很多东西。",
        zh_traditional: "商店裡有很多東西。",
        zh_pinyin: "shāngdiàn lǐ yǒu hěn duō dōngxi.",
        ko: "가게 안에 물건이 많다.",
        meaning_ko: "상점, 가게",
        meanings_extra: ["가게", "상점"],
        part_of_speech: "명사"
      },
      {
        no: 42,
        word: "饭馆",
        word_traditional: "飯館",
        pinyin: "fànguǎn",
        zh: "我们去饭馆吃饭。",
        zh_traditional: "我們去飯館吃飯。",
        zh_pinyin: "wǒmen qù fànguǎn chīfàn.",
        ko: "우리는 식당에 가서 밥을 먹는다.",
        meaning_ko: "식당",
        meanings_extra: ["음식점", "레스토랑"],
        part_of_speech: "명사"
      },
      {
        no: 43,
        word: "东西",
        word_traditional: "東西",
        pinyin: "dōngxi",
        zh: "我买了很多东西。",
        zh_traditional: "我買了很多東西。",
        zh_pinyin: "wǒ mǎile hěn duō dōngxi.",
        ko: "나는 물건을 많이 샀다.",
        meaning_ko: "물건",
        meanings_extra: ["것", "물건"],
        part_of_speech: "명사"
      },
      {
        no: 44,
        word: "书",
        word_traditional: "書",
        pinyin: "shū",
        zh: "我喜欢看书。",
        zh_traditional: "我喜歡看書。",
        zh_pinyin: "wǒ xǐhuan kàn shū.",
        ko: "나는 책 읽는 것을 좋아한다.",
        meaning_ko: "책",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 45,
        word: "桌子",
        word_traditional: "桌子",
        pinyin: "zhuōzi",
        zh: "桌子上有一本书。",
        zh_traditional: "桌子上有一本書。",
        zh_pinyin: "zhuōzi shàng yǒu yī běn shū.",
        ko: "책상이 위에 책 한 권이 있다.",
        meaning_ko: "탁자, 책상",
        meanings_extra: ["테이블"],
        part_of_speech: "명사"
      },
      {
        no: 46,
        word: "椅子",
        word_traditional: "椅子",
        pinyin: "yǐzi",
        zh: "这里有三把椅子。",
        zh_traditional: "這裡有三把椅子。",
        zh_pinyin: "zhèlǐ yǒu sān bǎ yǐzi.",
        ko: "여기에 의자 세 개가 있다.",
        meaning_ko: "의자",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 47,
        word: "杯子",
        word_traditional: "杯子",
        pinyin: "bēizi",
        zh: "杯子里有水。",
        zh_traditional: "杯子裡有水。",
        zh_pinyin: "bēizi lǐ yǒu shuǐ.",
        ko: "컵 안에 물이 있다.",
        meaning_ko: "컵",
        meanings_extra: ["잔"],
        part_of_speech: "명사"
      },
      {
        no: 48,
        word: "中国",
        word_traditional: "中國",
        pinyin: "Zhōngguó",
        zh: "中国是一个大国。",
        zh_traditional: "中國是一個大國。",
        zh_pinyin: "Zhōngguó shì yī gè dà guó.",
        ko: "중국은 큰 나라이다.",
        meaning_ko: "중국",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 49,
        word: "北京",
        word_traditional: "北京",
        pinyin: "Běijīng",
        zh: "北京是中国的首都。",
        zh_traditional: "北京是中國的首都。",
        zh_pinyin: "Běijīng shì Zhōngguó de shǒudū.",
        ko: "베이징은 중국의 수도이다.",
        meaning_ko: "베이징",
        meanings_extra: ["북경"],
        part_of_speech: "명사"
      },
      {
        no: 50,
        word: "汉语",
        word_traditional: "漢語",
        pinyin: "Hànyǔ",
        zh: "我学习汉语。",
        zh_traditional: "我學習漢語。",
        zh_pinyin: "wǒ xuéxí Hànyǔ.",
        ko: "나는 중국어를 공부한다.",
        meaning_ko: "중국어",
        meanings_extra: ["한어"],
        part_of_speech: "명사"
      },
      {
        no: 51,
        word: "水果",
        word_traditional: "水果",
        pinyin: "shuǐguǒ",
        zh: "我喜欢吃水果。",
        zh_traditional: "我喜歡吃水果。",
        zh_pinyin: "wǒ xǐhuan chī shuǐguǒ.",
        ko: "나는 과일 먹는 것을 좋아한다.",
        meaning_ko: "과일",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 52,
        word: "苹果",
        word_traditional: "蘋果",
        pinyin: "píngguǒ",
        zh: "我吃了一个苹果。",
        zh_traditional: "我吃了一個蘋果。",
        zh_pinyin: "wǒ chīle yī gè píngguǒ.",
        ko: "나는 사과 한 개를 먹었다.",
        meaning_ko: "사과",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 53,
        word: "水",
        word_traditional: "水",
        pinyin: "shuǐ",
        zh: "我喝水。",
        zh_traditional: "我喝水。",
        zh_pinyin: "wǒ hē shuǐ.",
        ko: "나는 물을 마신다.",
        meaning_ko: "물",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 54,
        word: "茶",
        word_traditional: "茶",
        pinyin: "chá",
        zh: "我喝茶。",
        zh_traditional: "我喝茶。",
        zh_pinyin: "wǒ hē chá.",
        ko: "나는 차를 마신다.",
        meaning_ko: "차",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 55,
        word: "菜",
        word_traditional: "菜",
        pinyin: "cài",
        zh: "我喜欢吃菜。",
        zh_traditional: "我喜歡吃菜。",
        zh_pinyin: "wǒ xǐhuan chī cài.",
        ko: "나는 채소를 좋아한다.",
        meaning_ko: "채소, 요리",
        meanings_extra: ["음식"],
        part_of_speech: "명사"
      },
      {
        no: 56,
        word: "米饭",
        word_traditional: "米飯",
        pinyin: "mǐfàn",
        zh: "我吃米饭。",
        zh_traditional: "我吃米飯。",
        zh_pinyin: "wǒ chī mǐfàn.",
        ko: "나는 밥을 먹는다.",
        meaning_ko: "밥",
        meanings_extra: ["쌀밥"],
        part_of_speech: "명사"
      },
      {
        no: 57,
        word: "狗",
        word_traditional: "狗",
        pinyin: "gǒu",
        zh: "我有一只狗。",
        zh_traditional: "我有一隻狗。",
        zh_pinyin: "wǒ yǒu yī zhī gǒu.",
        ko: "나는 개 한 마리가 있다.",
        meaning_ko: "개",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 58,
        word: "猫",
        word_traditional: "貓",
        pinyin: "māo",
        zh: "她有一只猫。",
        zh_traditional: "她有一隻貓。",
        zh_pinyin: "tā yǒu yī zhī māo.",
        ko: "그녀는 고양이 한 마리가 있다.",
        meaning_ko: "고양이",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 59,
        word: "电脑",
        word_traditional: "電腦",
        pinyin: "diànnǎo",
        zh: "我有一台电脑。",
        zh_traditional: "我有一台電腦。",
        zh_pinyin: "wǒ yǒu yī tái diànnǎo.",
        ko: "나는 컴퓨터 한 대가 있다.",
        meaning_ko: "컴퓨터",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 60,
        word: "电视",
        word_traditional: "電視",
        pinyin: "diànshì",
        zh: "我看电视。",
        zh_traditional: "我看電視。",
        zh_pinyin: "wǒ kàn diànshì.",
        ko: "나는 TV를 본다.",
        meaning_ko: "텔레비전",
        meanings_extra: ["TV"],
        part_of_speech: "명사"
      },
      {
        no: 61,
        word: "电影",
        word_traditional: "電影",
        pinyin: "diànyǐng",
        zh: "我喜欢看电影。",
        zh_traditional: "我喜歡看電影。",
        zh_pinyin: "wǒ xǐhuan kàn diànyǐng.",
        ko: "나는 영화 보는 것을 좋아한다.",
        meaning_ko: "영화",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 62,
        word: "飞机",
        word_traditional: "飛機",
        pinyin: "fēijī",
        zh: "飞机很大。",
        zh_traditional: "飛機很大。",
        zh_pinyin: "fēijī hěn dà.",
        ko: "비행기는 크다.",
        meaning_ko: "비행기",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 63,
        word: "出租车",
        word_traditional: "出租車",
        pinyin: "chūzūchē",
        zh: "我坐出租车去学校。",
        zh_traditional: "我坐出租車去學校。",
        zh_pinyin: "wǒ zuò chūzūchē qù xuéxiào.",
        ko: "나는 택시를 타고 학교에 간다.",
        meaning_ko: "택시",
        meanings_extra: ["콜택시"],
        part_of_speech: "명사"
      },
      {
        no: 64,
        word: "衣服",
        word_traditional: "衣服",
        pinyin: "yīfu",
        zh: "我喜欢这件衣服。",
        zh_traditional: "我喜歡這件衣服。",
        zh_pinyin: "wǒ xǐhuan zhè jiàn yīfu.",
        ko: "나는 이 옷을 좋아한다.",
        meaning_ko: "옷",
        meanings_extra: ["의복"],
        part_of_speech: "명사"
      },
      {
        no: 65,
        word: "字",
        word_traditional: "字",
        pinyin: "zì",
        zh: "这个字很难。",
        zh_traditional: "這個字很難。",
        zh_pinyin: "zhège zì hěn nán.",
        ko: "이 글자는 어렵다.",
        meaning_ko: "글자",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 66,
        word: "钱",
        word_traditional: "錢",
        pinyin: "qián",
        zh: "我有很多钱。",
        zh_traditional: "我有很多錢。",
        zh_pinyin: "wǒ yǒu hěn duō qián.",
        ko: "나는 돈이 많다.",
        meaning_ko: "돈",
        meanings_extra: ["화폐"],
        part_of_speech: "명사"
      },
      {
        no: 67,
        word: "天气",
        word_traditional: "天氣",
        pinyin: "tiānqì",
        zh: "今天天气很好。",
        zh_traditional: "今天天氣很好。",
        zh_pinyin: "jīntiān tiānqì hěn hǎo.",
        ko: "오늘 날씨가 좋다.",
        meaning_ko: "날씨",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 68,
        word: "年",
        word_traditional: "年",
        pinyin: "nián",
        zh: "今年是二零二五年。",
        zh_traditional: "今年是二零二五年。",
        zh_pinyin: "jīnnián shì èr líng èr wǔ nián.",
        ko: "올해는 2025년이다.",
        meaning_ko: "년, 해",
        meanings_extra: ["연도"],
        part_of_speech: "명사"
      },
      {
        no: 69,
        word: "月",
        word_traditional: "月",
        pinyin: "yuè",
        zh: "我喜欢十二月。",
        zh_traditional: "我喜歡十二月。",
        zh_pinyin: "wǒ xǐhuan shí'èr yuè.",
        ko: "나는 12월을 좋아한다.",
        meaning_ko: "월, 달",
        meanings_extra: ["달"],
        part_of_speech: "명사"
      },
      {
        no: 70,
        word: "星期",
        word_traditional: "星期",
        pinyin: "xīngqī",
        zh: "星期一我去学校。",
        zh_traditional: "星期一我去學校。",
        zh_pinyin: "xīngqī yī wǒ qù xuéxiào.",
        ko: "월요일에 나는 학교에 간다.",
        meaning_ko: "요일, 주",
        meanings_extra: ["주", "요일"],
        part_of_speech: "명사"
      },
      {
        no: 71,
        word: "昨天",
        word_traditional: "昨天",
        pinyin: "zuótiān",
        zh: "昨天我去商店。",
        zh_traditional: "昨天我去商店。",
        zh_pinyin: "zuótiān wǒ qù shāngdiàn.",
        ko: "어제 나는 가게에 갔다.",
        meaning_ko: "어제",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 72,
        word: "今天",
        word_traditional: "今天",
        pinyin: "jīntiān",
        zh: "今天是星期五。",
        zh_traditional: "今天是星期五。",
        zh_pinyin: "jīntiān shì xīngqī wǔ.",
        ko: "오늘은 금요일이다.",
        meaning_ko: "오늘",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 73,
        word: "明天",
        word_traditional: "明天",
        pinyin: "míngtiān",
        zh: "明天我去学校。",
        zh_traditional: "明天我去學校。",
        zh_pinyin: "míngtiān wǒ qù xuéxiào.",
        ko: "내일 나는 학교에 간다.",
        meaning_ko: "내일",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 74,
        word: "上午",
        word_traditional: "上午",
        pinyin: "shàngwǔ",
        zh: "上午我去银行。",
        zh_traditional: "上午我去銀行。",
        zh_pinyin: "shàngwǔ wǒ qù yínháng.",
        ko: "오전 나는 은행에 간다.",
        meaning_ko: "오전",
        meanings_extra: ["아침"],
        part_of_speech: "명사"
      },
      {
        no: 75,
        word: "中午",
        word_traditional: "中午",
        pinyin: "zhōngwǔ",
        zh: "中午我们吃饭。",
        zh_traditional: "中午我們吃飯。",
        zh_pinyin: "zhōngwǔ wǒmen chīfàn.",
        ko: "정오에 우리는 밥을 먹는다.",
        meaning_ko: "정오, 점심",
        meanings_extra: ["낮"],
        part_of_speech: "명사"
      },
      {
        no: 76,
        word: "下午",
        word_traditional: "下午",
        pinyin: "xiàwǔ",
        zh: "下午我要去图书馆。",
        zh_traditional: "下午我要去圖書館。",
        zh_pinyin: "xiàwǔ wǒ yào qù túshūguǎn.",
        ko: "오후에 나는 도서관에 갈 것이다.",
        meaning_ko: "오후",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 77,
        word: "上",
        word_traditional: "上",
        pinyin: "shàng",
        zh: "我上课了。",
        zh_traditional: "我上課了。",
        zh_pinyin: "wǒ shàng kè le.",
        ko: "나는 수업에 들어갔다.",
        meaning_ko: "위, 올라가다",
        meanings_extra: ["위에", "오르다"],
        part_of_speech: "동사/명사"
      },
      {
        no: 78,
        word: "下",
        word_traditional: "下",
        pinyin: "xià",
        zh: "他下楼了。",
        zh_traditional: "他下樓了。",
        zh_pinyin: "tā xià lóu le.",
        ko: "그는 아래층으로 내려갔다.",
        meaning_ko: "아래, 내리다",
        meanings_extra: ["아래에", "내려가다"],
        part_of_speech: "동사/명사"
      },
      {
        no: 79,
        word: "前面",
        word_traditional: "前面",
        pinyin: "qiánmiàn",
        zh: "学校在前面。",
        zh_traditional: "學校在前面。",
        zh_pinyin: "xuéxiào zài qiánmiàn.",
        ko: "학교가 앞에 있다.",
        meaning_ko: "앞, 앞쪽",
        meanings_extra: ["앞부분"],
        part_of_speech: "명사"
      },
      {
        no: 80,
        word: "后面",
        word_traditional: "後面",
        pinyin: "hòumiàn",
        zh: "车站在后面。",
        zh_traditional: "車站在後面。",
        zh_pinyin: "chēzhàn zài hòumiàn.",
        ko: "역이 뒤에 있다.",
        meaning_ko: "뒤, 뒤쪽",
        meanings_extra: ["뒷부분"],
        part_of_speech: "명사"
      },
      {
        no: 81,
        word: "现在",
        word_traditional: "現在",
        pinyin: "xiànzài",
        zh: "我现在在家。",
        zh_traditional: "我現在在家。",
        zh_pinyin: "wǒ xiànzài zài jiā.",
        ko: "나는 지금 집에 있다.",
        meaning_ko: "지금",
        meanings_extra: ["현재", "지금 이 순간"],
        part_of_speech: "명사"
      },
      {
        no: 82,
        word: "点",
        word_traditional: "點",
        pinyin: "diǎn",
        zh: "现在三点。",
        zh_traditional: "現在三點。",
        zh_pinyin: "xiànzài sān diǎn.",
        ko: "지금 세 시다.",
        meaning_ko: "시 (시간 단위)",
        meanings_extra: ["점", "시간"],
        part_of_speech: "명사"
      },
      {
        no: 83,
        word: "分钟",
        word_traditional: "分鐘",
        pinyin: "fēnzhōng",
        zh: "我等了十分钟。",
        zh_traditional: "我等了十分鐘。",
        zh_pinyin: "wǒ děngle shí fēnzhōng.",
        ko: "나는 10분 동안 기다렸다.",
        meaning_ko: "분 (시간 단위)",
        meanings_extra: ["분"],
        part_of_speech: "명사"
      },
      {
        no: 84,
        word: "时候",
        word_traditional: "時候",
        pinyin: "shíhou",
        zh: "你什么时候去？",
        zh_traditional: "你什麼時候去？",
        zh_pinyin: "nǐ shénme shíhou qù?",
        ko: "너 언제 가니?",
        meaning_ko: "때, 시간",
        meanings_extra: ["시기", "순간"],
        part_of_speech: "명사"
      },
      {
        no: 85,
        word: "谁",
        word_traditional: "誰",
        pinyin: "shéi",
        zh: "他是谁？",
        zh_traditional: "他是誰？",
        zh_pinyin: "tā shì shéi?",
        ko: "그는 누구인가?",
        meaning_ko: "누구",
        meanings_extra: ["어느 사람"],
        part_of_speech: "대명사"
      },
      {
        no: 86,
        word: "哪",
        word_traditional: "哪",
        pinyin: "nǎ",
        zh: "你去哪儿？",
        zh_traditional: "你去哪兒？",
        zh_pinyin: "nǐ qù nǎr?",
        ko: "너 어디 가니?",
        meaning_ko: "어느, 어디",
        meanings_extra: ["어디서"],
        part_of_speech: "대명사"
      },
      {
        no: 87,
        word: "什么",
        word_traditional: "什麼",
        pinyin: "shénme",
        zh: "这是什么？",
        zh_traditional: "這是什麼？",
        zh_pinyin: "zhè shì shénme?",
        ko: "이게 뭐야?",
        meaning_ko: "무엇",
        meanings_extra: ["뭐"],
        part_of_speech: "대명사"
      },
      {
        no: 88,
        word: "怎么",
        word_traditional: "怎麼",
        pinyin: "zěnme",
        zh: "你怎么去？",
        zh_traditional: "你怎麼去？",
        zh_pinyin: "nǐ zěnme qù?",
        ko: "너 어떻게 가니?",
        meaning_ko: "어떻게",
        meanings_extra: ["어째서"],
        part_of_speech: "부사"
      },
      {
        no: 89,
        word: "怎么样",
        word_traditional: "怎麼樣",
        pinyin: "zěnmeyàng",
        zh: "这个菜怎么样？",
        zh_traditional: "這個菜怎麼樣？",
        zh_pinyin: "zhège cài zěnmeyàng?",
        ko: "이 음식 어때?",
        meaning_ko: "어때?",
        meanings_extra: ["어떠니"],
        part_of_speech: "부사"
      },
      {
        no: 90,
        word: "多",
        word_traditional: "多",
        pinyin: "duō",
        zh: "你有多少钱？",
        zh_traditional: "你有多少錢？",
        zh_pinyin: "nǐ yǒu duōshao qián?",
        ko: "너는 돈이 얼마나 있니?",
        meaning_ko: "많다",
        meanings_extra: ["얼마나"],
        part_of_speech: "형용사/부사"
      },
      {
        no: 91,
        word: "读",
        word_traditional: "讀",
        pinyin: "dú",
        zh: "我读书。",
        zh_traditional: "我讀書。",
        zh_pinyin: "wǒ dú shū.",
        ko: "나는 책을 읽는다.",
        meaning_ko: "읽다",
        meanings_extra: ["공부하다"],
        part_of_speech: "동사"
      },
      {
        no: 92,
        word: "买",
        word_traditional: "買",
        pinyin: "mǎi",
        zh: "我买水果。",
        zh_traditional: "我買水果。",
        zh_pinyin: "wǒ mǎi shuǐguǒ.",
        ko: "나는 과일을 산다.",
        meaning_ko: "사다",
        meanings_extra: [],
        part_of_speech: "동사"
      },
      {
        no: 93,
        word: "来",
        word_traditional: "來",
        pinyin: "lái",
        zh: "他来了。",
        zh_traditional: "他來了。",
        zh_pinyin: "tā lái le.",
        ko: "그가 왔다.",
        meaning_ko: "오다",
        meanings_extra: [],
        part_of_speech: "동사"
      },
      {
        no: 94,
        word: "去",
        word_traditional: "去",
        pinyin: "qù",
        zh: "我去学校。",
        zh_traditional: "我去學校。",
        zh_pinyin: "wǒ qù xuéxiào.",
        ko: "나는 학교에 간다.",
        meaning_ko: "가다",
        meanings_extra: [],
        part_of_speech: "동사"
      },
      {
        no: 95,
        word: "住",
        word_traditional: "住",
        pinyin: "zhù",
        zh: "我住在北京。",
        zh_traditional: "我住在北京。",
        zh_pinyin: "wǒ zhù zài Běijīng.",
        ko: "나는 베이징에 산다.",
        meaning_ko: "살다",
        meanings_extra: [],
        part_of_speech: "동사"
      },
      {
        no: 96,
        word: "叫",
        word_traditional: "叫",
        pinyin: "jiào",
        zh: "我叫李华。",
        zh_traditional: "我叫李華。",
        zh_pinyin: "wǒ jiào Lǐ Huá.",
        ko: "나는 리화라고 불린다.",
        meaning_ko: "부르다",
        meanings_extra: ["이름이 ~이다"],
        part_of_speech: "동사"
      },
      {
        no: 97,
        word: "做",
        word_traditional: "做",
        pinyin: "zuò",
        zh: "我做饭。",
        zh_traditional: "我做飯。",
        zh_pinyin: "wǒ zuò fàn.",
        ko: "나는 밥을 만든다.",
        meaning_ko: "하다, 만들다",
        meanings_extra: [],
        part_of_speech: "동사"
      },
      {
        no: 98,
        word: "爱",
        word_traditional: "愛",
        pinyin: "ài",
        zh: "我爱你。",
        zh_traditional: "我愛你。",
        zh_pinyin: "wǒ ài nǐ.",
        ko: "나는 너를 사랑한다.",
        meaning_ko: "사랑하다",
        meanings_extra: ["좋아하다"],
        part_of_speech: "동사"
      },
      {
        no: 99,
        word: "回",
        word_traditional: "回",
        pinyin: "huí",
        zh: "我回家。",
        zh_traditional: "我回家。",
        zh_pinyin: "wǒ huí jiā.",
        ko: "나는 집에 돌아간다.",
        meaning_ko: "돌아오다",
        meanings_extra: ["돌아가다"],
        part_of_speech: "동사"
      },
      {
        no: 100,
        word: "坐",
        word_traditional: "坐",
        pinyin: "zuò",
        zh: "我坐车去学校。",
        zh_traditional: "我坐車去學校。",
        zh_pinyin: "wǒ zuò chē qù xuéxiào.",
        ko: "나는 차를 타고 학교에 간다.",
        meaning_ko: "앉다, 타다",
        meanings_extra: ["타다(교통수단)"],
        part_of_speech: "동사"
      },
      {
        no: 101,
        word: "开",
        word_traditional: "開",
        pinyin: "kāi",
        zh: "我开车去上班。",
        zh_traditional: "我開車去上班。",
        zh_pinyin: "wǒ kāichē qù shàngbān.",
        ko: "나는 차를 운전해서 출근한다.",
        meaning_ko: "열다, 운전하다",
        meanings_extra: ["켜다"],
        part_of_speech: "동사"
      },
      {
        no: 102,
        word: "请",
        word_traditional: "請",
        pinyin: "qǐng",
        zh: "请坐。",
        zh_traditional: "請坐。",
        zh_pinyin: "qǐng zuò.",
        ko: "앉으세요.",
        meaning_ko: "부탁하다, 초대하다",
        meanings_extra: ["제발"],
        part_of_speech: "동사/부사"
      },
      {
        no: 103,
        word: "看见",
        word_traditional: "看見",
        pinyin: "kànjiàn",
        zh: "我看见他了。",
        zh_traditional: "我看見他了。",
        zh_pinyin: "wǒ kànjiàn tā le.",
        ko: "나는 그를 보았다.",
        meaning_ko: "보다, 목격하다",
        meanings_extra: ["눈에 띄다"],
        part_of_speech: "동사"
      },
      {
        no: 104,
        word: "学习",
        word_traditional: "學習",
        pinyin: "xuéxí",
        zh: "我学习汉语。",
        zh_traditional: "我學習漢語。",
        zh_pinyin: "wǒ xuéxí Hànyǔ.",
        ko: "나는 중국어를 공부한다.",
        meaning_ko: "공부하다, 배우다",
        meanings_extra: ["학습하다"],
        part_of_speech: "동사"
      },
      {
        no: 105,
        word: "工作",
        word_traditional: "工作",
        pinyin: "gōngzuò",
        zh: "他工作很忙。",
        zh_traditional: "他工作很忙。",
        zh_pinyin: "tā gōngzuò hěn máng.",
        ko: "그는 일이 매우 바쁘다.",
        meaning_ko: "일하다, 일",
        meanings_extra: ["직업"],
        part_of_speech: "동사/명사"
      },
      {
        no: 106,
        word: "认识",
        word_traditional: "認識",
        pinyin: "rènshi",
        zh: "我认识他。",
        zh_traditional: "我認識他。",
        zh_pinyin: "wǒ rènshi tā.",
        ko: "나는 그를 안다.",
        meaning_ko: "알다, 인식하다",
        meanings_extra: ["만나다"],
        part_of_speech: "동사"
      },
      {
        no: 107,
        word: "喜欢",
        word_traditional: "喜歡",
        pinyin: "xǐhuan",
        zh: "我喜欢吃苹果。",
        zh_traditional: "我喜歡吃蘋果。",
        zh_pinyin: "wǒ xǐhuan chī píngguǒ.",
        ko: "나는 사과 먹는 것을 좋아한다.",
        meaning_ko: "좋아하다",
        meanings_extra: ["사랑하다"],
        part_of_speech: "동사"
      },
      {
        no: 108,
        word: "睡觉",
        word_traditional: "睡覺",
        pinyin: "shuìjiào",
        zh: "我晚上十点睡觉。",
        zh_traditional: "我晚上十點睡覺。",
        zh_pinyin: "wǒ wǎnshàng shí diǎn shuìjiào.",
        ko: "나는 밤 10시에 잠잔다.",
        meaning_ko: "잠을 자다",
        meanings_extra: [],
        part_of_speech: "동사"
      },
      {
        no: 109,
        word: "好",
        word_traditional: "好",
        pinyin: "hǎo",
        zh: "今天的天气很好。",
        zh_traditional: "今天的天氣很好。",
        zh_pinyin: "jīntiān de tiānqì hěn hǎo.",
        ko: "오늘 날씨가 좋다.",
        meaning_ko: "좋다",
        meanings_extra: ["괜찮다", "건강하다"],
        part_of_speech: "형용사"
      },
      {
        no: 110,
        word: "冷",
        word_traditional: "冷",
        pinyin: "lěng",
        zh: "冬天很冷。",
        zh_traditional: "冬天很冷。",
        zh_pinyin: "dōngtiān hěn lěng.",
        ko: "겨울은 매우 춥다.",
        meaning_ko: "춥다",
        meanings_extra: [],
        part_of_speech: "형용사"
      },
      {
        no: 111,
        word: "热",
        word_traditional: "熱",
        pinyin: "rè",
        zh: "夏天很热。",
        zh_traditional: "夏天很熱。",
        zh_pinyin: "xiàtiān hěn rè.",
        ko: "여름은 매우 덥다.",
        meaning_ko: "덥다",
        meanings_extra: ["뜨겁다"],
        part_of_speech: "형용사"
      },
      {
        no: 112,
        word: "高兴",
        word_traditional: "高興",
        pinyin: "gāoxìng",
        zh: "我很高兴见到你。",
        zh_traditional: "我很高興見到你。",
        zh_pinyin: "wǒ hěn gāoxìng jiàn dào nǐ.",
        ko: "나는 너를 만나서 매우 기쁘다.",
        meaning_ko: "기쁘다",
        meanings_extra: ["즐겁다"],
        part_of_speech: "형용사"
      },
      {
        no: 113,
        word: "漂亮",
        word_traditional: "漂亮",
        pinyin: "piàoliang",
        zh: "她很漂亮。",
        zh_traditional: "她很漂亮。",
        zh_pinyin: "tā hěn piàoliang.",
        ko: "그녀는 매우 예쁘다.",
        meaning_ko: "예쁘다",
        meanings_extra: ["아름답다"],
        part_of_speech: "형용사"
      },
      {
        no: 114,
        word: "下雨",
        word_traditional: "下雨",
        pinyin: "xiàyǔ",
        zh: "今天下雨了。",
        zh_traditional: "今天下雨了。",
        zh_pinyin: "jīntiān xià yǔ le.",
        ko: "오늘 비가 왔다.",
        meaning_ko: "비가 오다",
        meanings_extra: [],
        part_of_speech: "동사"
      },
      {
        no: 115,
        word: "不",
        word_traditional: "不",
        pinyin: "bù",
        zh: "我不是学生。",
        zh_traditional: "我不是學生。",
        zh_pinyin: "wǒ bú shì xuésheng.",
        ko: "나는 학생이 아니다.",
        meaning_ko: "아니다, ~않다",
        meanings_extra: ["부정"],
        part_of_speech: "부사"
      },
      {
        no: 116,
        word: "没",
        word_traditional: "沒",
        pinyin: "méi",
        zh: "我没钱。",
        zh_traditional: "我沒錢。",
        zh_pinyin: "wǒ méi qián.",
        ko: "나는 돈이 없다.",
        meaning_ko: "~않다 (과거, 현재)",
        meanings_extra: ["없다"],
        part_of_speech: "부사"
      },
      {
        no: 117,
        word: "很",
        word_traditional: "很",
        pinyin: "hěn",
        zh: "他很高。",
        zh_traditional: "他很高。",
        zh_pinyin: "tā hěn gāo.",
        ko: "그는 키가 크다.",
        meaning_ko: "매우",
        meanings_extra: ["아주"],
        part_of_speech: "부사"
      },
      {
        no: 118,
        word: "太",
        word_traditional: "太",
        pinyin: "tài",
        zh: "天气太热了。",
        zh_traditional: "天氣太熱了。",
        zh_pinyin: "tiānqì tài rè le.",
        ko: "날씨가 너무 덥다.",
        meaning_ko: "너무",
        meanings_extra: ["아주"],
        part_of_speech: "부사"
      },
      {
        no: 119,
        word: "都",
        word_traditional: "都",
        pinyin: "dōu",
        zh: "我们都去学校。",
        zh_traditional: "我們都去學校。",
        zh_pinyin: "wǒmen dōu qù xuéxiào.",
        ko: "우리는 모두 학교에 간다.",
        meaning_ko: "모두",
        meanings_extra: ["전부"],
        part_of_speech: "부사"
      },
      {
        no: 120,
        word: "在",
        word_traditional: "在",
        pinyin: "zài",
        zh: "我在家。",
        zh_traditional: "我在家。",
        zh_pinyin: "wǒ zài jiā.",
        ko: "나는 집에 있다.",
        meaning_ko: "~에 있다",
        meanings_extra: ["~에 위치하다"],
        part_of_speech: "전치사/동사"
      },
      {
        no: 121,
        word: "和",
        word_traditional: "和",
        pinyin: "hé",
        zh: "我和你是朋友。",
        zh_traditional: "我和你是朋友。",
        zh_pinyin: "wǒ hé nǐ shì péngyou.",
        ko: "나는 너와 친구이다.",
        meaning_ko: "와, 그리고",
        meanings_extra: ["함께", "더불어"],
        part_of_speech: "접속사"
      },
      {
        no: 122,
        word: "里",
        word_traditional: "裡",
        pinyin: "lǐ",
        zh: "书包里有书。",
        zh_traditional: "書包裡有書。",
        zh_pinyin: "shūbāo lǐ yǒu shū.",
        ko: "책가방 안에 책이 있다.",
        meaning_ko: "안",
        meanings_extra: ["속"],
        part_of_speech: "명사/전치사"
      },
      {
        no: 123,
        word: "这",
        word_traditional: "這",
        pinyin: "zhè",
        zh: "这是我的书。",
        zh_traditional: "這是我的書。",
        zh_pinyin: "zhè shì wǒ de shū.",
        ko: "이것은 내 책이다.",
        meaning_ko: "이것",
        meanings_extra: ["이"],
        part_of_speech: "대명사"
      },
      {
        no: 124,
        word: "那",
        word_traditional: "那",
        pinyin: "nà",
        zh: "那是你的杯子。",
        zh_traditional: "那是你的杯子。",
        zh_pinyin: "nà shì nǐ de bēizi.",
        ko: "저것은 너의 컵이다.",
        meaning_ko: "저것",
        meanings_extra: ["저"],
        part_of_speech: "대명사"
      },
      {
        no: 125,
        word: "的",
        word_traditional: "的",
        pinyin: "de",
        zh: "这是我的书。",
        zh_traditional: "這是我的書。",
        zh_pinyin: "zhè shì wǒ de shū.",
        ko: "이것은 내 책이다.",
        meaning_ko: "~의 (소유격)",
        meanings_extra: ["~한 (한정)"],
        part_of_speech: "조사"
      },
      {
        no: 126,
        word: "了",
        word_traditional: "了",
        pinyin: "le",
        zh: "我吃了饭。",
        zh_traditional: "我吃了飯。",
        zh_pinyin: "wǒ chī le fàn.",
        ko: "나는 밥을 먹었다.",
        meaning_ko: "완료 표시",
        meanings_extra: ["변화 표시"],
        part_of_speech: "조사"
      },
      {
        no: 127,
        word: "吗",
        word_traditional: "嗎",
        pinyin: "ma",
        zh: "你好吗？",
        zh_traditional: "你好嗎？",
        zh_pinyin: "nǐ hǎo ma?",
        ko: "잘 지내니?",
        meaning_ko: "의문문 어기조사",
        meanings_extra: ["~입니까?"],
        part_of_speech: "조사"
      },
      {
        no: 128,
        word: "呢",
        word_traditional: "呢",
        pinyin: "ne",
        zh: "你呢？",
        zh_traditional: "你呢？",
        zh_pinyin: "nǐ ne?",
        ko: "너는?",
        meaning_ko: "의문문 어기조사",
        meanings_extra: ["~은(는)?"],
        part_of_speech: "조사"
      },
      {
        no: 129,
        word: "喂",
        word_traditional: "喂",
        pinyin: "wèi",
        zh: "喂，你好！",
        zh_traditional: "喂，你好！",
        zh_pinyin: "wèi, nǐ hǎo!",
        ko: "여보세요, 안녕하세요!",
        meaning_ko: "여보세요",
        meanings_extra: ["야! (호칭)"],
        part_of_speech: "감탄사"
      },
      {
        no: 130,
        word: "谢谢",
        word_traditional: "謝謝",
        pinyin: "xièxie",
        zh: "谢谢你。",
        zh_traditional: "謝謝你。",
        zh_pinyin: "xièxie nǐ.",
        ko: "고마워.",
        meaning_ko: "감사합니다",
        meanings_extra: ["고맙다"],
        part_of_speech: "상투어"
      },
      {
        no: 131,
        word: "不客气",
        word_traditional: "不客氣",
        pinyin: "búkèqi",
        zh: "不客气。",
        zh_traditional: "不客氣。",
        zh_pinyin: "búkèqi.",
        ko: "천만에요.",
        meaning_ko: "천만에요",
        meanings_extra: ["별 말씀을요"],
        part_of_speech: "상투어"
      },
      {
        no: 132,
        word: "对不起",
        word_traditional: "對不起",
        pinyin: "duìbuqǐ",
        zh: "对不起。",
        zh_traditional: "對不起。",
        zh_pinyin: "duìbuqǐ.",
        ko: "미안합니다.",
        meaning_ko: "미안합니다",
        meanings_extra: ["죄송합니다"],
        part_of_speech: "상투어"
      },
      {
        no: 133,
        word: "没关系",
        word_traditional: "沒關係",
        pinyin: "méiguanxi",
        zh: "没关系。",
        zh_traditional: "沒關係。",
        zh_pinyin: "méiguanxi.",
        ko: "괜찮아요.",
        meaning_ko: "괜찮다",
        meanings_extra: ["상관없다"],
        part_of_speech: "상투어"
      },
      {
        no: 134,
        word: "再见",
        word_traditional: "再見",
        pinyin: "zàijiàn",
        zh: "再见！",
        zh_traditional: "再見！",
        zh_pinyin: "zàijiàn!",
        ko: "안녕히 가세요!",
        meaning_ko: "안녕",
        meanings_extra: ["잘 가", "또 봐"],
        part_of_speech: "상투어"
      },
      {
        no: 135,
        word: "打电话",
        word_traditional: "打電話",
        pinyin: "dǎ diànhuà",
        zh: "我给你打电话。",
        zh_traditional: "我給你打電話。",
        zh_pinyin: "wǒ gěi nǐ dǎ diànhuà.",
        ko: "내가 너에게 전화할게.",
        meaning_ko: "전화하다",
        meanings_extra: ["통화하다"],
        part_of_speech: "동사구"
      },
      {
        no: 136,
        word: "爱",
        word_traditional: "愛",
        pinyin: "ài",
        zh: "我爱我的家。",
        zh_traditional: "我愛我的家。",
        zh_pinyin: "wǒ ài wǒ de jiā.",
        ko: "나는 나의 집을 사랑한다.",
        meaning_ko: "사랑하다",
        meanings_extra: ["좋아하다"],
        part_of_speech: "동사"
      },
      {
        no: 137,
        word: "做",
        word_traditional: "做",
        pinyin: "zuò",
        zh: "我做作业。",
        zh_traditional: "我做作業。",
        zh_pinyin: "wǒ zuò zuòyè.",
        ko: "나는 숙제를 한다.",
        meaning_ko: "하다, 만들다",
        meanings_extra: ["수행하다"],
        part_of_speech: "동사"
      },
      {
        no: 138,
        word: "叫",
        word_traditional: "叫",
        pinyin: "jiào",
        zh: "他叫王老师。",
        zh_traditional: "他叫王老師。",
        zh_pinyin: "tā jiào Wáng lǎoshī.",
        ko: "그는 왕 선생님이라고 불린다.",
        meaning_ko: "부르다, 이름이 ~이다",
        meanings_extra: [],
        part_of_speech: "동사"
      },
      {
        no: 139,
        word: "住",
        word_traditional: "住",
        pinyin: "zhù",
        zh: "我住在学校附近。",
        zh_traditional: "我住在學校附近。",
        zh_pinyin: "wǒ zhù zài xuéxiào fùjìn.",
        ko: "나는 학교 근처에 산다.",
        meaning_ko: "살다",
        meanings_extra: [],
        part_of_speech: "동사"
      },
      {
        no: 140,
        word: "去",
        word_traditional: "去",
        pinyin: "qù",
        zh: "我们去商店。",
        zh_traditional: "我們去商店。",
        zh_pinyin: "wǒmen qù shāngdiàn.",
        ko: "우리는 가게에 간다.",
        meaning_ko: "가다",
        meanings_extra: [],
        part_of_speech: "동사"
      },
      {
        no: 141,
        word: "了",
        word_traditional: "了",
        pinyin: "le",
        zh: "我吃了饭。",
        zh_traditional: "我吃了飯。",
        zh_pinyin: "wǒ chī le fàn.",
        ko: "나는 밥을 먹었다.",
        meaning_ko: "완료 표시",
        meanings_extra: ["변화 표시"],
        part_of_speech: "조사"
      },
      {
        no: 142,
        word: "吗",
        word_traditional: "嗎",
        pinyin: "ma",
        zh: "你好吗？",
        zh_traditional: "你好嗎？",
        zh_pinyin: "nǐ hǎo ma?",
        ko: "잘 지내니?",
        meaning_ko: "의문문 어기조사",
        meanings_extra: ["~입니까?"],
        part_of_speech: "조사"
      },
      {
        no: 143,
        word: "呢",
        word_traditional: "呢",
        pinyin: "ne",
        zh: "你呢？",
        zh_traditional: "你呢？",
        zh_pinyin: "nǐ ne?",
        ko: "너는?",
        meaning_ko: "의문문 어기조사",
        meanings_extra: ["~은(는)?"],
        part_of_speech: "조사"
      },
      {
        no: 144,
        word: "喂",
        word_traditional: "喂",
        pinyin: "wèi",
        zh: "喂，你好！",
        zh_traditional: "喂，你好！",
        zh_pinyin: "wèi, nǐ hǎo!",
        ko: "여보세요, 안녕하세요!",
        meaning_ko: "여보세요",
        meanings_extra: ["야! (호칭)"],
        part_of_speech: "감탄사"
      },
      {
        no: 145,
        word: "谢谢",
        word_traditional: "謝謝",
        pinyin: "xièxie",
        zh: "谢谢你。",
        zh_traditional: "謝謝你。",
        zh_pinyin: "xièxie nǐ.",
        ko: "고마워.",
        meaning_ko: "감사합니다",
        meanings_extra: ["고맙다"],
        part_of_speech: "상투어"
      },
      {
        no: 146,
        word: "不客气",
        word_traditional: "不客氣",
        pinyin: "búkèqi",
        zh: "不客气。",
        zh_traditional: "不客氣。",
        zh_pinyin: "búkèqi.",
        ko: "천만에요.",
        meaning_ko: "천만에요",
        meanings_extra: ["별 말씀을요"],
        part_of_speech: "상투어"
      },
      {
        no: 147,
        word: "对不起",
        word_traditional: "對不起",
        pinyin: "duìbuqǐ",
        zh: "对不起。",
        zh_traditional: "對不起。",
        zh_pinyin: "duìbuqǐ.",
        ko: "미안합니다.",
        meaning_ko: "미안합니다",
        meanings_extra: ["죄송합니다"],
        part_of_speech: "상투어"
      },
      {
        no: 148,
        word: "没关系",
        word_traditional: "沒關係",
        pinyin: "méiguanxi",
        zh: "没关系。",
        zh_traditional: "沒關係。",
        zh_pinyin: "méiguanxi.",
        ko: "괜찮아요.",
        meaning_ko: "괜찮다",
        meanings_extra: ["상관없다"],
        part_of_speech: "상투어"
      },
      {
        no: 149,
        word: "再见",
        word_traditional: "再見",
        pinyin: "zàijiàn",
        zh: "再见！",
        zh_traditional: "再見！",
        zh_pinyin: "zàijiàn!",
        ko: "안녕히 가세요!",
        meaning_ko: "안녕",
        meanings_extra: ["잘 가", "또 봐"],
        part_of_speech: "상투어"
      },
      {
        no: 150,
        word: "打电话",
        word_traditional: "打電話",
        pinyin: "dǎ diànhuà",
        zh: "我给你打电话。",
        zh_traditional: "我給你打電話。",
        zh_pinyin: "wǒ gěi nǐ dǎ diànhuà.",
        ko: "내가 너에게 전화할게.",
        meaning_ko: "전화하다",
        meanings_extra: ["통화하다"],
        part_of_speech: "동사구"
      }
  ]
  