const quizList = [
    {
      no: 1,
      word: "阿姨",
      word_traditional: "阿姨",
      pinyin: "āyí",
      zh: "阿姨是我妈妈的朋友。",
      zh_traditional: "阿姨是我媽媽的朋友。",
      zh_pinyin: "āyí shì wǒ māma de péngyou.",
      ko: "아줌마는 우리 엄마의 친구이다.",
      meaning_ko: "아줌마, 아주머니 (엄마 또래 여성)",
      meanings_extra: ["이모"],
      part_of_speech: "명사"
    },
    {
      no: 2,
      word: "啊",
      word_traditional: "啊",
      pinyin: "a",
      zh: "你好啊！",
      zh_traditional: "你好啊！",
      zh_pinyin: "nǐ hǎo a!",
      ko: "안녕!",
      meaning_ko: "아!, 어! (감탄사)",
      meanings_extra: ["~야 (어기조사)"],
      part_of_speech: "감탄사"
    },
    {
      no: 3,
      word: "矮",
      word_traditional: "矮",
      pinyin: "ǎi",
      zh: "他很矮。",
      zh_traditional: "他很矮。",
      zh_pinyin: "tā hěn ǎi.",
      ko: "그는 키가 작다.",
      meaning_ko: "키가 작다, 낮다",
      meanings_extra: [],
      part_of_speech: "형용사"
    },
    {
      no: 4,
      word: "爱好",
      word_traditional: "愛好",
      pinyin: "àihào",
      zh: "我的爱好是看书。",
      zh_traditional: "我的愛好是看書。",
      zh_pinyin: "wǒ de àihào shì kàn shū.",
      ko: "내 취미는 책 읽기이다.",
      meaning_ko: "취미",
      meanings_extra: ["좋아하는 것"],
      part_of_speech: "명사"
    },
    {
      no: 5,
      word: "安静",
      word_traditional: "安靜",
      pinyin: "ānjìng",
      zh: "请安静。",
      zh_traditional: "請安靜。",
      zh_pinyin: "qǐng ānjìng.",
      ko: "조용히 해 주세요.",
      meaning_ko: "조용하다",
      meanings_extra: ["평화롭다"],
      part_of_speech: "형용사"
    },
    {
      no: 6,
      word: "把",
      word_traditional: "把",
      pinyin: "bǎ",
      zh: "请把书给我。",
      zh_traditional: "請把書給我。",
      zh_pinyin: "qǐng bǎ shū gěi wǒ.",
      ko: "책을 내게 주세요.",
      meaning_ko: "~을 (조사, 처리대상 표시)",
      meanings_extra: ["잡다", "가지고 있다"],
      part_of_speech: "조사/동사"
    },
    {
      no: 7,
      word: "班",
      word_traditional: "班",
      pinyin: "bān",
      zh: "我在一个班。",
      zh_traditional: "我在一個班。",
      zh_pinyin: "wǒ zài yí gè bān.",
      ko: "나는 한 반에 있다.",
      meaning_ko: "학급, 반",
      meanings_extra: ["근무조"],
      part_of_speech: "명사"
    },
    {
      no: 8,
      word: "搬",
      word_traditional: "搬",
      pinyin: "bān",
      zh: "我们要搬家了。",
      zh_traditional: "我們要搬家了。",
      zh_pinyin: "wǒmen yào bān jiā le.",
      ko: "우리는 이사할 것이다.",
      meaning_ko: "옮기다, 이사하다",
      meanings_extra: [],
      part_of_speech: "동사"
    },
    {
      no: 9,
      word: "半",
      word_traditional: "半",
      pinyin: "bàn",
      zh: "现在是两点半。",
      zh_traditional: "現在是兩點半。",
      zh_pinyin: "xiànzài shì liǎng diǎn bàn.",
      ko: "지금은 2시 반이다.",
      meaning_ko: "반, 절반",
      meanings_extra: ["중간"],
      part_of_speech: "명사/형용사"
    },
    {
      no: 10,
      word: "办法",
      word_traditional: "辦法",
      pinyin: "bànfǎ",
      zh: "我有一个办法。",
      zh_traditional: "我有一個辦法。",
      zh_pinyin: "wǒ yǒu yí gè bànfǎ.",
      ko: "나는 방법이 하나 있다.",
      meaning_ko: "방법",
      meanings_extra: ["수단", "방책"],
      part_of_speech: "명사"
    },
    {
      no: 11,
      word: "办公室",
      word_traditional: "辦公室",
      pinyin: "bàngōngshì",
      zh: "他在办公室工作。",
      zh_traditional: "他在辦公室工作。",
      zh_pinyin: "tā zài bàngōngshì gōngzuò.",
      ko: "그는 사무실에서 일한다.",
      meaning_ko: "사무실",
      meanings_extra: [],
      part_of_speech: "명사"
    },
    {
      no: 12,
      word: "帮忙",
      word_traditional: "幫忙",
      pinyin: "bāngmáng",
      zh: "请帮忙我一下。",
      zh_traditional: "請幫忙我一下。",
      zh_pinyin: "qǐng bāngmáng wǒ yíxià.",
      ko: "저 좀 도와주세요.",
      meaning_ko: "도와주다",
      meanings_extra: ["도움"],
      part_of_speech: "동사"
    },
    {
      no: 13,
      word: "包",
      word_traditional: "包",
      pinyin: "bāo",
      zh: "这是我的包。",
      zh_traditional: "這是我的包。",
      zh_pinyin: "zhè shì wǒ de bāo.",
      ko: "이것은 내 가방이다.",
      meaning_ko: "가방, 싸다",
      meanings_extra: ["포장하다"],
      part_of_speech: "명사/동사"
    },
    {
      no: 14,
      word: "饱",
      word_traditional: "飽",
      pinyin: "bǎo",
      zh: "我吃饱了。",
      zh_traditional: "我吃飽了。",
      zh_pinyin: "wǒ chī bǎo le.",
      ko: "나는 배부르다.",
      meaning_ko: "배부르다",
      meanings_extra: [],
      part_of_speech: "형용사"
    },
    {
      no: 15,
      word: "北方",
      word_traditional: "北方",
      pinyin: "běifāng",
      zh: "北方很冷。",
      zh_traditional: "北方很冷。",
      zh_pinyin: "běifāng hěn lěng.",
      ko: "북쪽은 매우 춥다.",
      meaning_ko: "북쪽",
      meanings_extra: [],
      part_of_speech: "명사"
    },
    {
      no: 16,
      word: "被",
      word_traditional: "被",
      pinyin: "bèi",
      zh: "他被老师批评了。",
      zh_traditional: "他被老師批評了。",
      zh_pinyin: "tā bèi lǎoshī pīpíng le.",
      ko: "그는 선생님에게 꾸중을 들었다.",
      meaning_ko: "~에 의해 (수동태 표시)",
      meanings_extra: [],
      part_of_speech: "전치사"
    },
    {
      no: 17,
      word: "鼻子",
      word_traditional: "鼻子",
      pinyin: "bízi",
      zh: "他的鼻子很大。",
      zh_traditional: "他的鼻子很大。",
      zh_pinyin: "tā de bízi hěn dà.",
      ko: "그의 코가 크다.",
      meaning_ko: "코",
      meanings_extra: [],
      part_of_speech: "명사"
    },
    {
      no: 18,
      word: "比较",
      word_traditional: "比較",
      pinyin: "bǐjiào",
      zh: "今天比较冷。",
      zh_traditional: "今天比較冷。",
      zh_pinyin: "jīntiān bǐjiào lěng.",
      ko: "오늘은 좀 더 춥다.",
      meaning_ko: "비교하다, 좀",
      meanings_extra: ["비교적"],
      part_of_speech: "부사/동사"
    },
    {
      no: 19,
      word: "比赛",
      word_traditional: "比賽",
      pinyin: "bǐsài",
      zh: "他们在比赛。",
      zh_traditional: "他們在比賽。",
      zh_pinyin: "tāmen zài bǐsài.",
      ko: "그들은 경기를 하고 있다.",
      meaning_ko: "경기, 시합",
      meanings_extra: ["경쟁"],
      part_of_speech: "명사/동사"
    },
    {
      no: 20,
      word: "笔记本",
      word_traditional: "筆記本",
      pinyin: "bǐjìběn",
      zh: "我有一个笔记本。",
      zh_traditional: "我有一個筆記本。",
      zh_pinyin: "wǒ yǒu yí gè bǐjìběn.",
      ko: "나는 노트북 하나가 있다.",
      meaning_ko: "노트북, 공책",
      meanings_extra: [],
      part_of_speech: "명사"
    },
    {
        no: 21,
        word: "必须",
        word_traditional: "必須",
        pinyin: "bìxū",
        zh: "你必须完成作业。",
        zh_traditional: "你必須完成作業。",
        zh_pinyin: "nǐ bìxū wánchéng zuòyè.",
        ko: "너는 숙제를 반드시 해야 한다.",
        meaning_ko: "반드시 ~해야 하다",
        meanings_extra: ["꼭 해야 한다"],
        part_of_speech: "조동사"
      },
      {
        no: 22,
        word: "变化",
        word_traditional: "變化",
        pinyin: "biànhuà",
        zh: "天气有变化。",
        zh_traditional: "天氣有變化。",
        zh_pinyin: "tiānqì yǒu biànhuà.",
        ko: "날씨에 변화가 있다.",
        meaning_ko: "변화",
        meanings_extra: ["변하다"],
        part_of_speech: "명사/동사"
      },
      {
        no: 23,
        word: "别人",
        word_traditional: "別人",
        pinyin: "biérén",
        zh: "我不关心别人。",
        zh_traditional: "我不關心別人。",
        zh_pinyin: "wǒ bù guānxīn biérén.",
        ko: "나는 다른 사람에 신경 쓰지 않는다.",
        meaning_ko: "다른 사람",
        meanings_extra: ["타인"],
        part_of_speech: "명사"
      },
      {
        no: 24,
        word: "冰箱",
        word_traditional: "冰箱",
        pinyin: "bīngxiāng",
        zh: "冰箱里有水果。",
        zh_traditional: "冰箱裡有水果。",
        zh_pinyin: "bīngxiāng lǐ yǒu shuǐguǒ.",
        ko: "냉장고 안에 과일이 있다.",
        meaning_ko: "냉장고",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 25,
        word: "菜单",
        word_traditional: "菜單",
        pinyin: "càidān",
        zh: "请给我菜单。",
        zh_traditional: "請給我菜單。",
        zh_pinyin: "qǐng gěi wǒ càidān.",
        ko: "메뉴를 주세요.",
        meaning_ko: "메뉴판",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 26,
        word: "参加",
        word_traditional: "參加",
        pinyin: "cānjiā",
        zh: "我参加了比赛。",
        zh_traditional: "我參加了比賽。",
        zh_pinyin: "wǒ cānjiā le bǐsài.",
        ko: "나는 경기에 참가했다.",
        meaning_ko: "참가하다",
        meanings_extra: ["참여하다"],
        part_of_speech: "동사"
      },
      {
        no: 27,
        word: "草",
        word_traditional: "草",
        pinyin: "cǎo",
        zh: "草很绿。",
        zh_traditional: "草很綠。",
        zh_pinyin: "cǎo hěn lǜ.",
        ko: "풀이 매우 푸르다.",
        meaning_ko: "풀",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 28,
        word: "层",
        word_traditional: "層",
        pinyin: "céng",
        zh: "他住在三层。",
        zh_traditional: "他住在三層。",
        zh_pinyin: "tā zhù zài sān céng.",
        ko: "그는 3층에 산다.",
        meaning_ko: "층",
        meanings_extra: ["겹"],
        part_of_speech: "양사"
      },
      {
        no: 29,
        word: "差",
        word_traditional: "差",
        pinyin: "chà",
        zh: "他的成绩很差。",
        zh_traditional: "他的成績很差。",
        zh_pinyin: "tā de chéngjì hěn chà.",
        ko: "그의 성적이 매우 나쁘다.",
        meaning_ko: "나쁘다, 부족하다",
        meanings_extra: ["차이"],
        part_of_speech: "형용사"
      },
      {
        no: 30,
        word: "超市",
        word_traditional: "超市",
        pinyin: "chāoshì",
        zh: "我去超市买东西。",
        zh_traditional: "我去超市買東西。",
        zh_pinyin: "wǒ qù chāoshì mǎi dōngxi.",
        ko: "나는 슈퍼마켓에 물건을 사러 간다.",
        meaning_ko: "슈퍼마켓",
        meanings_extra: ["마트"],
        part_of_speech: "명사"
      },
      {
        no: 31,
        word: "衬衫",
        word_traditional: "襯衫",
        pinyin: "chènshān",
        zh: "他穿了一件衬衫。",
        zh_traditional: "他穿了一件襯衫。",
        zh_pinyin: "tā chuān le yí jiàn chènshān.",
        ko: "그는 셔츠 한 벌을 입었다.",
        meaning_ko: "셔츠",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 32,
        word: "成绩",
        word_traditional: "成績",
        pinyin: "chéngjì",
        zh: "他的成绩很好。",
        zh_traditional: "他的成績很好。",
        zh_pinyin: "tā de chéngjì hěn hǎo.",
        ko: "그의 성적이 매우 좋다.",
        meaning_ko: "성적, 결과",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 33,
        word: "城市",
        word_traditional: "城市",
        pinyin: "chéngshì",
        zh: "北京是一个大城市。",
        zh_traditional: "北京是一個大城市。",
        zh_pinyin: "Běijīng shì yí gè dà chéngshì.",
        ko: "베이징은 큰 도시이다.",
        meaning_ko: "도시",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 34,
        word: "迟到",
        word_traditional: "遲到",
        pinyin: "chídào",
        zh: "他今天迟到了。",
        zh_traditional: "他今天遲到了。",
        zh_pinyin: "tā jīntiān chídào le.",
        ko: "그는 오늘 늦었다.",
        meaning_ko: "지각하다",
        meanings_extra: [],
        part_of_speech: "동사"
      },
      {
        no: 35,
        word: "除了",
        word_traditional: "除了",
        pinyin: "chúle",
        zh: "除了他，大家都来了。",
        zh_traditional: "除了他，大家都來了。",
        zh_pinyin: "chúle tā, dàjiā dōu lái le.",
        ko: "그를 제외하고 모두가 왔다.",
        meaning_ko: "~을 제외하고",
        meanings_extra: ["~뿐만 아니라"],
        part_of_speech: "전치사"
      },
      {
        no: 36,
        word: "船",
        word_traditional: "船",
        pinyin: "chuán",
        zh: "我们坐船去旅游。",
        zh_traditional: "我們坐船去旅遊。",
        zh_pinyin: "wǒmen zuò chuán qù lǚyóu.",
        ko: "우리는 배를 타고 여행을 간다.",
        meaning_ko: "배",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 37,
        word: "春",
        word_traditional: "春",
        pinyin: "chūn",
        zh: "春天很美丽。",
        zh_traditional: "春天很美麗。",
        zh_pinyin: "chūntiān hěn měilì.",
        ko: "봄은 매우 아름답다.",
        meaning_ko: "봄",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 38,
        word: "词典",
        word_traditional: "詞典",
        pinyin: "cídiǎn",
        zh: "我买了一本词典。",
        zh_traditional: "我買了一本詞典。",
        zh_pinyin: "wǒ mǎi le yī běn cídiǎn.",
        ko: "나는 사전을 한 권 샀다.",
        meaning_ko: "사전",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 39,
        word: "聪明",
        word_traditional: "聰明",
        pinyin: "cōngming",
        zh: "他很聪明。",
        zh_traditional: "他很聰明。",
        zh_pinyin: "tā hěn cōngming.",
        ko: "그는 매우 똑똑하다.",
        meaning_ko: "똑똑하다",
        meanings_extra: ["영리하다"],
        part_of_speech: "형용사"
      },
      {
        no: 40,
        word: "打扫",
        word_traditional: "打掃",
        pinyin: "dǎsǎo",
        zh: "她打扫房间。",
        zh_traditional: "她打掃房間。",
        zh_pinyin: "tā dǎsǎo fángjiān.",
        ko: "그녀는 방을 청소한다.",
        meaning_ko: "청소하다",
        meanings_extra: [],
        part_of_speech: "동사"
      },
      {
        no: 41,
        word: "打算",
        word_traditional: "打算",
        pinyin: "dǎsuàn",
        zh: "我打算去北京。",
        zh_traditional: "我打算去北京。",
        zh_pinyin: "wǒ dǎsuàn qù Běijīng.",
        ko: "나는 베이징에 갈 계획이다.",
        meaning_ko: "계획하다, ~할 생각이다",
        meanings_extra: ["계획", "의도"],
        part_of_speech: "동사"
      },
      {
        no: 42,
        word: "带",
        word_traditional: "帶",
        pinyin: "dài",
        zh: "请带你的护照。",
        zh_traditional: "請帶你的護照。",
        zh_pinyin: "qǐng dài nǐ de hùzhào.",
        ko: "여권을 꼭 가지고 오세요.",
        meaning_ko: "가지고 오다, 지니다",
        meanings_extra: ["띠", "벨트"],
        part_of_speech: "동사/명사"
      },
      {
        no: 43,
        word: "担心",
        word_traditional: "擔心",
        pinyin: "dānxīn",
        zh: "我担心你。",
        zh_traditional: "我擔心你。",
        zh_pinyin: "wǒ dānxīn nǐ.",
        ko: "나는 네가 걱정된다.",
        meaning_ko: "걱정하다",
        meanings_extra: ["염려하다"],
        part_of_speech: "동사"
      },
      {
        no: 44,
        word: "蛋糕",
        word_traditional: "蛋糕",
        pinyin: "dàngāo",
        zh: "我喜欢吃蛋糕。",
        zh_traditional: "我喜歡吃蛋糕。",
        zh_pinyin: "wǒ xǐhuan chī dàngāo.",
        ko: "나는 케이크 먹는 것을 좋아한다.",
        meaning_ko: "케이크",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 45,
        word: "当然",
        word_traditional: "當然",
        pinyin: "dāngrán",
        zh: "当然可以。",
        zh_traditional: "當然可以。",
        zh_pinyin: "dāngrán kěyǐ.",
        ko: "물론 할 수 있다.",
        meaning_ko: "물론",
        meanings_extra: ["당연히"],
        part_of_speech: "부사"
      },
      {
        no: 46,
        word: "地",
        word_traditional: "地",
        pinyin: "de",
        zh: "他慢慢地走。",
        zh_traditional: "他慢慢地走。",
        zh_pinyin: "tā mànman de zǒu.",
        ko: "그는 천천히 걷는다.",
        meaning_ko: "부사화하는 조사",
        meanings_extra: [],
        part_of_speech: "조사"
      },
      {
        no: 47,
        word: "灯",
        word_traditional: "燈",
        pinyin: "dēng",
        zh: "灯开着。",
        zh_traditional: "燈開著。",
        zh_pinyin: "dēng kāi zhe.",
        ko: "등이 켜져 있다.",
        meaning_ko: "등, 전등",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 48,
        word: "地方",
        word_traditional: "地方",
        pinyin: "dìfang",
        zh: "这里是一个好地方。",
        zh_traditional: "這裡是一個好地方。",
        zh_pinyin: "zhèlǐ shì yí gè hǎo dìfang.",
        ko: "여기는 좋은 곳이다.",
        meaning_ko: "장소, 곳",
        meanings_extra: ["지역"],
        part_of_speech: "명사"
      },
      {
        no: 49,
        word: "地铁",
        word_traditional: "地鐵",
        pinyin: "dìtiě",
        zh: "我坐地铁去上班。",
        zh_traditional: "我坐地鐵去上班。",
        zh_pinyin: "wǒ zuò dìtiě qù shàngbān.",
        ko: "나는 지하철을 타고 출근한다.",
        meaning_ko: "지하철",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 50,
        word: "地图",
        word_traditional: "地圖",
        pinyin: "dìtú",
        zh: "我用地图找路。",
        zh_traditional: "我用地圖找路。",
        zh_pinyin: "wǒ yòng dìtú zhǎo lù.",
        ko: "나는 지도를 사용해 길을 찾는다.",
        meaning_ko: "지도",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 51,
        word: "电梯",
        word_traditional: "電梯",
        pinyin: "diàntī",
        zh: "电梯坏了。",
        zh_traditional: "電梯壞了。",
        zh_pinyin: "diàntī huài le.",
        ko: "엘리베이터가 고장 났다.",
        meaning_ko: "엘리베이터",
        meanings_extra: ["승강기"],
        part_of_speech: "명사"
      },
      {
        no: 52,
        word: "电子邮件",
        word_traditional: "電子郵件",
        pinyin: "diànzǐ yóujiàn",
        zh: "我收到了一封电子邮件。",
        zh_traditional: "我收到了一封電子郵件。",
        zh_pinyin: "wǒ shōudào le yì fēng diànzǐ yóujiàn.",
        ko: "나는 이메일 한 통을 받았다.",
        meaning_ko: "이메일",
        meanings_extra: ["전자우편"],
        part_of_speech: "명사"
      },
      {
        no: 53,
        word: "东",
        word_traditional: "東",
        pinyin: "dōng",
        zh: "太阳从东边升起。",
        zh_traditional: "太陽從東邊升起。",
        zh_pinyin: "tàiyáng cóng dōngbiān shēng qǐ.",
        ko: "태양은 동쪽에서 뜬다.",
        meaning_ko: "동쪽",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 54,
        word: "冬",
        word_traditional: "冬",
        pinyin: "dōng",
        zh: "冬天很冷。",
        zh_traditional: "冬天很冷。",
        zh_pinyin: "dōngtiān hěn lěng.",
        ko: "겨울은 매우 춥다.",
        meaning_ko: "겨울",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 55,
        word: "动物",
        word_traditional: "動物",
        pinyin: "dòngwù",
        zh: "动物园里有很多动物。",
        zh_traditional: "動物園裡有很多動物。",
        zh_pinyin: "dòngwùyuán lǐ yǒu hěn duō dòngwù.",
        ko: "동물원에는 동물이 많다.",
        meaning_ko: "동물",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 56,
        word: "短",
        word_traditional: "短",
        pinyin: "duǎn",
        zh: "这条裤子太短了。",
        zh_traditional: "這條褲子太短了。",
        zh_pinyin: "zhè tiáo kùzi tài duǎn le.",
        ko: "이 바지는 너무 짧다.",
        meaning_ko: "짧다",
        meanings_extra: [],
        part_of_speech: "형용사"
      },
      {
        no: 57,
        word: "段",
        word_traditional: "段",
        pinyin: "duàn",
        zh: "这是一段有趣的故事。",
        zh_traditional: "這是一段有趣的故事。",
        zh_pinyin: "zhè shì yí duàn yǒuqù de gùshi.",
        ko: "이것은 재미있는 이야기 한 부분이다.",
        meaning_ko: "부분, 단락",
        meanings_extra: ["구간"],
        part_of_speech: "명사"
      },
      {
        no: 58,
        word: "锻炼",
        word_traditional: "鍛鍊",
        pinyin: "duànliàn",
        zh: "我每天锻炼身体。",
        zh_traditional: "我每天鍛鍊身體。",
        zh_pinyin: "wǒ měitiān duànliàn shēntǐ.",
        ko: "나는 매일 몸을 단련한다.",
        meaning_ko: "단련하다, 운동하다",
        meanings_extra: ["운동하다"],
        part_of_speech: "동사"
      },
      {
        no: 59,
        word: "多么",
        word_traditional: "多麼",
        pinyin: "duōme",
        zh: "多么漂亮的花啊！",
        zh_traditional: "多麼漂亮的花啊！",
        zh_pinyin: "duōme piàoliang de huā a!",
        ko: "정말 예쁜 꽃이구나!",
        meaning_ko: "얼마나, 매우",
        meanings_extra: ["아주"],
        part_of_speech: "부사"
      },
      {
        no: 60,
        word: "饿",
        word_traditional: "餓",
        pinyin: "è",
        zh: "我很饿。",
        zh_traditional: "我很餓。",
        zh_pinyin: "wǒ hěn è.",
        ko: "나는 매우 배고프다.",
        meaning_ko: "배고프다",
        meanings_extra: [],
        part_of_speech: "형용사"
      },
      {
        no: 61,
        word: "不但…而且…",
        word_traditional: "不但…而且…",
        pinyin: "bùdàn…érqiě…",
        zh: "他不但会说中文，而且会说英语。",
        zh_traditional: "他不但會說中文，而且會說英語。",
        zh_pinyin: "tā bùdàn huì shuō Zhōngwén, érqiě huì shuō Yīngyǔ.",
        ko: "그는 중국어뿐만 아니라 영어도 할 줄 안다.",
        meaning_ko: "~뿐만 아니라 ~도",
        meanings_extra: ["~뿐 아니라", "~게다가"],
        part_of_speech: "접속사"
      },
      {
        no: 62,
        word: "耳朵",
        word_traditional: "耳朵",
        pinyin: "ěrduo",
        zh: "我的耳朵疼。",
        zh_traditional: "我的耳朵疼。",
        zh_pinyin: "wǒ de ěrduo téng.",
        ko: "내 귀가 아프다.",
        meaning_ko: "귀",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 63,
        word: "发",
        word_traditional: "發",
        pinyin: "fā",
        zh: "他发了一个邮件。",
        zh_traditional: "他發了一個郵件。",
        zh_pinyin: "tā fā le yí gè yóujiàn.",
        ko: "그는 이메일을 보냈다.",
        meaning_ko: "보내다, 발송하다",
        meanings_extra: [],
        part_of_speech: "동사"
      },
      {
        no: 64,
        word: "发烧",
        word_traditional: "發燒",
        pinyin: "fāshāo",
        zh: "我发烧了。",
        zh_traditional: "我發燒了。",
        zh_pinyin: "wǒ fāshāo le.",
        ko: "나는 열이 났다.",
        meaning_ko: "열이 나다",
        meanings_extra: [],
        part_of_speech: "동사"
      },
      {
        no: 65,
        word: "发现",
        word_traditional: "發現",
        pinyin: "fāxiàn",
        zh: "我发现了一个问题。",
        zh_traditional: "我發現了一個問題。",
        zh_pinyin: "wǒ fāxiàn le yí gè wèntí.",
        ko: "나는 문제를 발견했다.",
        meaning_ko: "발견하다",
        meanings_extra: ["알아내다"],
        part_of_speech: "동사"
      },
      {
        no: 66,
        word: "方便",
        word_traditional: "方便",
        pinyin: "fāngbiàn",
        zh: "这个地方很方便。",
        zh_traditional: "這個地方很方便。",
        zh_pinyin: "zhè ge dìfang hěn fāngbiàn.",
        ko: "이곳은 매우 편리하다.",
        meaning_ko: "편리하다",
        meanings_extra: ["편하다"],
        part_of_speech: "형용사"
      },
      {
        no: 67,
        word: "放",
        word_traditional: "放",
        pinyin: "fàng",
        zh: "请把书放在桌子上。",
        zh_traditional: "請把書放在桌子上。",
        zh_pinyin: "qǐng bǎ shū fàng zài zhuōzi shàng.",
        ko: "책을 탁자 위에 놓아 주세요.",
        meaning_ko: "놓다, 두다",
        meanings_extra: ["놓아두다"],
        part_of_speech: "동사"
      },
      {
        no: 68,
        word: "放心",
        word_traditional: "放心",
        pinyin: "fàngxīn",
        zh: "你放心，我会帮你。",
        zh_traditional: "你放心，我會幫你。",
        zh_pinyin: "nǐ fàngxīn, wǒ huì bāng nǐ.",
        ko: "걱정하지 마, 내가 도와줄게.",
        meaning_ko: "안심하다",
        meanings_extra: ["걱정하지 않다"],
        part_of_speech: "동사"
      },
      {
        no: 69,
        word: "分",
        word_traditional: "分",
        pinyin: "fēn",
        zh: "现在是三点十分。",
        zh_traditional: "現在是三點十分。",
        zh_pinyin: "xiànzài shì sān diǎn shí fēn.",
        ko: "지금은 3시 10분이다.",
        meaning_ko: "분 (시간 단위)",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 70,
        word: "附近",
        word_traditional: "附近",
        pinyin: "fùjìn",
        zh: "学校附近有一个公园。",
        zh_traditional: "學校附近有一個公園。",
        zh_pinyin: "xuéxiào fùjìn yǒu yí gè gōngyuán.",
        ko: "학교 근처에 공원이 하나 있다.",
        meaning_ko: "근처",
        meanings_extra: ["주변"],
        part_of_speech: "명사"
      },
      {
        no: 71,
        word: "复习",
        word_traditional: "複習",
        pinyin: "fùxí",
        zh: "我复习了课文。",
        zh_traditional: "我複習了課文。",
        zh_pinyin: "wǒ fùxí le kèwén.",
        ko: "나는 수업 내용을 복습했다.",
        meaning_ko: "복습하다",
        meanings_extra: ["되돌아보다"],
        part_of_speech: "동사"
      },
      {
        no: 72,
        word: "干净",
        word_traditional: "乾淨",
        pinyin: "gānjìng",
        zh: "房间很干净。",
        zh_traditional: "房間很乾淨。",
        zh_pinyin: "fángjiān hěn gānjìng.",
        ko: "방이 매우 깨끗하다.",
        meaning_ko: "깨끗하다",
        meanings_extra: ["청결하다"],
        part_of_speech: "형용사"
      },
      {
        no: 73,
        word: "感兴趣",
        word_traditional: "感興趣",
        pinyin: "gǎn xìngqù",
        zh: "我对音乐感兴趣。",
        zh_traditional: "我對音樂感興趣。",
        zh_pinyin: "wǒ duì yīnyuè gǎn xìngqù.",
        ko: "나는 음악에 관심이 있다.",
        meaning_ko: "관심을 가지다",
        meanings_extra: ["흥미를 느끼다"],
        part_of_speech: "동사구"
      },
      {
        no: 74,
        word: "感冒",
        word_traditional: "感冒",
        pinyin: "gǎnmào",
        zh: "我感冒了。",
        zh_traditional: "我感冒了。",
        zh_pinyin: "wǒ gǎnmào le.",
        ko: "나는 감기에 걸렸다.",
        meaning_ko: "감기에 걸리다",
        meanings_extra: [],
        part_of_speech: "동사"
      },
      {
        no: 75,
        word: "刚才",
        word_traditional: "剛才",
        pinyin: "gāngcái",
        zh: "他刚才来了。",
        zh_traditional: "他剛才來了。",
        zh_pinyin: "tā gāngcái lái le.",
        ko: "그는 방금 왔다.",
        meaning_ko: "방금, 아까",
        meanings_extra: [],
        part_of_speech: "부사"
      },
      {
        no: 76,
        word: "个子",
        word_traditional: "個子",
        pinyin: "gèzi",
        zh: "她个子很高。",
        zh_traditional: "她個子很高。",
        zh_pinyin: "tā gèzi hěn gāo.",
        ko: "그녀는 키가 크다.",
        meaning_ko: "키, 신장",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 77,
        word: "跟",
        word_traditional: "跟",
        pinyin: "gēn",
        zh: "我跟他是朋友。",
        zh_traditional: "我跟他是朋友。",
        zh_pinyin: "wǒ gēn tā shì péngyou.",
        ko: "나는 그와 친구이다.",
        meaning_ko: "~와, ~과",
        meanings_extra: ["따르다"],
        part_of_speech: "전치사"
      },
      {
        no: 78,
        word: "根据",
        word_traditional: "根據",
        pinyin: "gēnjù",
        zh: "根据天气预报，明天会下雨。",
        zh_traditional: "根據天氣預報，明天會下雨。",
        zh_pinyin: "gēnjù tiānqì yùbào, míngtiān huì xiàyǔ.",
        ko: "일기예보에 따르면 내일 비가 올 것이다.",
        meaning_ko: "~에 근거하여",
        meanings_extra: ["~에 따라"],
        part_of_speech: "전치사"
      },
      {
        no: 79,
        word: "更",
        word_traditional: "更",
        pinyin: "gèng",
        zh: "今天比昨天更冷。",
        zh_traditional: "今天比昨天更冷。",
        zh_pinyin: "jīntiān bǐ zuótiān gèng lěng.",
        ko: "오늘은 어제보다 더 춥다.",
        meaning_ko: "더",
        meanings_extra: ["한층"],
        part_of_speech: "부사"
      },
      {
        no: 80,
        word: "公斤",
        word_traditional: "公斤",
        pinyin: "gōngjīn",
        zh: "这个苹果一公斤。",
        zh_traditional: "這個蘋果一公斤。",
        zh_pinyin: "zhège píngguǒ yì gōngjīn.",
        ko: "이 사과는 1kg이다.",
        meaning_ko: "킬로그램",
        meanings_extra: ["kg"],
        part_of_speech: "명사"
      },
      {
        no: 81,
        word: "公园",
        word_traditional: "公園",
        pinyin: "gōngyuán",
        zh: "我们去公园玩。",
        zh_traditional: "我們去公園玩。",
        zh_pinyin: "wǒmen qù gōngyuán wán.",
        ko: "우리는 공원에 놀러 간다.",
        meaning_ko: "공원",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 82,
        word: "故事",
        word_traditional: "故事",
        pinyin: "gùshi",
        zh: "这个故事很有趣。",
        zh_traditional: "這個故事很有趣。",
        zh_pinyin: "zhège gùshi hěn yǒuqù.",
        ko: "이 이야기는 매우 재미있다.",
        meaning_ko: "이야기, 이야기하다",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 83,
        word: "刮风",
        word_traditional: "刮風",
        pinyin: "guāfēng",
        zh: "今天刮风了。",
        zh_traditional: "今天刮風了。",
        zh_pinyin: "jīntiān guāfēng le.",
        ko: "오늘 바람이 분다.",
        meaning_ko: "바람이 불다",
        meanings_extra: [],
        part_of_speech: "동사"
      },
      {
        no: 84,
        word: "关",
        word_traditional: "關",
        pinyin: "guān",
        zh: "请关门。",
        zh_traditional: "請關門。",
        zh_pinyin: "qǐng guān mén.",
        ko: "문을 닫아 주세요.",
        meaning_ko: "닫다, 잠그다",
        meanings_extra: [],
        part_of_speech: "동사"
      },
      {
        no: 85,
        word: "关系",
        word_traditional: "關係",
        pinyin: "guānxì",
        zh: "我们是好关系。",
        zh_traditional: "我們是好關係。",
        zh_pinyin: "wǒmen shì hǎo guānxì.",
        ko: "우리는 좋은 관계이다.",
        meaning_ko: "관계",
        meanings_extra: ["연락"],
        part_of_speech: "명사"
      },
      {
        no: 86,
        word: "关心",
        word_traditional: "關心",
        pinyin: "guānxīn",
        zh: "我关心你。",
        zh_traditional: "我關心你。",
        zh_pinyin: "wǒ guānxīn nǐ.",
        ko: "나는 너를 걱정한다.",
        meaning_ko: "걱정하다, 관심을 가지다",
        meanings_extra: [],
        part_of_speech: "동사"
      },
      {
        no: 87,
        word: "关于",
        word_traditional: "關於",
        pinyin: "guānyú",
        zh: "这是关于中国的书。",
        zh_traditional: "這是關於中國的書。",
        zh_pinyin: "zhè shì guānyú Zhōngguó de shū.",
        ko: "이것은 중국에 관한 책이다.",
        meaning_ko: "~에 관하여",
        meanings_extra: ["~에 대하여"],
        part_of_speech: "전치사"
      },
      {
        no: 88,
        word: "国家",
        word_traditional: "國家",
        pinyin: "guójiā",
        zh: "中国是一个大国家。",
        zh_traditional: "中國是一個大國家。",
        zh_pinyin: "Zhōngguó shì yí gè dà guójiā.",
        ko: "중국은 큰 나라이다.",
        meaning_ko: "나라, 국가",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 89,
        word: "过去",
        word_traditional: "過去",
        pinyin: "guòqù",
        zh: "他过去了学校。",
        zh_traditional: "他過去了學校。",
        zh_pinyin: "tā guòqù le xuéxiào.",
        ko: "그는 학교에 갔다.",
        meaning_ko: "과거, 지나가다",
        meanings_extra: ["지난 시절"],
        part_of_speech: "명사/동사"
      },
      {
        no: 90,
        word: "过",
        word_traditional: "過",
        pinyin: "guò",
        zh: "我去过北京。",
        zh_traditional: "我去過北京。",
        zh_pinyin: "wǒ qù guò Běijīng.",
        ko: "나는 베이징에 가본 적이 있다.",
        meaning_ko: "경험을 나타내는 동사 뒤 보어",
        meanings_extra: ["지나다"],
        part_of_speech: "조사/동사"
      },
      {
        no: 91,
        word: "还是",
        word_traditional: "還是",
        pinyin: "háishì",
        zh: "你喝茶还是咖啡？",
        zh_traditional: "你喝茶還是咖啡？",
        zh_pinyin: "nǐ hē chá háishì kāfēi?",
        ko: "너는 차를 마시니, 아니면 커피를 마시니?",
        meaning_ko: "아직도, 혹은",
        meanings_extra: ["또는"],
        part_of_speech: "부사/접속사"
      },
      {
        no: 92,
        word: "害怕",
        word_traditional: "害怕",
        pinyin: "hàipà",
        zh: "我害怕黑暗。",
        zh_traditional: "我害怕黑暗。",
        zh_pinyin: "wǒ hàipà hēi'àn.",
        ko: "나는 어둠이 무섭다.",
        meaning_ko: "두려워하다",
        meanings_extra: ["무서워하다"],
        part_of_speech: "동사"
      },
      {
        no: 93,
        word: "黑板",
        word_traditional: "黑板",
        pinyin: "hēibǎn",
        zh: "老师在黑板上写字。",
        zh_traditional: "老師在黑板上寫字。",
        zh_pinyin: "lǎoshī zài hēibǎn shàng xiězì.",
        ko: "선생님이 칠판에 글을 쓴다.",
        meaning_ko: "칠판",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 94,
        word: "后来",
        word_traditional: "後來",
        pinyin: "hòulái",
        zh: "他后来去了北京。",
        zh_traditional: "他後來去了北京。",
        zh_pinyin: "tā hòulái qù le Běijīng.",
        ko: "그는 나중에 베이징에 갔다.",
        meaning_ko: "나중에",
        meanings_extra: ["후에"],
        part_of_speech: "부사"
      },
      {
        no: 95,
        word: "护照",
        word_traditional: "護照",
        pinyin: "hùzhào",
        zh: "请带好护照。",
        zh_traditional: "請帶好護照。",
        zh_pinyin: "qǐng dài hǎo hùzhào.",
        ko: "여권을 잘 챙기세요.",
        meaning_ko: "여권",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 96,
        word: "花",
        word_traditional: "花",
        pinyin: "huā",
        zh: "我花了很多钱。",
        zh_traditional: "我花了很多錢。",
        zh_pinyin: "wǒ huā le hěn duō qián.",
        ko: "나는 돈을 많이 썼다.",
        meaning_ko: "쓰다, 소비하다",
        meanings_extra: ["소비하다"],
        part_of_speech: "동사"
      },
      {
        no: 97,
        word: "花",
        word_traditional: "花",
        pinyin: "huā",
        zh: "这是一朵花。",
        zh_traditional: "這是一朵花。",
        zh_pinyin: "zhè shì yì duǒ huā.",
        ko: "이것은 꽃 한 송이이다.",
        meaning_ko: "꽃",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 98,
        word: "画",
        word_traditional: "畫",
        pinyin: "huà",
        zh: "她喜欢画画。",
        zh_traditional: "她喜歡畫畫。",
        zh_pinyin: "tā xǐhuan huà huà.",
        ko: "그녀는 그림 그리는 것을 좋아한다.",
        meaning_ko: "그리다, 그림",
        meanings_extra: [],
        part_of_speech: "동사/명사"
      },
      {
        no: 99,
        word: "坏",
        word_traditional: "壞",
        pinyin: "huài",
        zh: "我的手机坏了。",
        zh_traditional: "我的手機壞了。",
        zh_pinyin: "wǒ de shǒujī huài le.",
        ko: "내 휴대폰이 고장 났다.",
        meaning_ko: "나쁘다, 고장나다",
        meanings_extra: ["망가지다"],
        part_of_speech: "형용사/동사"
      },
      {
        no: 100,
        word: "欢迎",
        word_traditional: "歡迎",
        pinyin: "huānyíng",
        zh: "欢迎你来中国。",
        zh_traditional: "歡迎你來中國。",
        zh_pinyin: "huānyíng nǐ lái Zhōngguó.",
        ko: "중국에 오신 것을 환영합니다.",
        meaning_ko: "환영하다",
        meanings_extra: ["맞이하다"],
        part_of_speech: "동사"
      },
      {
        no: 101,
        word: "还",
        word_traditional: "還",
        pinyin: "huán",
        zh: "我还书了。",
        zh_traditional: "我還書了。",
        zh_pinyin: "wǒ huán shū le.",
        ko: "나는 책을 반납했다.",
        meaning_ko: "돌려주다, 반환하다",
        meanings_extra: ["되돌려주다"],
        part_of_speech: "동사"
      },
      {
        no: 102,
        word: "环境",
        word_traditional: "環境",
        pinyin: "huánjìng",
        zh: "这里的环境很好。",
        zh_traditional: "這裡的環境很好。",
        zh_pinyin: "zhèlǐ de huánjìng hěn hǎo.",
        ko: "이곳의 환경이 매우 좋다.",
        meaning_ko: "환경",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 103,
        word: "换",
        word_traditional: "換",
        pinyin: "huàn",
        zh: "我换了衣服。",
        zh_traditional: "我換了衣服。",
        zh_pinyin: "wǒ huàn le yīfu.",
        ko: "나는 옷을 갈아입었다.",
        meaning_ko: "바꾸다, 교환하다",
        meanings_extra: [],
        part_of_speech: "동사"
      },
      {
        no: 104,
        word: "黄河",
        word_traditional: "黃河",
        pinyin: "Huánghé",
        zh: "黄河是中国的母亲河。",
        zh_traditional: "黃河是中國的母親河。",
        zh_pinyin: "Huánghé shì Zhōngguó de mǔqīn hé.",
        ko: "황하는 중국의 어머니 강이다.",
        meaning_ko: "황하 (중국의 강 이름)",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 105,
        word: "回答",
        word_traditional: "回答",
        pinyin: "huídá",
        zh: "请回答我的问题。",
        zh_traditional: "請回答我的問題。",
        zh_pinyin: "qǐng huídá wǒ de wèntí.",
        ko: "내 질문에 답해 주세요.",
        meaning_ko: "대답하다",
        meanings_extra: ["답변"],
        part_of_speech: "동사"
      },
      {
        no: 106,
        word: "会议",
        word_traditional: "會議",
        pinyin: "huìyì",
        zh: "今天有一个会议。",
        zh_traditional: "今天有一個會議。",
        zh_pinyin: "jīntiān yǒu yí gè huìyì.",
        ko: "오늘 회의가 있다.",
        meaning_ko: "회의",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 107,
        word: "或者",
        word_traditional: "或者",
        pinyin: "huòzhě",
        zh: "你想喝茶或者咖啡？",
        zh_traditional: "你想喝茶或者咖啡？",
        zh_pinyin: "nǐ xiǎng hē chá huòzhě kāfēi?",
        ko: "너는 차 아니면 커피 마실래?",
        meaning_ko: "혹은, 또는",
        meanings_extra: ["아니면"],
        part_of_speech: "접속사"
      },
      {
        no: 108,
        word: "几乎",
        word_traditional: "幾乎",
        pinyin: "jīhū",
        zh: "我几乎每天学习。",
        zh_traditional: "我幾乎每天學習。",
        zh_pinyin: "wǒ jīhū měitiān xuéxí.",
        ko: "나는 거의 매일 공부한다.",
        meaning_ko: "거의",
        meanings_extra: ["대부분"],
        part_of_speech: "부사"
      },
      {
        no: 109,
        word: "机会",
        word_traditional: "機會",
        pinyin: "jīhuì",
        zh: "我有一个好机会。",
        zh_traditional: "我有一個好機會。",
        zh_pinyin: "wǒ yǒu yí gè hǎo jīhuì.",
        ko: "나는 좋은 기회를 가졌다.",
        meaning_ko: "기회",
        meanings_extra: ["찬스"],
        part_of_speech: "명사"
      },
      {
        no: 110,
        word: "极",
        word_traditional: "極",
        pinyin: "jí",
        zh: "天气极好。",
        zh_traditional: "天氣極好。",
        zh_pinyin: "tiānqì jí hǎo.",
        ko: "날씨가 매우 좋다.",
        meaning_ko: "극히, 매우",
        meanings_extra: ["최고"],
        part_of_speech: "부사"
      },
      {
        no: 111,
        word: "记得",
        word_traditional: "記得",
        pinyin: "jìde",
        zh: "我记得他的名字。",
        zh_traditional: "我記得他的名字。",
        zh_pinyin: "wǒ jìde tā de míngzi.",
        ko: "나는 그의 이름을 기억한다.",
        meaning_ko: "기억하다",
        meanings_extra: ["생각나다"],
        part_of_speech: "동사"
      },
      {
        no: 112,
        word: "季节",
        word_traditional: "季節",
        pinyin: "jìjié",
        zh: "春天是我的喜欢的季节。",
        zh_traditional: "春天是我的喜歡的季節。",
        zh_pinyin: "chūntiān shì wǒ de xǐhuan de jìjié.",
        ko: "봄은 내가 좋아하는 계절이다.",
        meaning_ko: "계절",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 113,
        word: "检查",
        word_traditional: "檢查",
        pinyin: "jiǎnchá",
        zh: "医生检查了病人。",
        zh_traditional: "醫生檢查了病人。",
        zh_pinyin: "yīshēng jiǎnchá le bìngrén.",
        ko: "의사가 환자를 검사했다.",
        meaning_ko: "검사하다",
        meanings_extra: ["점검하다"],
        part_of_speech: "동사"
      },
      {
        no: 114,
        word: "简单",
        word_traditional: "簡單",
        pinyin: "jiǎndān",
        zh: "这个问题很简单。",
        zh_traditional: "這個問題很簡單。",
        zh_pinyin: "zhège wèntí hěn jiǎndān.",
        ko: "이 문제는 매우 쉽다.",
        meaning_ko: "간단하다",
        meanings_extra: ["쉬운"],
        part_of_speech: "형용사"
      },
      {
        no: 115,
        word: "健康",
        word_traditional: "健康",
        pinyin: "jiànkāng",
        zh: "身体健康很重要。",
        zh_traditional: "身體健康很重要。",
        zh_pinyin: "shēntǐ jiànkāng hěn zhòngyào.",
        ko: "건강이 매우 중요하다.",
        meaning_ko: "건강하다",
        meanings_extra: [],
        part_of_speech: "형용사"
      },
      {
        no: 116,
        word: "见面",
        word_traditional: "見面",
        pinyin: "jiànmiàn",
        zh: "我们明天见面。",
        zh_traditional: "我們明天見面。",
        zh_pinyin: "wǒmen míngtiān jiànmiàn.",
        ko: "우리는 내일 만난다.",
        meaning_ko: "만나다",
        meanings_extra: ["대면하다"],
        part_of_speech: "동사"
      },
      {
        no: 117,
        word: "讲",
        word_traditional: "講",
        pinyin: "jiǎng",
        zh: "老师讲得很好。",
        zh_traditional: "老師講得很好。",
        zh_pinyin: "lǎoshī jiǎng de hěn hǎo.",
        ko: "선생님이 아주 잘 설명한다.",
        meaning_ko: "말하다, 설명하다",
        meanings_extra: [],
        part_of_speech: "동사"
      },
      {
        no: 118,
        word: "教",
        word_traditional: "教",
        pinyin: "jiāo",
        zh: "他教我们中文。",
        zh_traditional: "他教我們中文。",
        zh_pinyin: "tā jiāo wǒmen Zhōngwén.",
        ko: "그는 우리에게 중국어를 가르친다.",
        meaning_ko: "가르치다",
        meanings_extra: [],
        part_of_speech: "동사"
      },
      {
        no: 119,
        word: "角",
        word_traditional: "角",
        pinyin: "jiǎo",
        zh: "桌子的角很尖。",
        zh_traditional: "桌子的角很尖。",
        zh_pinyin: "zhuōzi de jiǎo hěn jiān.",
        ko: "책상 모서리가 매우 뾰족하다.",
        meaning_ko: "모서리, 각",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 120,
        word: "脚",
        word_traditional: "腳",
        pinyin: "jiǎo",
        zh: "我的脚很疼。",
        zh_traditional: "我的腳很疼。",
        zh_pinyin: "wǒ de jiǎo hěn téng.",
        ko: "내 발이 매우 아프다.",
        meaning_ko: "발",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 121,
        word: "接",
        word_traditional: "接",
        pinyin: "jiē",
        zh: "我去接你。",
        zh_traditional: "我去接你。",
        zh_pinyin: "wǒ qù jiē nǐ.",
        ko: "내가 너를 데리러 갈게.",
        meaning_ko: "받다, 데리다",
        meanings_extra: ["맞다"],
        part_of_speech: "동사"
      },
      {
        no: 122,
        word: "街道",
        word_traditional: "街道",
        pinyin: "jiēdào",
        zh: "这条街道很热闹。",
        zh_traditional: "這條街道很熱鬧。",
        zh_pinyin: "zhè tiáo jiēdào hěn rènào.",
        ko: "이 거리는 매우 번화하다.",
        meaning_ko: "거리",
        meanings_extra: ["길"],
        part_of_speech: "명사"
      },
      {
        no: 123,
        word: "结婚",
        word_traditional: "結婚",
        pinyin: "jiéhūn",
        zh: "他们结婚了。",
        zh_traditional: "他們結婚了。",
        zh_pinyin: "tāmen jiéhūn le.",
        ko: "그들은 결혼했다.",
        meaning_ko: "결혼하다",
        meanings_extra: [],
        part_of_speech: "동사"
      },
      {
        no: 124,
        word: "结束",
        word_traditional: "結束",
        pinyin: "jiéshù",
        zh: "会议结束了。",
        zh_traditional: "會議結束了。",
        zh_pinyin: "huìyì jiéshù le.",
        ko: "회의가 끝났다.",
        meaning_ko: "끝나다",
        meanings_extra: ["종료하다"],
        part_of_speech: "동사"
      },
      {
        no: 125,
        word: "节目",
        word_traditional: "節目",
        pinyin: "jiémù",
        zh: "我喜欢这个节目。",
        zh_traditional: "我喜歡這個節目。",
        zh_pinyin: "wǒ xǐhuan zhège jiémù.",
        ko: "나는 이 프로그램을 좋아한다.",
        meaning_ko: "프로그램",
        meanings_extra: ["방송"],
        part_of_speech: "명사"
      },
      {
        no: 126,
        word: "节日",
        word_traditional: "節日",
        pinyin: "jiérì",
        zh: "春节是一个重要的节日。",
        zh_traditional: "春節是一個重要的節日。",
        zh_pinyin: "Chūnjié shì yí gè zhòngyào de jiérì.",
        ko: "춘절은 중요한 명절이다.",
        meaning_ko: "명절, 축제일",
        meanings_extra: ["휴일"],
        part_of_speech: "명사"
      },
      {
        no: 127,
        word: "解决",
        word_traditional: "解決",
        pinyin: "jiějué",
        zh: "我们解决了问题。",
        zh_traditional: "我們解決了問題。",
        zh_pinyin: "wǒmen jiějué le wèntí.",
        ko: "우리는 문제를 해결했다.",
        meaning_ko: "해결하다",
        meanings_extra: ["처리하다"],
        part_of_speech: "동사"
      },
      {
        no: 128,
        word: "借",
        word_traditional: "借",
        pinyin: "jiè",
        zh: "我向朋友借书。",
        zh_traditional: "我向朋友借書。",
        zh_pinyin: "wǒ xiàng péngyou jiè shū.",
        ko: "나는 친구에게 책을 빌렸다.",
        meaning_ko: "빌리다, 빌려주다",
        meanings_extra: [],
        part_of_speech: "동사"
      },
      {
        no: 129,
        word: "经常",
        word_traditional: "經常",
        pinyin: "jīngcháng",
        zh: "我经常去图书馆。",
        zh_traditional: "我經常去圖書館。",
        zh_pinyin: "wǒ jīngcháng qù túshūguǎn.",
        ko: "나는 자주 도서관에 간다.",
        meaning_ko: "자주",
        meanings_extra: ["항상"],
        part_of_speech: "부사"
      },
      {
        no: 130,
        word: "经过",
        word_traditional: "經過",
        pinyin: "jīngguò",
        zh: "我经过公园去学校。",
        zh_traditional: "我經過公園去學校。",
        zh_pinyin: "wǒ jīngguò gōngyuán qù xuéxiào.",
        ko: "나는 공원을 지나 학교에 간다.",
        meaning_ko: "지나가다, 경과하다",
        meanings_extra: ["경험하다"],
        part_of_speech: "동사"
      },
      {
        no: 131,
        word: "经理",
        word_traditional: "經理",
        pinyin: "jīnglǐ",
        zh: "他是公司的经理。",
        zh_traditional: "他是公司的經理。",
        zh_pinyin: "tā shì gōngsī de jīnglǐ.",
        ko: "그는 회사의 매니저이다.",
        meaning_ko: "매니저, 관리자",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 132,
        word: "久",
        word_traditional: "久",
        pinyin: "jiǔ",
        zh: "我等了很久。",
        zh_traditional: "我等了很久。",
        zh_pinyin: "wǒ děng le hěn jiǔ.",
        ko: "나는 오래 기다렸다.",
        meaning_ko: "오래",
        meanings_extra: ["장시간"],
        part_of_speech: "형용사/부사"
      },
      {
        no: 133,
        word: "旧",
        word_traditional: "舊",
        pinyin: "jiù",
        zh: "这本书很旧。",
        zh_traditional: "這本書很舊。",
        zh_pinyin: "zhè běn shū hěn jiù.",
        ko: "이 책은 매우 낡았다.",
        meaning_ko: "낡다, 오래되다",
        meanings_extra: ["오래된"],
        part_of_speech: "형용사"
      },
      {
        no: 134,
        word: "句子",
        word_traditional: "句子",
        pinyin: "jùzi",
        zh: "这个句子很难。",
        zh_traditional: "這個句子很難。",
        zh_pinyin: "zhège jùzi hěn nán.",
        ko: "이 문장은 어렵다.",
        meaning_ko: "문장",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 135,
        word: "决定",
        word_traditional: "決定",
        pinyin: "juédìng",
        zh: "我决定学习中文。",
        zh_traditional: "我決定學習中文。",
        zh_pinyin: "wǒ juédìng xuéxí Zhōngwén.",
        ko: "나는 중국어를 공부하기로 결정했다.",
        meaning_ko: "결정하다",
        meanings_extra: ["판단하다"],
        part_of_speech: "동사"
      },
      {
        no: 136,
        word: "渴",
        word_traditional: "渴",
        pinyin: "kě",
        zh: "我很渴。",
        zh_traditional: "我很渴。",
        zh_pinyin: "wǒ hěn kě.",
        ko: "나는 매우 목마르다.",
        meaning_ko: "목마르다",
        meanings_extra: [],
        part_of_speech: "형용사"
      },
      {
        no: 137,
        word: "可爱",
        word_traditional: "可愛",
        pinyin: "kě'ài",
        zh: "这只猫很可爱。",
        zh_traditional: "這隻貓很可愛。",
        zh_pinyin: "zhè zhī māo hěn kě'ài.",
        ko: "이 고양이는 매우 귀엽다.",
        meaning_ko: "귀엽다",
        meanings_extra: ["사랑스럽다"],
        part_of_speech: "형용사"
      },
      {
        no: 138,
        word: "刻",
        word_traditional: "刻",
        pinyin: "kè",
        zh: "现在三点一刻。",
        zh_traditional: "現在三點一刻。",
        zh_pinyin: "xiànzài sān diǎn yí kè.",
        ko: "지금은 3시 15분이다.",
        meaning_ko: "15분, 순간",
        meanings_extra: ["시간 단위"],
        part_of_speech: "명사"
      },
      {
        no: 139,
        word: "客人",
        word_traditional: "客人",
        pinyin: "kèrén",
        zh: "客人来了。",
        zh_traditional: "客人來了。",
        zh_pinyin: "kèrén lái le.",
        ko: "손님이 왔다.",
        meaning_ko: "손님",
        meanings_extra: ["게스트"],
        part_of_speech: "명사"
      },
      {
        no: 140,
        word: "空调",
        word_traditional: "空調",
        pinyin: "kōngtiáo",
        zh: "房间有空调。",
        zh_traditional: "房間有空調。",
        zh_pinyin: "fángjiān yǒu kōngtiáo.",
        ko: "방에 에어컨이 있다.",
        meaning_ko: "에어컨",
        meanings_extra: ["냉방기"],
        part_of_speech: "명사"
      },
      {
        no: 141,
        word: "口",
        word_traditional: "口",
        pinyin: "kǒu",
        zh: "请张开你的口。",
        zh_traditional: "請張開你的口。",
        zh_pinyin: "qǐng zhāng kāi nǐ de kǒu.",
        ko: "입을 벌려 주세요.",
        meaning_ko: "입",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 142,
        word: "哭",
        word_traditional: "哭",
        pinyin: "kū",
        zh: "宝宝在哭。",
        zh_traditional: "寶寶在哭。",
        zh_pinyin: "bǎobǎo zài kū.",
        ko: "아기가 울고 있다.",
        meaning_ko: "울다",
        meanings_extra: [],
        part_of_speech: "동사"
      },
      {
        no: 143,
        word: "裤子",
        word_traditional: "褲子",
        pinyin: "kùzi",
        zh: "这条裤子很新。",
        zh_traditional: "這條褲子很新。",
        zh_pinyin: "zhè tiáo kùzi hěn xīn.",
        ko: "이 바지는 매우 새롭다.",
        meaning_ko: "바지",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 144,
        word: "筷子",
        word_traditional: "筷子",
        pinyin: "kuàizi",
        zh: "我用筷子吃饭。",
        zh_traditional: "我用筷子吃飯。",
        zh_pinyin: "wǒ yòng kuàizi chī fàn.",
        ko: "나는 젓가락으로 밥을 먹는다.",
        meaning_ko: "젓가락",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 145,
        word: "蓝",
        word_traditional: "藍",
        pinyin: "lán",
        zh: "天空是蓝色的。",
        zh_traditional: "天空是藍色的。",
        zh_pinyin: "tiānkōng shì lán sè de.",
        ko: "하늘은 파란색이다.",
        meaning_ko: "파란색",
        meanings_extra: [],
        part_of_speech: "형용사"
      },
      {
        no: 146,
        word: "老",
        word_traditional: "老",
        pinyin: "lǎo",
        zh: "爷爷很老了。",
        zh_traditional: "爺爺很老了。",
        zh_pinyin: "yéye hěn lǎo le.",
        ko: "할아버지는 매우 나이가 많다.",
        meaning_ko: "늙다, 나이가 많다",
        meanings_extra: [],
        part_of_speech: "형용사"
      },
      {
        no: 147,
        word: "离开",
        word_traditional: "離開",
        pinyin: "líkāi",
        zh: "我明天离开这里。",
        zh_traditional: "我明天離開這裡。",
        zh_pinyin: "wǒ míngtiān líkāi zhèlǐ.",
        ko: "나는 내일 이곳을 떠난다.",
        meaning_ko: "떠나다",
        meanings_extra: ["이별하다"],
        part_of_speech: "동사"
      },
      {
        no: 148,
        word: "礼物",
        word_traditional: "禮物",
        pinyin: "lǐwù",
        zh: "我买了一个礼物。",
        zh_traditional: "我買了一個禮物。",
        zh_pinyin: "wǒ mǎi le yí gè lǐwù.",
        ko: "나는 선물을 하나 샀다.",
        meaning_ko: "선물",
        meanings_extra: ["기념품"],
        part_of_speech: "명사"
      },
      {
        no: 149,
        word: "历史",
        word_traditional: "歷史",
        pinyin: "lìshǐ",
        zh: "我喜欢学习历史。",
        zh_traditional: "我喜歡學習歷史。",
        zh_pinyin: "wǒ xǐhuan xuéxí lìshǐ.",
        ko: "나는 역사를 공부하는 것을 좋아한다.",
        meaning_ko: "역사",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 150,
        word: "脸",
        word_traditional: "臉",
        pinyin: "liǎn",
        zh: "她有一个圆脸。",
        zh_traditional: "她有一個圓臉。",
        zh_pinyin: "tā yǒu yí gè yuán liǎn.",
        ko: "그녀는 둥근 얼굴을 가지고 있다.",
        meaning_ko: "얼굴",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 151,
        word: "聊天",
        word_traditional: "聊天",
        pinyin: "liáotiān",
        zh: "我们喜欢聊天。",
        zh_traditional: "我們喜歡聊天。",
        zh_pinyin: "wǒmen xǐhuan liáotiān.",
        ko: "우리는 대화하는 것을 좋아한다.",
        meaning_ko: "이야기하다, 대화하다",
        meanings_extra: ["수다떨다"],
        part_of_speech: "동사"
      },
      {
        no: 152,
        word: "练习",
        word_traditional: "練習",
        pinyin: "liànxí",
        zh: "我每天练习汉语。",
        zh_traditional: "我每天練習漢語。",
        zh_pinyin: "wǒ měitiān liànxí Hànyǔ.",
        ko: "나는 매일 중국어를 연습한다.",
        meaning_ko: "연습하다",
        meanings_extra: [],
        part_of_speech: "동사"
      },
      {
        no: 153,
        word: "辆",
        word_traditional: "輛",
        pinyin: "liàng",
        zh: "我家有两辆车。",
        zh_traditional: "我家有兩輛車。",
        zh_pinyin: "wǒ jiā yǒu liǎng liàng chē.",
        ko: "우리 집에는 차가 두 대 있다.",
        meaning_ko: "대 (차량 단위)",
        meanings_extra: [],
        part_of_speech: "양사"
      },
      {
        no: 154,
        word: "了解",
        word_traditional: "了解",
        pinyin: "liǎojiě",
        zh: "我了解这个问题。",
        zh_traditional: "我了解這個問題。",
        zh_pinyin: "wǒ liǎojiě zhège wèntí.",
        ko: "나는 이 문제를 이해한다.",
        meaning_ko: "이해하다",
        meanings_extra: ["알다"],
        part_of_speech: "동사"
      },
      {
        no: 155,
        word: "邻居",
        word_traditional: "鄰居",
        pinyin: "línjū",
        zh: "我的邻居很友好。",
        zh_traditional: "我的鄰居很友好。",
        zh_pinyin: "wǒ de línjū hěn yǒuhǎo.",
        ko: "우리 이웃은 매우 친절하다.",
        meaning_ko: "이웃",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 156,
        word: "留学",
        word_traditional: "留學",
        pinyin: "liúxué",
        zh: "他去美国留学。",
        zh_traditional: "他去美國留學。",
        zh_pinyin: "tā qù Měiguó liúxué.",
        ko: "그는 미국에 유학 간다.",
        meaning_ko: "유학하다",
        meanings_extra: [],
        part_of_speech: "동사"
      },
      {
        no: 157,
        word: "楼",
        word_traditional: "樓",
        pinyin: "lóu",
        zh: "我住在三楼。",
        zh_traditional: "我住在三樓。",
        zh_pinyin: "wǒ zhù zài sān lóu.",
        ko: "나는 3층에 산다.",
        meaning_ko: "건물, 층",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 158,
        word: "绿",
        word_traditional: "綠",
        pinyin: "lǜ",
        zh: "这是一片绿草地。",
        zh_traditional: "這是一片綠草地。",
        zh_pinyin: "zhè shì yí piàn lǜ cǎodì.",
        ko: "이곳은 푸른 초원이다.",
        meaning_ko: "초록색",
        meanings_extra: [],
        part_of_speech: "형용사"
      },
      {
        no: 159,
        word: "马",
        word_traditional: "馬",
        pinyin: "mǎ",
        zh: "他骑马。",
        zh_traditional: "他騎馬。",
        zh_pinyin: "tā qí mǎ.",
        ko: "그는 말을 탄다.",
        meaning_ko: "말",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 160,
        word: "马上",
        word_traditional: "馬上",
        pinyin: "mǎshàng",
        zh: "我马上去。",
        zh_traditional: "我馬上去。",
        zh_pinyin: "wǒ mǎshàng qù.",
        ko: "나는 곧 간다.",
        meaning_ko: "곧, 바로",
        meanings_extra: ["즉시"],
        part_of_speech: "부사"
      },
      {
        no: 161,
        word: "满意",
        word_traditional: "滿意",
        pinyin: "mǎnyì",
        zh: "我对结果很满意。",
        zh_traditional: "我對結果很滿意。",
        zh_pinyin: "wǒ duì jiéguǒ hěn mǎnyì.",
        ko: "나는 결과에 매우 만족한다.",
        meaning_ko: "만족하다",
        meanings_extra: ["마음에 들다"],
        part_of_speech: "형용사"
      },
      {
        no: 162,
        word: "帽子",
        word_traditional: "帽子",
        pinyin: "màozi",
        zh: "他戴着一顶帽子。",
        zh_traditional: "他戴著一頂帽子。",
        zh_pinyin: "tā dàizhe yì dǐng màozi.",
        ko: "그는 모자를 쓰고 있다.",
        meaning_ko: "모자",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 163,
        word: "米",
        word_traditional: "米",
        pinyin: "mǐ",
        zh: "我喜欢吃米饭。",
        zh_traditional: "我喜歡吃米飯。",
        zh_pinyin: "wǒ xǐhuan chī mǐfàn.",
        ko: "나는 밥 먹는 것을 좋아한다.",
        meaning_ko: "쌀, 미터",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 164,
        word: "面包",
        word_traditional: "麵包",
        pinyin: "miànbāo",
        zh: "我买了面包。",
        zh_traditional: "我買了麵包。",
        zh_pinyin: "wǒ mǎi le miànbāo.",
        ko: "나는 빵을 샀다.",
        meaning_ko: "빵",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 165,
        word: "明白",
        word_traditional: "明白",
        pinyin: "míngbai",
        zh: "我明白你的意思。",
        zh_traditional: "我明白你的意思。",
        zh_pinyin: "wǒ míngbai nǐ de yìsi.",
        ko: "나는 네 뜻을 이해한다.",
        meaning_ko: "이해하다, 명백하다",
        meanings_extra: [],
        part_of_speech: "동사/형용사"
      },
      {
        no: 166,
        word: "拿",
        word_traditional: "拿",
        pinyin: "ná",
        zh: "请拿这个给我。",
        zh_traditional: "請拿這個給我。",
        zh_pinyin: "qǐng ná zhège gěi wǒ.",
        ko: "이것을 내게 가져다 주세요.",
        meaning_ko: "잡다, 들다",
        meanings_extra: ["가지고 가다"],
        part_of_speech: "동사"
      },
      {
        no: 167,
        word: "奶奶",
        word_traditional: "奶奶",
        pinyin: "nǎinai",
        zh: "奶奶很喜欢花。",
        zh_traditional: "奶奶很喜歡花。",
        zh_pinyin: "nǎinai hěn xǐhuan huā.",
        ko: "할머니는 꽃을 매우 좋아하신다.",
        meaning_ko: "할머니",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 168,
        word: "南",
        word_traditional: "南",
        pinyin: "nán",
        zh: "我们向南走。",
        zh_traditional: "我們向南走。",
        zh_pinyin: "wǒmen xiàng nán zǒu.",
        ko: "우리는 남쪽으로 간다.",
        meaning_ko: "남쪽",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 169,
        word: "难",
        word_traditional: "難",
        pinyin: "nán",
        zh: "这道题很难。",
        zh_traditional: "這道題很難。",
        zh_pinyin: "zhè dào tí hěn nán.",
        ko: "이 문제는 매우 어렵다.",
        meaning_ko: "어렵다, 힘들다",
        meanings_extra: ["난처하다"],
        part_of_speech: "형용사"
      },
      {
        no: 170,
        word: "难过",
        word_traditional: "難過",
        pinyin: "nánguò",
        zh: "我很难过。",
        zh_traditional: "我很難過。",
        zh_pinyin: "wǒ hěn nánguò.",
        ko: "나는 매우 슬프다.",
        meaning_ko: "슬프다",
        meanings_extra: ["마음이 아프다"],
        part_of_speech: "형용사"
      },
      {
        no: 171,
        word: "年级",
        word_traditional: "年級",
        pinyin: "niánjí",
        zh: "我上三年级。",
        zh_traditional: "我上三年級。",
        zh_pinyin: "wǒ shàng sān niánjí.",
        ko: "나는 3학년에 다닌다.",
        meaning_ko: "학년",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 172,
        word: "年轻",
        word_traditional: "年輕",
        pinyin: "niánqīng",
        zh: "他很年轻。",
        zh_traditional: "他很年輕。",
        zh_pinyin: "tā hěn niánqīng.",
        ko: "그는 매우 젊다.",
        meaning_ko: "젊다",
        meanings_extra: ["어리다"],
        part_of_speech: "형용사"
      },
      {
        no: 173,
        word: "鸟",
        word_traditional: "鳥",
        pinyin: "niǎo",
        zh: "鸟在树上。",
        zh_traditional: "鳥在樹上。",
        zh_pinyin: "niǎo zài shù shàng.",
        ko: "새가 나무 위에 있다.",
        meaning_ko: "새",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 174,
        word: "努力",
        word_traditional: "努力",
        pinyin: "nǔlì",
        zh: "他学习很努力。",
        zh_traditional: "他學習很努力。",
        zh_pinyin: "tā xuéxí hěn nǔlì.",
        ko: "그는 공부를 매우 열심히 한다.",
        meaning_ko: "노력하다",
        meanings_extra: ["열심히 하다"],
        part_of_speech: "동사"
      },
      {
        no: 175,
        word: "爬山",
        word_traditional: "爬山",
        pinyin: "páshān",
        zh: "我们去爬山。",
        zh_traditional: "我們去爬山。",
        zh_pinyin: "wǒmen qù páshān.",
        ko: "우리는 등산하러 간다.",
        meaning_ko: "등산하다",
        meanings_extra: ["산을 오르다"],
        part_of_speech: "동사"
      },
      {
        no: 176,
        word: "盘子",
        word_traditional: "盤子",
        pinyin: "pánzi",
        zh: "盘子里有水果。",
        zh_traditional: "盤子裡有水果。",
        zh_pinyin: "pánzi lǐ yǒu shuǐguǒ.",
        ko: "접시 안에 과일이 있다.",
        meaning_ko: "접시",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 177,
        word: "胖",
        word_traditional: "胖",
        pinyin: "pàng",
        zh: "他有点胖。",
        zh_traditional: "他有點胖。",
        zh_pinyin: "tā yǒudiǎn pàng.",
        ko: "그는 조금 뚱뚱하다.",
        meaning_ko: "뚱뚱하다",
        meanings_extra: ["살찐다"],
        part_of_speech: "형용사"
      },
      {
        no: 178,
        word: "啤酒",
        word_traditional: "啤酒",
        pinyin: "píjiǔ",
        zh: "他喜欢喝啤酒。",
        zh_traditional: "他喜歡喝啤酒。",
        zh_pinyin: "tā xǐhuan hē píjiǔ.",
        ko: "그는 맥주 마시는 것을 좋아한다.",
        meaning_ko: "맥주",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 179,
        word: "皮鞋",
        word_traditional: "皮鞋",
        pinyin: "píxié",
        zh: "他穿着皮鞋。",
        zh_traditional: "他穿著皮鞋。",
        zh_pinyin: "tā chuānzhe píxié.",
        ko: "그는 구두를 신고 있다.",
        meaning_ko: "구두",
        meanings_extra: ["가죽 신발"],
        part_of_speech: "명사"
      },
      {
        no: 180,
        word: "瓶子",
        word_traditional: "瓶子",
        pinyin: "píngzi",
        zh: "桌子上有一个瓶子。",
        zh_traditional: "桌子上有一個瓶子。",
        zh_pinyin: "zhuōzi shàng yǒu yí gè píngzi.",
        ko: "탁자 위에 병 하나가 있다.",
        meaning_ko: "병",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 181,
        word: "其实",
        word_traditional: "其實",
        pinyin: "qíshí",
        zh: "其实我很喜欢学习。",
        zh_traditional: "其實我很喜歡學習。",
        zh_pinyin: "qíshí wǒ hěn xǐhuan xuéxí.",
        ko: "사실 나는 공부하는 것을 매우 좋아한다.",
        meaning_ko: "사실은, 실제로",
        meanings_extra: ["정말로"],
        part_of_speech: "부사"
      },
      {
        no: 182,
        word: "其他",
        word_traditional: "其他",
        pinyin: "qítā",
        zh: "其他人都来了。",
        zh_traditional: "其他人都來了。",
        zh_pinyin: "qítā rén dōu lái le.",
        ko: "다른 사람들은 모두 왔다.",
        meaning_ko: "다른, 그 밖의",
        meanings_extra: ["기타"],
        part_of_speech: "대명사"
      },
      {
        no: 183,
        word: "骑",
        word_traditional: "騎",
        pinyin: "qí",
        zh: "他骑自行车去学校。",
        zh_traditional: "他騎自行車去學校。",
        zh_pinyin: "tā qí zìxíngchē qù xuéxiào.",
        ko: "그는 자전거를 타고 학교에 간다.",
        meaning_ko: "타다 (자전거, 말 등)",
        meanings_extra: [],
        part_of_speech: "동사"
      },
      {
        no: 184,
        word: "奇怪",
        word_traditional: "奇怪",
        pinyin: "qíguài",
        zh: "这很奇怪。",
        zh_traditional: "這很奇怪。",
        zh_pinyin: "zhè hěn qíguài.",
        ko: "이것은 매우 이상하다.",
        meaning_ko: "이상하다, 이상한",
        meanings_extra: ["이상하게 여기다"],
        part_of_speech: "형용사"
      },
      {
        no: 185,
        word: "起来",
        word_traditional: "起來",
        pinyin: "qǐlái",
        zh: "他起来了。",
        zh_traditional: "他起來了。",
        zh_pinyin: "tā qǐlái le.",
        ko: "그가 일어났다.",
        meaning_ko: "일어나다, ~하기 시작하다",
        meanings_extra: ["~해 보이다"],
        part_of_speech: "보어"
      },
      {
        no: 186,
        word: "起飞",
        word_traditional: "起飛",
        pinyin: "qǐfēi",
        zh: "飞机马上起飞。",
        zh_traditional: "飛機馬上起飛。",
        zh_pinyin: "fēijī mǎshàng qǐfēi.",
        ko: "비행기가 곧 이륙한다.",
        meaning_ko: "이륙하다",
        meanings_extra: [],
        part_of_speech: "동사"
      },
      {
        no: 187,
        word: "清楚",
        word_traditional: "清楚",
        pinyin: "qīngchu",
        zh: "我听得很清楚。",
        zh_traditional: "我聽得很清楚。",
        zh_pinyin: "wǒ tīng de hěn qīngchu.",
        ko: "나는 아주 또렷하게 들었다.",
        meaning_ko: "명확하다, 분명하다",
        meanings_extra: ["뚜렷하다"],
        part_of_speech: "형용사"
      },
      {
        no: 188,
        word: "请假",
        word_traditional: "請假",
        pinyin: "qǐngjià",
        zh: "我明天要请假。",
        zh_traditional: "我明天要請假。",
        zh_pinyin: "wǒ míngtiān yào qǐngjià.",
        ko: "나는 내일 휴가를 신청해야 한다.",
        meaning_ko: "휴가를 신청하다",
        meanings_extra: ["휴가내다"],
        part_of_speech: "동사"
      },
      {
        no: 189,
        word: "秋",
        word_traditional: "秋",
        pinyin: "qiū",
        zh: "秋天很凉快。",
        zh_traditional: "秋天很涼快。",
        zh_pinyin: "qiūtiān hěn liángkuai.",
        ko: "가을은 매우 선선하다.",
        meaning_ko: "가을",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 190,
        word: "裙子",
        word_traditional: "裙子",
        pinyin: "qúnzi",
        zh: "她穿着漂亮的裙子。",
        zh_traditional: "她穿著漂亮的裙子。",
        zh_pinyin: "tā chuānzhe piàoliang de qúnzi.",
        ko: "그녀는 예쁜 치마를 입고 있다.",
        meaning_ko: "치마",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 191,
        word: "然后",
        word_traditional: "然後",
        pinyin: "ránhòu",
        zh: "我先吃饭，然后学习。",
        zh_traditional: "我先吃飯，然後學習。",
        zh_pinyin: "wǒ xiān chīfàn, ránhòu xuéxí.",
        ko: "나는 먼저 밥을 먹고, 그 다음 공부한다.",
        meaning_ko: "그리고 나서, 그 다음",
        meanings_extra: ["그 후"],
        part_of_speech: "부사"
      },
      {
        no: 192,
        word: "热情",
        word_traditional: "熱情",
        pinyin: "rèqíng",
        zh: "他很热情。",
        zh_traditional: "他很熱情。",
        zh_pinyin: "tā hěn rèqíng.",
        ko: "그는 매우 친절하다.",
        meaning_ko: "열정적이다, 친절하다",
        meanings_extra: ["정열적이다"],
        part_of_speech: "형용사"
      },
      {
        no: 193,
        word: "认为",
        word_traditional: "認為",
        pinyin: "rènwéi",
        zh: "我认为他说得对。",
        zh_traditional: "我認為他說得對。",
        zh_pinyin: "wǒ rènwéi tā shuō de duì.",
        ko: "나는 그가 옳다고 생각한다.",
        meaning_ko: "생각하다, 여기다",
        meanings_extra: ["판단하다"],
        part_of_speech: "동사"
      },
      {
        no: 194,
        word: "认真",
        word_traditional: "認真",
        pinyin: "rènzhēn",
        zh: "他学习很认真。",
        zh_traditional: "他學習很認真。",
        zh_pinyin: "tā xuéxí hěn rènzhēn.",
        ko: "그는 공부를 매우 열심히 한다.",
        meaning_ko: "진지하다, 성실하다",
        meanings_extra: ["열심히 하다"],
        part_of_speech: "형용사"
      },
      {
        no: 195,
        word: "容易",
        word_traditional: "容易",
        pinyin: "róngyì",
        zh: "这件事很容易。",
        zh_traditional: "這件事很容易。",
        zh_pinyin: "zhè jiàn shì hěn róngyì.",
        ko: "이 일은 매우 쉽다.",
        meaning_ko: "쉽다",
        meanings_extra: ["용이하다"],
        part_of_speech: "형용사"
      },
      {
        no: 196,
        word: "如果",
        word_traditional: "如果",
        pinyin: "rúguǒ",
        zh: "如果明天下雨，我不去。",
        zh_traditional: "如果明天下雨，我不去。",
        zh_pinyin: "rúguǒ míngtiān xiàyǔ, wǒ bù qù.",
        ko: "만약 내일 비가 오면, 나는 가지 않는다.",
        meaning_ko: "만약 ~라면",
        meanings_extra: ["조건절"],
        part_of_speech: "접속사"
      },
      {
        no: 197,
        word: "伞",
        word_traditional: "傘",
        pinyin: "sǎn",
        zh: "请带伞。",
        zh_traditional: "請帶傘。",
        zh_pinyin: "qǐng dài sǎn.",
        ko: "우산을 가져오세요.",
        meaning_ko: "우산",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 198,
        word: "上网",
        word_traditional: "上網",
        pinyin: "shàngwǎng",
        zh: "我每天上网。",
        zh_traditional: "我每天上網。",
        zh_pinyin: "wǒ měitiān shàngwǎng.",
        ko: "나는 매일 인터넷을 한다.",
        meaning_ko: "인터넷에 접속하다",
        meanings_extra: ["웹서핑하다"],
        part_of_speech: "동사"
      },
      {
        no: 199,
        word: "生气",
        word_traditional: "生氣",
        pinyin: "shēngqì",
        zh: "他很生气。",
        zh_traditional: "他很生氣。",
        zh_pinyin: "tā hěn shēngqì.",
        ko: "그는 매우 화가 났다.",
        meaning_ko: "화내다, 성내다",
        meanings_extra: [],
        part_of_speech: "동사"
      },
      {
        no: 200,
        word: "声音",
        word_traditional: "聲音",
        pinyin: "shēngyīn",
        zh: "她的声音很好听。",
        zh_traditional: "她的聲音很好聽。",
        zh_pinyin: "tā de shēngyīn hěn hǎotīng.",
        ko: "그녀의 목소리가 매우 듣기 좋다.",
        meaning_ko: "소리, 목소리",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 201,
        word: "试",
        word_traditional: "試",
        pinyin: "shì",
        zh: "我想试一试。",
        zh_traditional: "我想試一試。",
        zh_pinyin: "wǒ xiǎng shì yí shì.",
        ko: "나는 한번 해보고 싶다.",
        meaning_ko: "시험하다, 시도하다",
        meanings_extra: ["시험", "도전하다"],
        part_of_speech: "동사"
      },
      {
        no: 202,
        word: "世界",
        word_traditional: "世界",
        pinyin: "shìjiè",
        zh: "世界很大。",
        zh_traditional: "世界很大。",
        zh_pinyin: "shìjiè hěn dà.",
        ko: "세상은 매우 크다.",
        meaning_ko: "세계",
        meanings_extra: ["세상"],
        part_of_speech: "명사"
      },
      {
        no: 203,
        word: "瘦",
        word_traditional: "瘦",
        pinyin: "shòu",
        zh: "他很瘦。",
        zh_traditional: "他很瘦。",
        zh_pinyin: "tā hěn shòu.",
        ko: "그는 매우 마르다.",
        meaning_ko: "마르다, 날씬하다",
        meanings_extra: ["얇다"],
        part_of_speech: "형용사"
      },
      {
        no: 204,
        word: "舒服",
        word_traditional: "舒服",
        pinyin: "shūfu",
        zh: "我感觉很舒服。",
        zh_traditional: "我感覺很舒服。",
        zh_pinyin: "wǒ gǎnjué hěn shūfu.",
        ko: "나는 매우 편안하다.",
        meaning_ko: "편안하다, 쾌적하다",
        meanings_extra: [],
        part_of_speech: "형용사"
      },
      {
        no: 205,
        word: "叔叔",
        word_traditional: "叔叔",
        pinyin: "shūshu",
        zh: "我叔叔是医生。",
        zh_traditional: "我叔叔是醫生。",
        zh_pinyin: "wǒ shūshu shì yīshēng.",
        ko: "내 삼촌은 의사이다.",
        meaning_ko: "삼촌",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 206,
        word: "树",
        word_traditional: "樹",
        pinyin: "shù",
        zh: "树很高。",
        zh_traditional: "樹很高。",
        zh_pinyin: "shù hěn gāo.",
        ko: "나무가 매우 크다.",
        meaning_ko: "나무",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 207,
        word: "数学",
        word_traditional: "數學",
        pinyin: "shùxué",
        zh: "我喜欢数学。",
        zh_traditional: "我喜歡數學。",
        zh_pinyin: "wǒ xǐhuan shùxué.",
        ko: "나는 수학을 좋아한다.",
        meaning_ko: "수학",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 208,
        word: "刷牙",
        word_traditional: "刷牙",
        pinyin: "shuāyá",
        zh: "我每天刷牙两次。",
        zh_traditional: "我每天刷牙兩次。",
        zh_pinyin: "wǒ měitiān shuāyá liǎng cì.",
        ko: "나는 매일 두 번 이를 닦는다.",
        meaning_ko: "양치질하다",
        meanings_extra: [],
        part_of_speech: "동사"
      },
      {
        no: 209,
        word: "双",
        word_traditional: "雙",
        pinyin: "shuāng",
        zh: "我买了一双鞋。",
        zh_traditional: "我買了一雙鞋。",
        zh_pinyin: "wǒ mǎi le yì shuāng xié.",
        ko: "나는 신발 한 켤레를 샀다.",
        meaning_ko: "쌍, 켤레",
        meanings_extra: ["짝"],
        part_of_speech: "양사"
      },
      {
        no: 210,
        word: "水平",
        word_traditional: "水平",
        pinyin: "shuǐpíng",
        zh: "我的中文水平很好。",
        zh_traditional: "我的中文水平很好。",
        zh_pinyin: "wǒ de Zhōngwén shuǐpíng hěn hǎo.",
        ko: "내 중국어 실력이 매우 좋다.",
        meaning_ko: "수준",
        meanings_extra: ["레벨"],
        part_of_speech: "명사"
      },
      {
        no: 211,
        word: "司机",
        word_traditional: "司機",
        pinyin: "sījī",
        zh: "司机开车很快。",
        zh_traditional: "司機開車很快。",
        zh_pinyin: "sījī kāichē hěn kuài.",
        ko: "운전사가 차를 매우 빨리 운전한다.",
        meaning_ko: "운전사",
        meanings_extra: ["기사"],
        part_of_speech: "명사"
      },
      {
        no: 212,
        word: "太阳",
        word_traditional: "太陽",
        pinyin: "tàiyáng",
        zh: "太阳很大。",
        zh_traditional: "太陽很大。",
        zh_pinyin: "tàiyáng hěn dà.",
        ko: "태양이 매우 크다.",
        meaning_ko: "태양",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 213,
        word: "特别",
        word_traditional: "特別",
        pinyin: "tèbié",
        zh: "我特别喜欢这个电影。",
        zh_traditional: "我特別喜歡這個電影。",
        zh_pinyin: "wǒ tèbié xǐhuan zhège diànyǐng.",
        ko: "나는 이 영화를 특히 좋아한다.",
        meaning_ko: "특별히",
        meanings_extra: ["특이하게"],
        part_of_speech: "부사"
      },
      {
        no: 214,
        word: "疼",
        word_traditional: "疼",
        pinyin: "téng",
        zh: "我的头很疼。",
        zh_traditional: "我的頭很疼。",
        zh_pinyin: "wǒ de tóu hěn téng.",
        ko: "내 머리가 매우 아프다.",
        meaning_ko: "아프다",
        meanings_extra: ["통증이 있다"],
        part_of_speech: "형용사"
      },
      {
        no: 215,
        word: "提高",
        word_traditional: "提高",
        pinyin: "tígāo",
        zh: "我想提高中文水平。",
        zh_traditional: "我想提高中文水平。",
        zh_pinyin: "wǒ xiǎng tígāo Zhōngwén shuǐpíng.",
        ko: "나는 중국어 실력을 향상시키고 싶다.",
        meaning_ko: "향상시키다",
        meanings_extra: ["증가시키다"],
        part_of_speech: "동사"
      },
      {
        no: 216,
        word: "体育",
        word_traditional: "體育",
        pinyin: "tǐyù",
        zh: "我喜欢体育运动。",
        zh_traditional: "我喜歡體育運動。",
        zh_pinyin: "wǒ xǐhuan tǐyù yùndòng.",
        ko: "나는 스포츠를 좋아한다.",
        meaning_ko: "체육, 스포츠",
        meanings_extra: ["운동"],
        part_of_speech: "명사"
      },
      {
        no: 217,
        word: "甜",
        word_traditional: "甜",
        pinyin: "tián",
        zh: "这个苹果很甜。",
        zh_traditional: "這個蘋果很甜。",
        zh_pinyin: "zhège píngguǒ hěn tián.",
        ko: "이 사과는 매우 달다.",
        meaning_ko: "달다",
        meanings_extra: ["달콤하다"],
        part_of_speech: "형용사"
      },
      {
        no: 218,
        word: "条",
        word_traditional: "條",
        pinyin: "tiáo",
        zh: "这条裤子很长。",
        zh_traditional: "這條褲子很長。",
        zh_pinyin: "zhè tiáo kùzi hěn cháng.",
        ko: "이 바지는 매우 길다.",
        meaning_ko: "가늘고 긴 것(양사)",
        meanings_extra: ["조각", "한 줄"],
        part_of_speech: "양사"
      },
      {
        no: 219,
        word: "同事",
        word_traditional: "同事",
        pinyin: "tóngshì",
        zh: "他是我的同事。",
        zh_traditional: "他是我的同事。",
        zh_pinyin: "tā shì wǒ de tóngshì.",
        ko: "그는 내 동료이다.",
        meaning_ko: "동료, 직장 동료",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 220,
        word: "同意",
        word_traditional: "同意",
        pinyin: "tóngyì",
        zh: "我同意你的意见。",
        zh_traditional: "我同意你的意見。",
        zh_pinyin: "wǒ tóngyì nǐ de yìjiàn.",
        ko: "나는 네 의견에 동의한다.",
        meaning_ko: "동의하다",
        meanings_extra: ["승낙하다"],
        part_of_speech: "동사"
      },
      {
        no: 221,
        word: "头发",
        word_traditional: "頭髮",
        pinyin: "tóufa",
        zh: "她的头发很长。",
        zh_traditional: "她的頭髮很長。",
        zh_pinyin: "tā de tóufa hěn cháng.",
        ko: "그녀의 머리카락이 매우 길다.",
        meaning_ko: "머리카락",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 222,
        word: "突然",
        word_traditional: "突然",
        pinyin: "tūrán",
        zh: "天气突然变冷。",
        zh_traditional: "天氣突然變冷。",
        zh_pinyin: "tiānqì tūrán biàn lěng.",
        ko: "날씨가 갑자기 추워졌다.",
        meaning_ko: "갑자기",
        meanings_extra: ["돌연히"],
        part_of_speech: "부사"
      },
      {
        no: 223,
        word: "图书馆",
        word_traditional: "圖書館",
        pinyin: "túshūguǎn",
        zh: "我去图书馆学习。",
        zh_traditional: "我去圖書館學習。",
        zh_pinyin: "wǒ qù túshūguǎn xuéxí.",
        ko: "나는 도서관에 공부하러 간다.",
        meaning_ko: "도서관",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 224,
        word: "腿",
        word_traditional: "腿",
        pinyin: "tuǐ",
        zh: "他的腿受伤了。",
        zh_traditional: "他的腿受傷了。",
        zh_pinyin: "tā de tuǐ shòushāng le.",
        ko: "그의 다리가 다쳤다.",
        meaning_ko: "다리",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 225,
        word: "完成",
        word_traditional: "完成",
        pinyin: "wánchéng",
        zh: "我完成了作业。",
        zh_traditional: "我完成了作業。",
        zh_pinyin: "wǒ wánchéng le zuòyè.",
        ko: "나는 숙제를 완성했다.",
        meaning_ko: "완성하다",
        meanings_extra: ["끝내다"],
        part_of_speech: "동사"
      },
      {
        no: 226,
        word: "碗",
        word_traditional: "碗",
        pinyin: "wǎn",
        zh: "我吃了一碗饭。",
        zh_traditional: "我吃了一碗飯。",
        zh_pinyin: "wǒ chī le yì wǎn fàn.",
        ko: "나는 밥 한 그릇을 먹었다.",
        meaning_ko: "그릇",
        meanings_extra: ["사발"],
        part_of_speech: "명사"
      },
      {
        no: 227,
        word: "万",
        word_traditional: "萬",
        pinyin: "wàn",
        zh: "一万个人来了。",
        zh_traditional: "一萬個人來了。",
        zh_pinyin: "yí wàn gè rén lái le.",
        ko: "만 명이 왔다.",
        meaning_ko: "만 (숫자)",
        meanings_extra: ["10,000"],
        part_of_speech: "수사"
      },
      {
        no: 228,
        word: "忘记",
        word_traditional: "忘記",
        pinyin: "wàngjì",
        zh: "我忘记了他的名字。",
        zh_traditional: "我忘記了他的名字。",
        zh_pinyin: "wǒ wàngjì le tā de míngzi.",
        ko: "나는 그의 이름을 잊었다.",
        meaning_ko: "잊다",
        meanings_extra: [],
        part_of_speech: "동사"
      },
      {
        no: 229,
        word: "为",
        word_traditional: "為",
        pinyin: "wèi",
        zh: "我为你高兴。",
        zh_traditional: "我為你高興。",
        zh_pinyin: "wǒ wèi nǐ gāoxìng.",
        ko: "나는 네가 기뻐서 기쁘다.",
        meaning_ko: "~을 위해",
        meanings_extra: ["~때문에"],
        part_of_speech: "전치사"
      },
      {
        no: 230,
        word: "为了",
        word_traditional: "為了",
        pinyin: "wèile",
        zh: "我为了健康锻炼。",
        zh_traditional: "我為了健康鍛鍊。",
        zh_pinyin: "wǒ wèile jiànkāng duànliàn.",
        ko: "나는 건강을 위해 운동한다.",
        meaning_ko: "~하기 위해서",
        meanings_extra: ["목적"],
        part_of_speech: "전치사"
      },
      {
        no: 231,
        word: "位",
        word_traditional: "位",
        pinyin: "wèi",
        zh: "这是一位老师。",
        zh_traditional: "這是一位老師。",
        zh_pinyin: "zhè shì yí wèi lǎoshī.",
        ko: "이분은 선생님이다.",
        meaning_ko: "분 (존칭 양사)",
        meanings_extra: ["자리"],
        part_of_speech: "양사"
      },
      {
        no: 232,
        word: "文化",
        word_traditional: "文化",
        pinyin: "wénhuà",
        zh: "中国文化很丰富。",
        zh_traditional: "中國文化很豐富。",
        zh_pinyin: "Zhōngguó wénhuà hěn fēngfù.",
        ko: "중국 문화는 매우 풍부하다.",
        meaning_ko: "문화",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 233,
        word: "西",
        word_traditional: "西",
        pinyin: "xī",
        zh: "太阳从西边落下。",
        zh_traditional: "太陽從西邊落下。",
        zh_pinyin: "tàiyáng cóng xībiān luò xià.",
        ko: "태양은 서쪽으로 진다.",
        meaning_ko: "서쪽",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 234,
        word: "习惯",
        word_traditional: "習慣",
        pinyin: "xíguàn",
        zh: "我习惯早起。",
        zh_traditional: "我習慣早起。",
        zh_pinyin: "wǒ xíguàn zǎoqǐ.",
        ko: "나는 일찍 일어나는 습관이 있다.",
        meaning_ko: "습관",
        meanings_extra: ["익숙하다"],
        part_of_speech: "명사/동사"
      },
      {
        no: 235,
        word: "洗手间",
        word_traditional: "洗手間",
        pinyin: "xǐshǒujiān",
        zh: "洗手间在哪里？",
        zh_traditional: "洗手間在哪裡？",
        zh_pinyin: "xǐshǒujiān zài nǎlǐ?",
        ko: "화장실이 어디 있나요?",
        meaning_ko: "화장실",
        meanings_extra: ["세면실"],
        part_of_speech: "명사"
      },
      {
        no: 236,
        word: "洗澡",
        word_traditional: "洗澡",
        pinyin: "xǐzǎo",
        zh: "我每天洗澡。",
        zh_traditional: "我每天洗澡。",
        zh_pinyin: "wǒ měitiān xǐzǎo.",
        ko: "나는 매일 샤워한다.",
        meaning_ko: "목욕하다, 샤워하다",
        meanings_extra: [],
        part_of_speech: "동사"
      },
      {
        no: 237,
        word: "夏",
        word_traditional: "夏",
        pinyin: "xià",
        zh: "夏天很热。",
        zh_traditional: "夏天很熱。",
        zh_pinyin: "xiàtiān hěn rè.",
        ko: "여름은 매우 덥다.",
        meaning_ko: "여름",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 238,
        word: "先",
        word_traditional: "先",
        pinyin: "xiān",
        zh: "我们先吃饭。",
        zh_traditional: "我們先吃飯。",
        zh_pinyin: "wǒmen xiān chīfàn.",
        ko: "우리는 먼저 밥을 먹는다.",
        meaning_ko: "먼저",
        meanings_extra: ["우선"],
        part_of_speech: "부사"
      },
      {
        no: 239,
        word: "香蕉",
        word_traditional: "香蕉",
        pinyin: "xiāngjiāo",
        zh: "我喜欢吃香蕉。",
        zh_traditional: "我喜歡吃香蕉。",
        zh_pinyin: "wǒ xǐhuan chī xiāngjiāo.",
        ko: "나는 바나나 먹는 것을 좋아한다.",
        meaning_ko: "바나나",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 240,
        word: "相信",
        word_traditional: "相信",
        pinyin: "xiāngxìn",
        zh: "我相信你。",
        zh_traditional: "我相信你。",
        zh_pinyin: "wǒ xiāngxìn nǐ.",
        ko: "나는 너를 믿는다.",
        meaning_ko: "믿다",
        meanings_extra: ["신뢰하다"],
        part_of_speech: "동사"
      },
      {
        no: 241,
        word: "向",
        word_traditional: "向",
        pinyin: "xiàng",
        zh: "他向我走来。",
        zh_traditional: "他向我走來。",
        zh_pinyin: "tā xiàng wǒ zǒu lái.",
        ko: "그가 나에게 걸어온다.",
        meaning_ko: "~쪽으로",
        meanings_extra: ["향하여"],
        part_of_speech: "전치사"
      },
      {
        no: 242,
        word: "像",
        word_traditional: "像",
        pinyin: "xiàng",
        zh: "他像他的爸爸。",
        zh_traditional: "他像他的爸爸。",
        zh_pinyin: "tā xiàng tā de bàba.",
        ko: "그는 그의 아버지를 닮았다.",
        meaning_ko: "~처럼 보이다, 닮다",
        meanings_extra: ["이미지", "모습"],
        part_of_speech: "동사/명사"
      },
      {
        no: 243,
        word: "小心",
        word_traditional: "小心",
        pinyin: "xiǎoxīn",
        zh: "小心地滑。",
        zh_traditional: "小心地滑。",
        zh_pinyin: "xiǎoxīn dì huá.",
        ko: "바닥이 미끄러우니 조심하세요.",
        meaning_ko: "조심하다",
        meanings_extra: ["주의하다"],
        part_of_speech: "동사"
      },
      {
        no: 244,
        word: "校长",
        word_traditional: "校長",
        pinyin: "xiàozhǎng",
        zh: "校长在办公室。",
        zh_traditional: "校長在辦公室。",
        zh_pinyin: "xiàozhǎng zài bàngōngshì.",
        ko: "교장 선생님은 사무실에 있다.",
        meaning_ko: "교장 선생님",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 245,
        word: "新闻",
        word_traditional: "新聞",
        pinyin: "xīnwén",
        zh: "我每天看新闻。",
        zh_traditional: "我每天看新聞。",
        zh_pinyin: "wǒ měitiān kàn xīnwén.",
        ko: "나는 매일 뉴스를 본다.",
        meaning_ko: "뉴스",
        meanings_extra: ["소식"],
        part_of_speech: "명사"
      },
      {
        no: 246,
        word: "新鲜",
        word_traditional: "新鮮",
        pinyin: "xīnxiān",
        zh: "水果很新鲜。",
        zh_traditional: "水果很新鮮。",
        zh_pinyin: "shuǐguǒ hěn xīnxiān.",
        ko: "과일이 매우 신선하다.",
        meaning_ko: "신선하다",
        meanings_extra: ["싱싱하다"],
        part_of_speech: "형용사"
      },
      {
        no: 247,
        word: "信用卡",
        word_traditional: "信用卡",
        pinyin: "xìnyòngkǎ",
        zh: "我用信用卡付款。",
        zh_traditional: "我用信用卡付款。",
        zh_pinyin: "wǒ yòng xìnyòngkǎ fùkuǎn.",
        ko: "나는 신용카드로 결제한다.",
        meaning_ko: "신용카드",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 248,
        word: "行李箱",
        word_traditional: "行李箱",
        pinyin: "xínglixiāng",
        zh: "我的行李箱很大。",
        zh_traditional: "我的行李箱很大。",
        zh_pinyin: "wǒ de xínglixiāng hěn dà.",
        ko: "내 여행 가방은 크다.",
        meaning_ko: "여행 가방",
        meanings_extra: ["캐리어"],
        part_of_speech: "명사"
      },
      {
        no: 249,
        word: "熊猫",
        word_traditional: "熊貓",
        pinyin: "xióngmāo",
        zh: "熊猫很可爱。",
        zh_traditional: "熊貓很可愛。",
        zh_pinyin: "xióngmāo hěn kě'ài.",
        ko: "팬더는 매우 귀엽다.",
        meaning_ko: "팬더",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 250,
        word: "需要",
        word_traditional: "需要",
        pinyin: "xūyào",
        zh: "我需要帮助。",
        zh_traditional: "我需要幫助。",
        zh_pinyin: "wǒ xūyào bāngzhù.",
        ko: "나는 도움이 필요하다.",
        meaning_ko: "필요하다",
        meanings_extra: ["요구하다"],
        part_of_speech: "동사"
      },
      {
        no: 251,
        word: "选择",
        word_traditional: "選擇",
        pinyin: "xuǎnzé",
        zh: "你选择哪个？",
        zh_traditional: "你選擇哪個？",
        zh_pinyin: "nǐ xuǎnzé nǎ ge?",
        ko: "너는 어느 것을 선택하니?",
        meaning_ko: "선택하다",
        meanings_extra: ["고르다"],
        part_of_speech: "동사"
      },
      {
        no: 252,
        word: "要求",
        word_traditional: "要求",
        pinyin: "yāoqiú",
        zh: "我有一些要求。",
        zh_traditional: "我有一些要求。",
        zh_pinyin: "wǒ yǒu yìxiē yāoqiú.",
        ko: "나는 몇 가지 요구가 있다.",
        meaning_ko: "요구하다",
        meanings_extra: ["요청하다"],
        part_of_speech: "동사"
      },
      {
        no: 253,
        word: "爷爷",
        word_traditional: "爺爺",
        pinyin: "yéye",
        zh: "爷爷喜欢讲故事。",
        zh_traditional: "爺爺喜歡講故事。",
        zh_pinyin: "yéye xǐhuan jiǎng gùshi.",
        ko: "할아버지는 이야기하는 것을 좋아한다.",
        meaning_ko: "할아버지",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 254,
        word: "一定",
        word_traditional: "一定",
        pinyin: "yídìng",
        zh: "你一定能成功。",
        zh_traditional: "你一定能成功。",
        zh_pinyin: "nǐ yídìng néng chénggōng.",
        ko: "너는 반드시 성공할 것이다.",
        meaning_ko: "반드시",
        meanings_extra: ["틀림없이"],
        part_of_speech: "부사"
      },
      {
        no: 255,
        word: "一共",
        word_traditional: "一共",
        pinyin: "yígòng",
        zh: "我们一共有十个人。",
        zh_traditional: "我們一共有十個人。",
        zh_pinyin: "wǒmen yígòng yǒu shí gè rén.",
        ko: "우리는 총 10명이다.",
        meaning_ko: "합쳐서, 총",
        meanings_extra: ["모두 합쳐"],
        part_of_speech: "부사"
      },
      {
        no: 256,
        word: "一会儿",
        word_traditional: "一會兒",
        pinyin: "yíhuìr",
        zh: "我等你一会儿。",
        zh_traditional: "我等你一會兒。",
        zh_pinyin: "wǒ děng nǐ yíhuìr.",
        ko: "나는 너를 잠시 기다리겠다.",
        meaning_ko: "잠시, 조금 있다가",
        meanings_extra: ["곧"],
        part_of_speech: "명사/부사"
      },
      {
        no: 257,
        word: "一样",
        word_traditional: "一樣",
        pinyin: "yíyàng",
        zh: "我们穿一样的衣服。",
        zh_traditional: "我們穿一樣的衣服。",
        zh_pinyin: "wǒmen chuān yíyàng de yīfu.",
        ko: "우리는 같은 옷을 입었다.",
        meaning_ko: "같다, 동일하다",
        meanings_extra: ["마찬가지"],
        part_of_speech: "형용사"
      },
      {
        no: 258,
        word: "以前",
        word_traditional: "以前",
        pinyin: "yǐqián",
        zh: "我以前住在北京。",
        zh_traditional: "我以前住在北京。",
        zh_pinyin: "wǒ yǐqián zhù zài Běijīng.",
        ko: "나는 전에 베이징에 살았다.",
        meaning_ko: "전에, 이전에",
        meanings_extra: ["과거"],
        part_of_speech: "명사/부사"
      },
      {
        no: 259,
        word: "一般",
        word_traditional: "一般",
        pinyin: "yìbān",
        zh: "我一般早上六点起床。",
        zh_traditional: "我一般早上六點起床。",
        zh_pinyin: "wǒ yìbān zǎoshang liù diǎn qǐchuáng.",
        ko: "나는 보통 아침 6시에 일어난다.",
        meaning_ko: "보통, 일반적이다",
        meanings_extra: ["대체로"],
        part_of_speech: "부사/형용사"
      },
      {
        no: 260,
        word: "一边",
        word_traditional: "一邊",
        pinyin: "yìbiān",
        zh: "我一边吃饭一边看书。",
        zh_traditional: "我一邊吃飯一邊看書。",
        zh_pinyin: "wǒ yìbiān chīfàn yìbiān kàn shū.",
        ko: "나는 밥을 먹으면서 책을 본다.",
        meaning_ko: "~하면서",
        meanings_extra: ["동시에"],
        part_of_speech: "부사"
      },
      {
        no: 261,
        word: "一直",
        word_traditional: "一直",
        pinyin: "yìzhí",
        zh: "我一直学习中文。",
        zh_traditional: "我一直學習中文。",
        zh_pinyin: "wǒ yìzhí xuéxí Zhōngwén.",
        ko: "나는 계속해서 중국어를 공부한다.",
        meaning_ko: "계속, 줄곧",
        meanings_extra: ["항상"],
        part_of_speech: "부사"
      },
      {
        no: 262,
        word: "音乐",
        word_traditional: "音樂",
        pinyin: "yīnyuè",
        zh: "我喜欢听音乐。",
        zh_traditional: "我喜歡聽音樂。",
        zh_pinyin: "wǒ xǐhuan tīng yīnyuè.",
        ko: "나는 음악 듣는 것을 좋아한다.",
        meaning_ko: "음악",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 263,
        word: "银行",
        word_traditional: "銀行",
        pinyin: "yínháng",
        zh: "银行就在前面。",
        zh_traditional: "銀行就在前面。",
        zh_pinyin: "yínháng jiù zài qiánmiàn.",
        ko: "은행은 바로 앞에 있다.",
        meaning_ko: "은행",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 264,
        word: "饮料",
        word_traditional: "飲料",
        pinyin: "yǐnliào",
        zh: "我买了饮料。",
        zh_traditional: "我買了飲料。",
        zh_pinyin: "wǒ mǎi le yǐnliào.",
        ko: "나는 음료를 샀다.",
        meaning_ko: "음료",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 265,
        word: "应该",
        word_traditional: "應該",
        pinyin: "yīnggāi",
        zh: "你应该多休息。",
        zh_traditional: "你應該多休息。",
        zh_pinyin: "nǐ yīnggāi duō xiūxi.",
        ko: "너는 좀 더 쉬어야 한다.",
        meaning_ko: "~해야 한다",
        meanings_extra: ["마땅히"],
        part_of_speech: "조동사"
      },
      {
        no: 266,
        word: "影响",
        word_traditional: "影響",
        pinyin: "yǐngxiǎng",
        zh: "他的话影响了我。",
        zh_traditional: "他的話影響了我。",
        zh_pinyin: "tā de huà yǐngxiǎng le wǒ.",
        ko: "그의 말이 나에게 영향을 주었다.",
        meaning_ko: "영향을 미치다",
        meanings_extra: ["영향력"],
        part_of_speech: "동사/명사"
      },
      {
        no: 267,
        word: "用",
        word_traditional: "用",
        pinyin: "yòng",
        zh: "我用手机上网。",
        zh_traditional: "我用手機上網。",
        zh_pinyin: "wǒ yòng shǒujī shàngwǎng.",
        ko: "나는 휴대폰으로 인터넷을 한다.",
        meaning_ko: "사용하다",
        meanings_extra: ["이용하다"],
        part_of_speech: "동사"
      },
      {
        no: 268,
        word: "游戏",
        word_traditional: "遊戲",
        pinyin: "yóuxì",
        zh: "孩子们喜欢玩游戏。",
        zh_traditional: "孩子們喜歡玩遊戲。",
        zh_pinyin: "háizi men xǐhuan wán yóuxì.",
        ko: "아이들은 게임하는 것을 좋아한다.",
        meaning_ko: "게임",
        meanings_extra: ["놀이"],
        part_of_speech: "명사"
      },
      {
        no: 269,
        word: "有名",
        word_traditional: "有名",
        pinyin: "yǒumíng",
        zh: "他是一位有名的演员。",
        zh_traditional: "他是一位有名的演員。",
        zh_pinyin: "tā shì yí wèi yǒumíng de yǎnyuán.",
        ko: "그는 유명한 배우이다.",
        meaning_ko: "유명하다",
        meanings_extra: ["저명하다"],
        part_of_speech: "형용사"
      },
      {
        no: 270,
        word: "又",
        word_traditional: "又",
        pinyin: "yòu",
        zh: "他又高又帅。",
        zh_traditional: "他又高又帥。",
        zh_pinyin: "tā yòu gāo yòu shuài.",
        ko: "그는 키도 크고 잘생겼다.",
        meaning_ko: "~하고 또 ~하다",
        meanings_extra: ["다시"],
        part_of_speech: "부사"
      },
      {
        no: 271,
        word: "遇到",
        word_traditional: "遇到",
        pinyin: "yùdào",
        zh: "我遇到了老朋友。",
        zh_traditional: "我遇到了老朋友。",
        zh_pinyin: "wǒ yùdào le lǎo péngyou.",
        ko: "나는 오랜 친구를 만났다.",
        meaning_ko: "마주치다, 만나다",
        meanings_extra: ["부딪치다"],
        part_of_speech: "동사"
      },
      {
        no: 272,
        word: "元",
        word_traditional: "元",
        pinyin: "yuán",
        zh: "这个东西十元。",
        zh_traditional: "這個東西十元。",
        zh_pinyin: "zhège dōngxi shí yuán.",
        ko: "이 물건은 10위안이다.",
        meaning_ko: "위안 (화폐 단위)",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 273,
        word: "愿意",
        word_traditional: "願意",
        pinyin: "yuànyì",
        zh: "我愿意帮助你。",
        zh_traditional: "我願意幫助你。",
        zh_pinyin: "wǒ yuànyì bāngzhù nǐ.",
        ko: "나는 기꺼이 너를 도와주겠다.",
        meaning_ko: "기꺼이 ~하다",
        meanings_extra: ["원하다"],
        part_of_speech: "동사"
      },
      {
        no: 274,
        word: "月亮",
        word_traditional: "月亮",
        pinyin: "yuèliang",
        zh: "月亮很圆。",
        zh_traditional: "月亮很圓。",
        zh_pinyin: "yuèliang hěn yuán.",
        ko: "달이 매우 둥글다.",
        meaning_ko: "달",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 275,
        word: "越",
        word_traditional: "越",
        pinyin: "yuè",
        zh: "天气越冷越想喝热茶。",
        zh_traditional: "天氣越冷越想喝熱茶。",
        zh_pinyin: "tiānqì yuè lěng yuè xiǎng hē rè chá.",
        ko: "날씨가 추울수록 따뜻한 차가 마시고 싶다.",
        meaning_ko: "~할수록",
        meanings_extra: ["더욱"],
        part_of_speech: "부사"
      },
      {
        no: 276,
        word: "站",
        word_traditional: "站",
        pinyin: "zhàn",
        zh: "我在车站等你。",
        zh_traditional: "我在車站等你。",
        zh_pinyin: "wǒ zài chēzhàn děng nǐ.",
        ko: "나는 역에서 너를 기다린다.",
        meaning_ko: "역, 서다",
        meanings_extra: ["정류장"],
        part_of_speech: "명사/동사"
      },
      {
        no: 277,
        word: "张",
        word_traditional: "張",
        pinyin: "zhāng",
        zh: "我有一张桌子。",
        zh_traditional: "我有一張桌子。",
        zh_pinyin: "wǒ yǒu yì zhāng zhuōzi.",
        ko: "나는 책상 하나가 있다.",
        meaning_ko: "장 (평평한 물건 단위)",
        meanings_extra: ["종이장"],
        part_of_speech: "양사"
      },
      {
        no: 278,
        word: "长",
        word_traditional: "長",
        pinyin: "zhǎng",
        zh: "头发长了。",
        zh_traditional: "頭髮長了。",
        zh_pinyin: "tóufa zhǎng le.",
        ko: "머리카락이 길어졌다.",
        meaning_ko: "길다, 자라다",
        meanings_extra: ["성장하다"],
        part_of_speech: "형용사/동사"
      },
      {
        no: 279,
        word: "着急",
        word_traditional: "著急",
        pinyin: "zháojí",
        zh: "不要着急。",
        zh_traditional: "不要著急。",
        zh_pinyin: "bù yào zháojí.",
        ko: "걱정하지 마세요.",
        meaning_ko: "초조하다, 걱정하다",
        meanings_extra: ["급하다"],
        part_of_speech: "형용사"
      },
      {
        no: 280,
        word: "照顾",
        word_traditional: "照顧",
        pinyin: "zhàogù",
        zh: "他照顾生病的妈妈。",
        zh_traditional: "他照顧生病的媽媽。",
        zh_pinyin: "tā zhàogù shēngbìng de māma.",
        ko: "그는 아픈 엄마를 돌본다.",
        meaning_ko: "돌보다, 보살피다",
        meanings_extra: [],
        part_of_speech: "동사"
      },
      {
        no: 281,
        word: "照片",
        word_traditional: "照片",
        pinyin: "zhàopiàn",
        zh: "我拍了一张照片。",
        zh_traditional: "我拍了一張照片。",
        zh_pinyin: "wǒ pāi le yì zhāng zhàopiàn.",
        ko: "나는 사진 한 장을 찍었다.",
        meaning_ko: "사진",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 282,
        word: "照相机",
        word_traditional: "照相機",
        pinyin: "zhàoxiàngjī",
        zh: "他用照相机拍照。",
        zh_traditional: "他用照相機拍照。",
        zh_pinyin: "tā yòng zhàoxiàngjī pāizhào.",
        ko: "그는 카메라로 사진을 찍는다.",
        meaning_ko: "카메라",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 283,
        word: "只",
        word_traditional: "只",
        pinyin: "zhī",
        zh: "我有一只猫。",
        zh_traditional: "我有一隻貓。",
        zh_pinyin: "wǒ yǒu yì zhī māo.",
        ko: "나는 고양이 한 마리가 있다.",
        meaning_ko: "(동물 등을 세는) 마리, 짝",
        meanings_extra: ["양사"],
        part_of_speech: "양사"
      },
      {
        no: 284,
        word: "只",
        word_traditional: "只",
        pinyin: "zhǐ",
        zh: "我只喜欢你。",
        zh_traditional: "我只喜歡你。",
        zh_pinyin: "wǒ zhǐ xǐhuan nǐ.",
        ko: "나는 너만 좋아한다.",
        meaning_ko: "오직, ~만",
        meanings_extra: ["단지"],
        part_of_speech: "부사"
      },
      {
        no: 285,
        word: "只有…才…",
        word_traditional: "只有…才…",
        pinyin: "zhǐyǒu…cái…",
        zh: "只有努力才有成功。",
        zh_traditional: "只有努力才有成功。",
        zh_pinyin: "zhǐyǒu nǔlì cái yǒu chénggōng.",
        ko: "오직 노력해야 성공할 수 있다.",
        meaning_ko: "오직 ~해야만 ~하다",
        meanings_extra: ["~해야만"],
        part_of_speech: "구문"
      },
      {
        no: 286,
        word: "中文",
        word_traditional: "中文",
        pinyin: "zhōngwén",
        zh: "我会说中文。",
        zh_traditional: "我會說中文。",
        zh_pinyin: "wǒ huì shuō zhōngwén.",
        ko: "나는 중국어를 할 수 있다.",
        meaning_ko: "중국어",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 287,
        word: "中间",
        word_traditional: "中間",
        pinyin: "zhōngjiān",
        zh: "他站在两个人中间。",
        zh_traditional: "他站在兩個人中間。",
        zh_pinyin: "tā zhàn zài liǎng gè rén zhōngjiān.",
        ko: "그는 두 사람 사이에 서 있다.",
        meaning_ko: "중간",
        meanings_extra: ["사이"],
        part_of_speech: "명사"
      },
      {
        no: 288,
        word: "终于",
        word_traditional: "終於",
        pinyin: "zhōngyú",
        zh: "我终于完成了作业。",
        zh_traditional: "我終於完成了作業。",
        zh_pinyin: "wǒ zhōngyú wánchéng le zuòyè.",
        ko: "나는 드디어 숙제를 끝냈다.",
        meaning_ko: "마침내, 결국",
        meanings_extra: ["드디어"],
        part_of_speech: "부사"
      },
      {
        no: 289,
        word: "种",
        word_traditional: "種",
        pinyin: "zhǒng",
        zh: "这里有很多种花。",
        zh_traditional: "這裡有很多種花。",
        zh_pinyin: "zhèlǐ yǒu hěn duō zhǒng huā.",
        ko: "여기에는 꽃이 여러 종류 있다.",
        meaning_ko: "종류",
        meanings_extra: ["종"],
        part_of_speech: "명사"
      },
      {
        no: 290,
        word: "重要",
        word_traditional: "重要",
        pinyin: "zhòngyào",
        zh: "健康很重要。",
        zh_traditional: "健康很重要。",
        zh_pinyin: "jiànkāng hěn zhòngyào.",
        ko: "건강이 매우 중요하다.",
        meaning_ko: "중요하다",
        meanings_extra: [],
        part_of_speech: "형용사"
      },
      {
        no: 291,
        word: "周末",
        word_traditional: "週末",
        pinyin: "zhōumò",
        zh: "周末我们去旅游。",
        zh_traditional: "週末我們去旅遊。",
        zh_pinyin: "zhōumò wǒmen qù lǚyóu.",
        ko: "주말에 우리는 여행을 간다.",
        meaning_ko: "주말",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 292,
        word: "主要",
        word_traditional: "主要",
        pinyin: "zhǔyào",
        zh: "学习主要靠自己。",
        zh_traditional: "學習主要靠自己。",
        zh_pinyin: "xuéxí zhǔyào kào zìjǐ.",
        ko: "공부는 주로 자기 자신에게 달려 있다.",
        meaning_ko: "주된, 주요한",
        meanings_extra: ["중요한"],
        part_of_speech: "형용사"
      },
      {
        no: 293,
        word: "注意",
        word_traditional: "注意",
        pinyin: "zhùyì",
        zh: "上课要注意听讲。",
        zh_traditional: "上課要注意聽講。",
        zh_pinyin: "shàngkè yào zhùyì tīngjiǎng.",
        ko: "수업 시간에 집중해서 들어야 한다.",
        meaning_ko: "주의하다, 집중하다",
        meanings_extra: ["신경 쓰다"],
        part_of_speech: "동사"
      },
      {
        no: 294,
        word: "自己",
        word_traditional: "自己",
        pinyin: "zìjǐ",
        zh: "我自己做饭。",
        zh_traditional: "我自己做飯。",
        zh_pinyin: "wǒ zìjǐ zuò fàn.",
        ko: "나는 혼자서 밥을 한다.",
        meaning_ko: "자기 자신",
        meanings_extra: ["스스로"],
        part_of_speech: "대명사"
      },
      {
        no: 295,
        word: "自行车",
        word_traditional: "自行車",
        pinyin: "zìxíngchē",
        zh: "我骑自行车去学校。",
        zh_traditional: "我騎自行車去學校。",
        zh_pinyin: "wǒ qí zìxíngchē qù xuéxiào.",
        ko: "나는 자전거를 타고 학교에 간다.",
        meaning_ko: "자전거",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 296,
        word: "总是",
        word_traditional: "總是",
        pinyin: "zǒngshì",
        zh: "他总是迟到。",
        zh_traditional: "他總是遲到。",
        zh_pinyin: "tā zǒngshì chídào.",
        ko: "그는 항상 지각한다.",
        meaning_ko: "항상, 늘",
        meanings_extra: ["언제나"],
        part_of_speech: "부사"
      },
      {
        no: 297,
        word: "嘴",
        word_traditional: "嘴",
        pinyin: "zuǐ",
        zh: "他的嘴很大。",
        zh_traditional: "他的嘴很大。",
        zh_pinyin: "tā de zuǐ hěn dà.",
        ko: "그의 입이 매우 크다.",
        meaning_ko: "입",
        meanings_extra: [],
        part_of_speech: "명사"
      },
      {
        no: 298,
        word: "最后",
        word_traditional: "最後",
        pinyin: "zuìhòu",
        zh: "我最后到了学校。",
        zh_traditional: "我最後到了學校。",
        zh_pinyin: "wǒ zuìhòu dào le xuéxiào.",
        ko: "나는 마지막으로 학교에 도착했다.",
        meaning_ko: "마지막",
        meanings_extra: ["최종"],
        part_of_speech: "형용사/부사"
      },
      {
        no: 299,
        word: "最近",
        word_traditional: "最近",
        pinyin: "zuìjìn",
        zh: "你最近怎么样？",
        zh_traditional: "你最近怎麼樣？",
        zh_pinyin: "nǐ zuìjìn zěnmeyàng?",
        ko: "너 요즘 어때?",
        meaning_ko: "최근",
        meanings_extra: ["요즘"],
        part_of_speech: "부사"
      },
      {
        no: 300,
        word: "作业",
        word_traditional: "作業",
        pinyin: "zuòyè",
        zh: "我做完作业了。",
        zh_traditional: "我做完作業了。",
        zh_pinyin: "wǒ zuò wán zuòyè le.",
        ko: "나는 숙제를 다 했다.",
        meaning_ko: "숙제",
        meanings_extra: ["과제"],
        part_of_speech: "명사"
      }
  ]
  